### ISSUE TITLE
火狐浏览器 序列最后一行回车不能退出序列

### ISSUE THREAD

**Issue by rsl140** [wangeditor-team/wangEditor-v5#107]
## bug 描述

火狐浏览器 序列最后一行回车不能退出序列

## 你预期的样子是？

可以正常退出序列模式

## 浏览器及版本号
90.0.2

## 最小成本的复现步骤

- 步骤一 输入文本内容并设置为序列
- 步骤二 在最后一个序列末尾 点击回车 
- 步骤三 序列一直存在

**Comment by wangfupeng1988** [comment]
mac firefox 未复现。先关闭吧
