### ISSUE TITLE
选择含有链接文字时无法进行缩进

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/wangEditor-v5#133]
## bug 描述

选择含有链接文字时无法进行缩进

## 你预期的样子是？

选择含有链接文字时可以进行缩进

## 浏览器及版本号
all

## wangEditor 版本

v5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1. 选择该段文字  hello world ~~~ slate examples!
2. 尝试缩进

![image](https://user-images.githubusercontent.com/43435489/129470773-34119a24-3e36-468f-acde-2acf147d9031.png)

**Comment by wangfupeng1988** [comment]
但如果不全选一整行，只是光标点击某一行，则可正常缩进。

**Comment by wangfupeng1988** [comment]
和这个一起看 https://github.com/wangeditor-team/we-2021/issues/143

**Comment by wangfupeng1988** [comment]
已解决，下载 https://www.npmjs.com/package/@wangeditor/editor 最新版本即可
