### ISSUE TITLE
选中不同的div居中，后面的div居中了，含有图片的div没有居中

### ISSUE THREAD

**Issue by wangqiaoling01** [wangeditor-team/wangEditor-v5#143]
## bug 描述

*如下图，选中两行内容，点击居中，结果含有图片的div并没有居中，后面的div居中了。
单独选中含有图片的div时，内容没有居中
*
<img width="967" alt="image" src="https://user-images.githubusercontent.com/67910349/129528780-b96092fc-9ffc-4608-955f-c91644d55e7e.png">

## 你预期的样子是？

*选中内容居中，不影响其他内容*

## 浏览器及版本号

*Safari 版本14.1.1 (16611.2.7.1.4)*

## wangEditor 版本

*v5*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：default model -> create
- 步骤二：选中两行内容，其中一行含有图片
- 步骤三：居中

**Comment by wangfupeng1988** [comment]
chrome也有这个问题

**Comment by wangfupeng1988** [comment]
和这个问题一起看 https://github.com/wangeditor-team/we-2021/issues/133

**Comment by shi-lai-mu** [comment]
@wangqiaoling01 「后面的div居中了」没有复现，最新的代码可复现吗？
![image](https://user-images.githubusercontent.com/45140991/132305576-f92c84f3-8959-405f-8902-b8aba3070dbd.png)

**Comment by wangfupeng1988** [comment]
已解决，下载 https://www.npmjs.com/package/@wangeditor/editor 最新版本即可
