### ISSUE TITLE
设置文字颜色与背景色行为与预期不一致

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/wangEditor-v5#173]
## bug 描述

设置文字颜色与背景色行为与预期不一致

## 你预期的样子是？

未选择文字时 可以预先设置文字颜色 输入后文字呈现该颜色
未选择文字时 可以预先设置文字背景颜色 输入后文字呈现该背景颜色、
参考语雀

## 系统和浏览器及版本号
all
## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

1. 鼠标点击某一行
2. 设置背景颜色和文字颜色
3. 再输入文字

**Comment by wangfupeng1988** [comment]
还有一个问题：为选中文字时，点击“加粗”菜单（或其他下划线、删除线等），菜单没有切换为 active 状态，需输入文字之后，菜单才会被 active 。

![image](https://user-images.githubusercontent.com/9583120/147477559-3d45f8dd-f3ec-467b-aa2f-ee5499e53924.png)


和这个有点类似，可以一起看看。
