### ISSUE TITLE
优化：单元格内全选

### ISSUE THREAD

**Issue by shi-lai-mu** [wangeditor-team/wangEditor-v5#188]
功能描述
单元格内执行全选时 应全选单元格内内容!
![image](https://user-images.githubusercontent.com/45140991/132123542-52eba935-3b59-4979-8bf7-4e4bebdc0b2a.png)

当前为全选全内容!
![image](https://user-images.githubusercontent.com/45140991/132123560-df47f44a-7f04-4590-8246-85180c65f4c0.png)

可参考的案例
参考 语雀 单元格全选

**Comment by wangfupeng1988** [comment]
已解决，下载 https://www.npmjs.com/package/@wangeditor/editor 最新版本即可

PS：只有当 单元格内有内容时，才会全选单元格。单元格为空时，依然全选整个编辑器。
