### ISSUE TITLE
qq浏览器无法运行v5的vue2组件

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor-v5#195]
## bug 描述

qq浏览器无法运行v5的vue2组件
![image](https://user-images.githubusercontent.com/65208676/132340842-d303f353-0943-45ef-93e5-9d676ffcd60d.png)

## 你预期的样子是？

qq浏览器可以正常运行v5的vue2组件

## 系统和浏览器及版本号

- win10
- qq浏览器 10.8.2

## wangEditor 版本

 "@wangeditor/editor-cattle": "^0.7.0",
    "@wangeditor/editor-for-vue": "^0.6.3",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 在qq浏览器运行vue2 项目 ，
- 步骤二 项目中安装v5的vue2组件
- 步骤三 运行

**Comment by wangfupeng1988** [comment]
我测试着，React demo 在 qq 浏览器也有同样报错。

**Comment by blackhu0804** [comment]
"@wangeditor/editor-for-vue": "^0.6.6" 版本正常

**Comment by blackhu0804** [comment]
![image](https://user-images.githubusercontent.com/18188260/133627418-7c48c47c-72d7-43d9-aa55-a12d6415524b.png)
QQ浏览器使用 vue-cli 创建的项目直接运行会报错，删除node_modules里面的mjs文件可以正常运行。

**Comment by blackhu0804** [comment]
https://github.com/jsdom/jsdom/issues/3205   好像是jsdom引入的bug

**Comment by blackhu0804** [comment]
https://github.com/facebook/jest/issues/11571 jest 有相关issue提到该问题

**Comment by blackhu0804** [comment]
> ![image](https://user-images.githubusercontent.com/18188260/133627418-7c48c47c-72d7-43d9-aa55-a12d6415524b.png)
> QQ浏览器使用 vue-cli 创建的项目直接运行会报错，删除node_modules里面的mjs文件可以正常运行。

这个要参考 https://www.wangeditor.com/v5/guide/for-frame.html#vue-cli
