### ISSUE TITLE
列表对齐失败

### ISSUE THREAD

**Issue by wangqiaoling01** [wangeditor-team/wangEditor-v5#198]
## bug 描述

*选中前两行，将其设置为无序列表，然后将其居中或者居右，含有超链接的li不能正确对齐*
![image](https://user-images.githubusercontent.com/67910349/132927893-d1134eea-f341-4e1c-b724-1b5962adbddf.png)

## 你预期的样子是？

*正确对齐*

## 系统和浏览器及版本号

- 操作系统：Windows
- 浏览器和版本：Edge  版本 93.0.961.38 (官方内部版本) (64 位)

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：进入 http://106.12.198.214:8882/main/examples/default-mode.html，选中前两行
- 步骤二：设置为无序列表
- 步骤三：居中 / 居右

**Comment by wangqiaoling01** [comment]
有序列表问题同上

**Comment by leohai** [comment]
- Transforms.setNodes 时，会判断选中部分的层级结构进行遍历匹配到节点类型是否Element，如上选择时 paragraph 和 link 都为element 类型，导致api不生效。
- 解决方法: 修改选项mode为较高层级
