### ISSUE TITLE
分割线能光标聚焦

### ISSUE THREAD

**Issue by leohai** [wangeditor-team/wangEditor-v5#200]
## bug 描述

*插入分割线后点击它，光标会聚焦在分割线里*
![image](https://user-images.githubusercontent.com/34530234/132952218-61bd05af-8604-4c32-876b-76e2a1dae924.png)

## 你预期的样子是？

*光标不能聚焦在分割线里*

## 系统和浏览器及版本号

- mac
- chrome 92

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 插入分割线
- 鼠标点击分割线
- 光标会聚焦在分割线里

**Comment by wangfupeng1988** [comment]
这个问题，目前没有想到好的解决办法。先待定
