### ISSUE TITLE
编辑区域无内容时，创建表格，然后ctrl+a键全选删除，导致无法换行

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor-v5#211]
## bug 描述

编辑内容无内容时，创建表格，然后ctrl+a键全选删除，导致回车无法换行样式也错了

## 你预期的样子是？

正常输入

## 系统和浏览器及版本号

- mac，window
- Chrome、Edge 最新版

## wangEditor 版本

"@wangeditor/editor": "^0.10.0",
"@wangeditor/editor-cattle": "^0.8.0", 
"@wangeditor/editor-for-vue": "^5.1.5-1",

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 把内容清空
- 步骤二 创建表格，然后ctrl+a全选内容
- 步骤三 按删除键

**Comment by wangfupeng1988** [comment]
不要输入任何文字内容，否则就复现不了了。

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor-v5/issues/271 重复了
