### ISSUE TITLE
h4和h5 字体大小 是一样的效果

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor-v5#212]
## bug 描述

h4和h5 字体大小 貌似是一样的效果

## 你预期的样子是？

有区分

## 系统和浏览器及版本号

mac
- Chrome 

## wangEditor 版本

"@wangeditor/editor": "^0.10.0",
"@wangeditor/editor-cattle": "^0.8.0",
"@wangeditor/editor-for-vue": "^5.1.5-1",

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 依次创建 h4 h5 标题
- 步骤二 查看区别
- 步骤三 对比

**Comment by wangfupeng1988** [comment]
我这里看着是有差距的。
![image](https://user-images.githubusercontent.com/9583120/135006522-418a6b19-8ffa-4b77-80bd-857945b31d36.png)

**Comment by shi-lai-mu** [comment]
![image](https://user-images.githubusercontent.com/45140991/135006874-208cf298-05eb-41a4-9b4b-f1aa26681a25.png)
有差距

**Comment by shi-lai-mu** [comment]
![image](https://user-images.githubusercontent.com/45140991/135006924-5fbe2194-dd09-4868-bc1a-b05d0d2d4cd7.png)
有差距

**Comment by liuqh0609** [comment]
![image](https://user-images.githubusercontent.com/43341115/135006976-6c988ac3-ad69-4966-a694-e8fa7a559e10.png)
