### ISSUE TITLE
编辑内容超长时，在最底部点击tooltip菜单，滚动条会恢复最顶部

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor-v5#213]
## bug 描述

编辑内容超长时，在最底部点击tooltip菜单，滚动条会恢复最顶部

## 你预期的样子是？

不滚动

## 系统和浏览器及版本号

- mac
- Mac OS - Safari

## wangEditor 版本

"@wangeditor/editor": "^0.10.0",
    "@wangeditor/editor-cattle": "^0.8.0",
    "@wangeditor/editor-for-vue": "^5.1.5-1",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 输入内容，输入内容超过外层的高度
- 步骤二 创建链接，然后点击链接显示tooltip菜单
- 步骤三 点击修改按钮，点击确定，效果如图
- 
![2021-09-22 14-48-54 2021-09-22 14_49_11](https://user-images.githubusercontent.com/65208676/134808860-48524a01-7e32-4502-a002-4f143d59483e.gif)

**Comment by wangfupeng1988** [comment]
当前代码的测试页 http://106.12.198.214:8882/main/examples/default-mode.html 在 safari 未复现
