### ISSUE TITLE
复制图片，粘贴上传，然后全选删除内容，无法删除图片（windows QQ 浏览器）

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor-v5#216]
## bug 描述

复制图片，粘贴上传，然后全选删除内容，无法删除图片

## 你预期的样子是？

正常删除图片

## 系统和浏览器及版本号

- window 10
- qq浏览器

## wangEditor 版本

"@wangeditor/editor": "^0.10.0",
    "@wangeditor/editor-cattle": "^0.8.0",
    "@wangeditor/editor-for-vue": "^5.1.5-1",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 浏览器某个地方复制一张图片 
- 步骤二 粘贴在编辑器内，然后全选删除
- 步骤三 无法删除图片，其他内容正常删除，

**Comment by wangfupeng1988** [comment]
当前最新代码未复现。先关闭，继续观察
