### ISSUE TITLE
开始编辑时选择了代码或其他格式无法在前一行或后一行继续编写无样式内容

### ISSUE THREAD

**Issue by 1164461842** [wangeditor-team/wangEditor-v5#221]
## bug 描述
![image](https://user-images.githubusercontent.com/54823693/136649662-f714c22c-fb8f-4aec-9eae-e06d0dab7bce.png)

## 你预期的样子是？
可以两次回车后继续输入无格式内容

## 系统和浏览器及版本号

- 操作系统 WIN10 
- 浏览器和版本 Google Chrome  92.0.4515.159（正式版本） （64 位）

## wangEditor 版本
v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤
在开始输入时直接选择行内代码样式或者直接输入代码块格式内容，输入之后回车后面也是对应格式的内容，无法继续输入非代码格式的内容

**Comment by wangfupeng1988** [comment]
“可以两次回车后继续输入无格式内容” —— 这是针对 代码块 的，并不是针对 行内代码。

例如，你开始设置了加粗，也是需要“两次回车去掉加粗”吗？我感觉这并不合理。
