### ISSUE TITLE
建议增加预览模式

### ISSUE THREAD

**Issue by Shen120** [wangeditor-team/wangEditor-v5#223]
## 功能描述

建议增加预览模式

## 提炼几个功能点

- 编辑后可预览编辑的内容

## 可参考的案例

github 编辑器的预览

**Comment by wangfupeng1988** [comment]
这个完全可以用户自己实现，而且做起来很简单。

- 可以使用 `disable` 和 `enable` 两个 API （[文档](https://www.wangeditor.com/v5/guide/API.html#disable)）切换编辑器可用状态，实现预览。
- 或者，自己实现预览。新建一个按钮，点击时获取内容，并新建一个 div 渲染内容。
