### ISSUE TITLE
编辑器中添加图片后点击图片被禁止对齐

### ISSUE THREAD

**Issue by zhenghui8485** [wangeditor-team/wangEditor-v5#224]
## bug 描述

编辑器中添加图片后点击图片被禁止对齐

## 你预期的样子是？

可以选择对齐方式并进行对齐

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本 谷歌浏览器（版本 91.0.4472.164（正式版本） （64 位））

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 复制一段内容，粘贴到txt文本，然后从txt文档复制内容粘贴到编辑器中
- 步骤二 选择空行区域添加图片，并点击添加好的图片，被禁止选择对齐选项排列
- 
![image](https://user-images.githubusercontent.com/43600186/136653522-96e3cdea-946d-4f2a-871a-f4cc77e50f34.png)

- 步骤三 需全选图片区域才能选择对齐方式，例图片区域上方有文字会一并被统一对齐排列，而不能单选择图片进行对齐排列
![image](https://user-images.githubusercontent.com/43600186/136653528-f290e511-6278-41be-b7ec-5b84b8007baf.png)

**Comment by wangfupeng1988** [comment]
首先，目前不支持图文混排，不支持图片单独右对齐。只支持一行、一个段落的对齐方式。

所以，这个问题可以当做一个体验问题，但修改之后，也是针对一个段落的对齐方式，而不是单个图片。

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor-v5/issues/143 https://github.com/wangeditor-team/wangEditor-v5/issues/133 一起看看，都是对齐的问题，都一起解决吧。

**Comment by wangfupeng1988** [comment]
已解决，下载 https://www.npmjs.com/package/@wangeditor/editor 最新版本即可
