### ISSUE TITLE
使用 wangEditor 怎么将输入纯文本替换为 html 元素

### ISSUE THREAD

**Issue by nolan1230** [wangeditor-team/wangEditor-v5#228]
## 问题描述

我的需求：

输入过程中，如果检测到输入的文本有 #tag# （符合 #text# 被认为是一个标签）,则将这个纯文本 #tag# 替换成 <i>#tag#</i>

## wangEditor 版本

@wangeditor/editor-for-react    v0.6.10

@wangeditor/editor       v0.10.2

## 是否查阅了文档 ？
是

https://www.wangeditor.com/v5/guide/for-frame.html#%E4%BD%BF%E7%94%A8
有查阅，貌似没有找到相关的api。

**Comment by wangfupeng1988** [comment]
markdown 插件应看法完 https://github.com/wangeditor-team/wangEditor-plugin-md
