### ISSUE TITLE
V4 如何升级到 V5 ？ V5 无法用 html 格式编辑

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#233]
## 问题描述

V4 存储的是 html ，而 V5 需要用 JSON 数据才能编辑。
如果我现在使用 V4 ，想要直接升级到 V5 ，那历史文件就无法编辑了，该怎么办？

## wangEditor 版本

V5

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
![image](https://user-images.githubusercontent.com/9583120/140691747-a48e05fb-64a7-458e-9a0a-dfd92f35c893.png)

**Comment by koibi2** [comment]
> V5 不支持保存、回显 html。

个人认为这个改动太大了。
风险太高，暂不会升级：

1. 过去的 html 数据不兼容 V5。只能用不同的编辑器回显，等于以后永远2个编辑器。维护成本太高。
2. 存储2个字段太消耗储存空间、性能。感觉无法说服后端。
3. 从别的地方复制的 html 富文本，无法带格式粘贴。这是很常见的需求，若不支持，感觉用户会投诉。
4. 协同编辑之类的也用不到。或者说 V5 的新优化、新功能感觉不够亮眼。

不知道其它用户有没有这个想法，或者 wangEditor 团队有没有做过用户调研。
个人只能选择观望。等等看 dangerouslyPasteHTML 等 API 能否支持。
祝越来越好。

**Comment by wangfupeng1988** [comment]
@koibi2 这个改动很大，给 v4 升级的用户造成了很多困扰，这个我是承认的。不过确实没有办法，html 是一个完全不可控的数据结构，为了以后的扩展性我们不得不放弃。

V5 这次重构，相比于 V4 是很大的进步，从功能到体验再到稳定性都完全不一样了。V4 的很多棘手的 bug 在 V5 将不再出现。
当然如果你觉得不够亮，那可能是你本身的需求就是简单的富文本编辑，用不到那么多扩展的东西。如果是这样，我也建议继续用 V4

粘贴 html 格式和 `dangerouslyInsertHtml ` 可以看这里 https://github.com/wangeditor-team/wangEditor-v5/issues/283 ，测试的差不多了，近期将会发布。

**Comment by czphappy** [comment]
同意koibi2的说法

**Comment by czphappy** [comment]
同意koibi2 的说法

**Comment by czphappy** [comment]
同意koibi2 的说法
1.content字段实在太消耗储存空间。无法说服后端。因为富文本不会是单独使用的，肯定会和其他输入控件一起使用。
2.过去的 html 数据不兼容 V5。而且后端修改难度比较大，维护成本太高。无法说服（尝试过N次）
3.协同编辑需求实在不大，
4.与其让我们支持两个编辑器，为什么不能在V5支持两种模式的回显，虽然存在显示bug，但有些业务确实不需要这么复杂的要求。而且，我们希望升级V5，主要是看重他的界面和新功能。
5.修改成本太高，即使是新入手V5，开发成本也比较高，恕我直言，感觉V5版本会叫好不叫座。

**Comment by wangfupeng1988** [comment]
@czphappy 有问题我就改，最近我会高优支持这个问题。

**Comment by wangfupeng1988** [comment]
功能已开发完，开始邀请测试 https://github.com/wangeditor-team/wangEditor-v5/issues/351

**Comment by tonyhan0702** [comment]
V5版本，会支持html格式编辑吗？升级到一半，发现v5无法html编辑，这个影响很大呀，希望官方给出明确回复，我们好定后续的开发方案，谢谢！

**Comment by wangfupeng1988** [comment]
> 功能已开发完，开始邀请测试 #351

@tonyhan0702 看这里。

正在高优支持中，计划在春节前发布该功能

**Comment by wangfupeng1988** [comment]
@czphappy @koibi2 @tonyhan0702 最新版本已经支持“回显 html”，可查阅文档 https://www.wangeditor.com/v5/guide/getting-started.html#%E8%AE%BE%E7%BD%AE-html
