### ISSUE TITLE
是不是还没支持复制word文本字符

### ISSUE THREAD

**Issue by zjslqshqz** [wangeditor-team/wangEditor-v5#246]
## 问题描述

word 文本复制进去的文字变成了图片

## wangEditor 版本

5

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

是不是还没支持复制word文本字符？v4 正常

**Comment by wangfupeng1988** [comment]
v5 默认不再支持带样式的复制、粘贴。

该功能会在 v5 发布之后，后续再开发单独的插件。
