### ISSUE TITLE
使用React组件时如何切换语言

### ISSUE THREAD

**Issue by He-Dongwei-GitHub** [wangeditor-team/wangEditor-v5#247]
## 问题描述

*在使用React组件时，引入`i18nChangeLanguage`并使用`i18nChangeLanguage('en')`修改语言没有效果。如何才能在使用React组件的情况下切换语言呢？*

## wangEditor 版本

*"@wangeditor/editor": "^0.10.3",
 "@wangeditor/editor-for-react": "^0.6.10"*

## 是否查阅了文档 ？

（文档链接 https://www.wangeditor.com/v5/guide/i18n.html ）

*是*

**Comment by wangfupeng1988** [comment]
我们跟踪一下这个问题。

**Comment by a835100635** [comment]
vue3使用正常，如下图
![image](https://user-images.githubusercontent.com/65208676/140480270-5720ad52-e36f-4749-9432-ef9144c577be.png)
vue2x使用正常，如下图
![image](https://user-images.githubusercontent.com/65208676/140480353-48bef474-7358-4b14-8c67-2e180f3e0e1a.png)

**Comment by He-Dongwei-GitHub** [comment]
我使用的是`@wangeditor/editor-for-react": "^0.6.10`这个组件；而`i18nChangeLanguage('en')`这个方法对前面提到的react组件并不能生效。

**Comment by TGuoW** [comment]
@He-Dongwei-GitHub 你好，确认下，是否是使用create-react-app创建的应用

**Comment by He-Dongwei-GitHub** [comment]
> @He-Dongwei-GitHub 你好，确认下，是否是使用create-react-app创建的应用

@TGuoW 使用的是umi

**Comment by wangfupeng1988** [comment]
这俩 npm 包升级到最新版本就可以了

```
    "@wangeditor/editor": "^0.10.4",
    "@wangeditor/editor-for-react": "^0.6.11",
```
