### ISSUE TITLE
React 环境下，注册插件是否有效？需验证

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#248]
## 问题描述

React 环境下，注册插件是否有效，验证一下。参考文档 https://www.wangeditor.com/v5/guide/development.html#slate-%E6%8F%92%E4%BB%B6

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

**Comment by He-Dongwei-GitHub** [comment]
在使用这个组件的前提下(`@wangeditor/editor-for-react": "^0.6.10`)：
参考文档里的注册组件的方式并不能生效

**Comment by wangfupeng1988** [comment]
@He-Dongwei-GitHub 这俩 npm 包升级到最新版本，就可以了

```
    "@wangeditor/editor": "^0.10.4",
    "@wangeditor/editor-for-react": "^0.6.11",
```
