### ISSUE TITLE
react中使用V5版本，初始化时defaultContent的children数组大于2时会出错

### ISSUE THREAD

**Issue by yangtaiqiong** [wangeditor-team/wangEditor-v5#249]
## bug 描述

在react中使用，当初始化的默认content的children数组元素超过2个时会报错。
  
此处children属性数组有两个（详细看复现步骤），显示正常：

![%Y71S{B)Y94XR`RL9I}F{XQ](https://user-images.githubusercontent.com/41353824/140466517-966579a5-33c9-4531-8bf8-e09fa239767b.png)

当children属性数组有三个，显示报错
![5QM1N%7TK~U5%10X~}5V7EX](https://user-images.githubusercontent.com/41353824/140466420-674f8e7c-306a-46d3-96ae-4addb905ac7d.png)

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- windows 10
- 浏览器和版本
   谷歌浏览器
## wangEditor 版本

"@wangeditor/editor": "^0.10.3",
"@wangeditor/editor-for-react": "^0.6.10"

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一创建默认内容，且保证children数组元素超过三个
- let content = [
    {
      style: {
        textAlign: 'center',
      },
      type: 'paragraph',
      children: [
        {
          color: '#000000',
          fontSize: '24',
          bold: 'true',
          text: '1701',
        },

        {
          color: '#000000',
          fontSize: '24',
          bold: 'true',
          text: '1701',
        },
        {
          color: '#000000',
          fontSize: '24',
          bold: 'true',
          text: '1701',
        },
      ],
    },
  ];
- 步骤二带入@wangeditor/editor-for-react的Editor组件中：
- <Editor
        defaultConfig={editorConfig}
        defaultContent={content}
        mode="default"
        style={{ height: '500px' }}
      />
- 步骤三打开浏览器，报错
- 
![5QM1N%7TK~U5%10X~}5V7EX](https://user-images.githubusercontent.com/41353824/140466283-70353430-233f-4794-8903-3b3679171ac0.png)

**Comment by wangfupeng1988** [comment]
属性完全一样的 text ，要合并为一个节点，不要分开。

![image](https://user-images.githubusercontent.com/9583120/140477507-3c0ee797-fee5-4e7f-be6a-216abb9468e2.png)

你试试这样写会报错吗？

```js
[
        {
            type: 'header1',
            children: [{ text: '标题'}]
        },
        {
            type: 'paragraph',
            children: [
                { text: 'hello', bold: 'true' },
                { text: ' '},
                { text: 'hello', underline: 'true' },
            ]
        },
]
```
