### ISSUE TITLE
图片 hoverbar menu 自定义

### ISSUE THREAD

**Issue by CarmenHYC** [wangeditor-team/wangEditor-v5#251]
## 问题描述

1.图片上传时，如果上传文件大于2M，控制台直接报错，没有弹窗提示，定义回调onFailed和onError未触发；
2.图片插入后点击图片出来的编辑菜单可不可以自定义？比如可以去掉菜单上的编辑按钮，像用于内容在微信小程序显示的话，跳转连接是没有用的，如果有些功能在，会导致甲方提出无理要求

## wangEditor 版本

V5 for vue typescript

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

直接点击上传图片

**Comment by wangfupeng1988** [comment]
图片体积默认限制 2M ，可以通过 `maxFileSize` 执行修改 https://www.wangeditor.com/v5/guide/menu-config.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

**Comment by wangfupeng1988** [comment]
关于 hoverbar 的自定义，目前还不支持。不过这个j建议很好，我们会尽快优化它。

![image](https://user-images.githubusercontent.com/9583120/140476650-fbf969f8-da06-459f-ab62-916a495a5572.png)

**Comment by wangfupeng1988** [comment]
最新版本已经支持 hoverbar menu 自定义
https://www.wangeditor.com/v5/guide/editor-config.html#%E4%BD%BF%E7%94%A8-element-type
