### ISSUE TITLE
在react中，想使用Boot.registerRenderElem(conf)来自定义扩展新功能

### ISSUE THREAD

**Issue by yangtaiqiong** [wangeditor-team/wangEditor-v5#253]
## 问题描述

您好，我想在react当中使用自定义扩展新功能，创建一个自定义的节点，按照文档的自定义扩展新功能编写简单的测试代码，发现自己自定义的节点并未生效，不知道是自定义扩展新功能是不能在react中使用还是我用法出了问题，想请清楚这方面的前辈解答一二

## wangEditor 版本

"@wangeditor/editor": "^0.10.3",
"@wangeditor/editor-for-react": "^0.6.10",

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

我将其简化为一个简单的组件，如下所示，本意想通过点击按钮，来添加一个自定义节点，自定义节点会返回一个h1的标题显示在富文本编辑器中

`import React, { useState } from 'react';
import { Boot, SlateTransforms } from '@wangeditor/editor';
import { Editor } from '@wangeditor/editor-for-react';

function DocEditor(props) {
  const [editor, setEditor] = useState(null);

  const editorConfig = {
    placeholder: '请输入内容...',
  };

  //注册自定义节点
  Boot.registerRenderElem({
    type: 'myType',
    renderElem: function(elem, children, editor) {
      const vnode = h('h1', {}, children);
      console.log('kkk');
      return vnode;
    },
  });

  editorConfig.onCreated = editor => {
    setEditor(editor);
  };

  //想通过点击的方式插入我自定义的节点
  function onClickInsert() {
    SlateTransforms.insertNodes(editor, [
      {
        type: 'myType',
        children: [{ text: 'xxx' }],
      },
    ]);
  }

  return (
    <div>
      <Editor
        defaultConfig={editorConfig}
        defaultContent={[]}
        mode="default"
        style={{ height: '500px' }}
      />
      <button onClick={onClickInsert}>click</button>
    </div>
  );
}

//最后在react中导出该组件
export default DocEditor;
`

**Comment by wangfupeng1988** [comment]
该问题已经找到原因，正在全力修复中。

**Comment by yangtaiqiong** [comment]
好的，辛苦您了

**Comment by TGuoW** [comment]
@yangtaiqiong 你好，确认下，是否是使用create-react-app创建的应用

**Comment by yangtaiqiong** [comment]
@wangfupeng1988 不是，我是用umi创建的应用

**Comment by yangtaiqiong** [comment]
@TGuoW 不是，我是用umi创建的应用，但是我也在create-react-app创建的应用中试了一下，还是没有达到预期的效果

**Comment by wangfupeng1988** [comment]
好的，这个问题我们会高优处理的

**Comment by wangfupeng1988** [comment]
这俩 npm 包升级到最新版本，就可以了

```
    "@wangeditor/editor": "^0.10.4",
    "@wangeditor/editor-for-react": "^0.6.11",
```
