### ISSUE TITLE
图片添加跳转地址,缺少css属性

### ISSUE THREAD

**Issue by panghaoyuan** [wangeditor-team/wangEditor-v5#255]
## 问题描述

插入图片添加跳转链接后，鼠标移动到图片上时，光标不会出现点击样式（小手）
如何图片加了链接，自动添加点击样式

``` css 
cursor: pointer
```

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

*是*

**Comment by wangfupeng1988** [comment]
个人以为这样不可取。

鼠标的 `cursor: pointer` 样式，是告诉用户，这是一个链接，可以点击，点击之后可以跳转。
如果图片加了这个样式，点击之后又不能跳转，这就符合预期了。

不过，据你的问题，我觉得可以在图片的右上角加一个其他的 icon 来表示一下图片有链接。像这种

![image](https://user-images.githubusercontent.com/9583120/140888586-81ee136f-5e47-40f9-bb45-6a78ce808d79.png)

**Comment by panghaoyuan** [comment]
> 个人以为这样不可取。
> 
> 鼠标的 `cursor: pointer` 样式，是告诉用户，这是一个链接，可以点击，点击之后可以跳转。 如果图片加了这个样式，点击之后又不能跳转，这就不符合预期了。
> 
> 不过，据你的问题，我觉得可以在图片的右上角加一个其他的 icon 来表示一下图片有链接。像这种
> 
> ![image](https://user-images.githubusercontent.com/9583120/140888586-81ee136f-5e47-40f9-bb45-6a78ce808d79.png)

 抱歉，我刚才可能描述的不够清楚，因为图片添加链接是可选的，当添加了跳转时是否应该由编辑器提供鼠标的 cursor: pointer 样式，没添加链接时，不添加这个样式。

图片右上角这种形式时编辑器提供，还是我需要自行添加。

**Comment by wangfupeng1988** [comment]
1. 即便图片添加了链接，也不应该有 `cursor: pointer` 。因为有了它，就说明可以点击跳转，而现在是不支持点击图片跳转的。
2. 图片右上角这种形式 —— 这个要编辑器提供，目前不支持扩展。

**Comment by panghaoyuan** [comment]
> 1. 即便图片添加了链接，也不应该有 `cursor: pointer` 。因为有了它，就说明可以点击跳转，而现在是不支持点击图片跳转的。
> 2. 图片右上角这种形式 —— 这个要编辑器提供，目前不支持扩展。

我之前提过一个issue，不是通过额外添加代码可以支持支持点击图片跳转吗？

#238 这个issue

**Comment by wangfupeng1988** [comment]
那是你自己展示内容时，并不是在编辑内容时。
