### ISSUE TITLE
插入js代码块，先写方法体最后， 方法名称使用中文输入法拼音，回车输入时出现重复内容

### ISSUE THREAD

**Issue by SmartWuJun** [wangeditor-team/wangEditor-v5#258]
## bug 描述
function ceshiceshi(){
}

## 你预期的样子是？

function ceshi(){
}

## 系统和浏览器及版本号
widnow10 
chrome95

## wangEditor 版本
v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

官网
插入代码块 javascript
首先插入内容 function (){}
在输入法 切换到中文， 在() 前面 插入 ceshi 拼音 然后回车 ，出现两个 ceshiceshi

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/demo/zh-CN 可以复现。Mac OS + chrome 95 + Mac 自带中文输入法

![image](https://user-images.githubusercontent.com/9583120/141066991-32389968-84f5-4552-b0a5-94048e3cb109.png)

**Comment by lkw199711** [comment]
https://www.wangeditor.com/demo/zh-CN 可以复现。win10 + chrome 94 + 微软拼音输入法
