### ISSUE TITLE
没有能直接修改编辑器内容的api，回填内容很麻烦

### ISSUE THREAD

**Issue by Teal-H** [wangeditor-team/wangEditor-v5#261]
## 功能描述
希望跟v4版本一样可以直接给编辑器赋值
*请输入内容……*
目前要回填编辑器遇到问题：
以用createEditor({ content })只能设置默认值
在很多实际场景中这个content是动态的
## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
第一，你说的 `很多实际场景中这个content是动态的` 这个我认同。但你可以在获得 content 之后再去创建编辑器，延迟创建即可。例如在 Vue React 中，ajax 请求结束之后再创建编辑器
- vue2 https://juejin.cn/post/7030722267264843783#heading-6
- vue2 https://juejin.cn/post/7027977252331585544#heading-6
- react https://juejin.cn/post/7030584414652334093#heading-6

第二，如果你必须要先创建编辑器，然后再重新 rewrite 内容（像 v4 的 `txt.html(...)`），那 v5 目前的 API 也是支持的，可以去看[文档](https://www.wangeditor.com/v5/guide/API.html#insertnodes)

```js
// 重新赋值编辑器内容
editor.select([])
editor.deleteFragment()
SlateTransforms.insertNodes(editor, [
  { type: 'paragraph', children: [{ text: 'aaa' }] },
  { type: 'paragraph', children: [{ text: 'bbb' }] }
])
SlateTransforms.removeNodes(editor, { at: [0] })
```

第三，不建议使用一个编辑器，频繁的切换不同文档。一个编辑器，就服务于一个文档。如果切换文档，那就销毁该编辑器，重建编辑器。

**Comment by wangfupeng1988** [comment]
对了，上述第二条，我后续可以封装成一个 API `rewriteContent` 。但其实代码还是那几行。
