### ISSUE TITLE
getHtml 获取带表格的数据报错

### ISSUE THREAD

**Issue by Miss-Sixty** [wangeditor-team/wangEditor-v5#270]
## bug 描述

getHtml 获取带表格的数据报错：
Error: Cannot get table row node by cell node {"type":"table-cell","children":[{"text":"测试"}]}

## 你预期的样子是？

正常获得htnl代码

## 系统和浏览器及版本号

mac&windows

## wangEditor 版本

^0.12.3

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

```javascript
//vue3
 const editor = createEditor({
    content: [
      {
        type: 'table',
        children: [
          {
            type: 'table-row',
            children: [
              {
                type: 'table-cell',
                children: [{ text: '测试' }],
              },
            ],
          },
        ],
        withHeader: true,
      },
    ],
  })

editor.getHtml()
```

**Comment by wangfupeng1988** [comment]
vue3 环境下未复现这个问题 （mac os + chrome）
![image](https://user-images.githubusercontent.com/9583120/142723899-b57da695-5f46-448a-adc2-978a880b8789.png)

**Comment by Miss-Sixty** [comment]
> vue3 环境下未复现这个问题（mac os + chrome） ![图片](https://user-images.githubusercontent.com/9583120/142723899-b57da695-5f46-448a-adc2-978a880b8789.png)

![image](https://user-images.githubusercontent.com/40154623/142727259-a974609c-8ed7-4df3-acbb-6f8271a83864.png)
环境：vite + mac os + vue3 + chrome
我只是想用 createEditor({content}) 来将结构数据转换为 html 输出出来，并没有创建编辑器，上面图片是我使用的所有代码。

**Comment by wangfupeng1988** [comment]
已复现，我高优看下。

**Comment by wangfupeng1988** [comment]
升级最新的版本试一下

**Comment by Miss-Sixty** [comment]
> 升级最新的版本试一下

嗯，新版本问题解决了
