### ISSUE TITLE
npm ERR! notarget No matching version found for @wangeditor/code-highlight@^0.7.7.

### ISSUE THREAD

**Issue by ZHT131** [wangeditor-team/wangEditor-v5#275]
## bug 描述

我使用npm按照文档中所说安装v5版本报错了，提示：
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @wangeditor/code-highlight@^0.7.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@wangeditor/editor'

## 你预期的样子是？

正常安装

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 chrome最新版

## wangEditor 版本

v5

**Comment by wangfupeng1988** [comment]
这是一个 bug ，我会尽快解决。
使用 yarn 安装，它会让你选择版本，你每个选择最新版即可。

**Comment by ZHT131** [comment]
> 这是一个错误，我会尽快 使用纱线安装，它可以解决你选择的版本，你每次选择最新版本。

我目前项目是基于npm install的有什么解决方案吗

**Comment by ZHT131** [comment]
> 这是一个 bug ，我会尽快解决。 使用 yarn 安装，它会让你选择版本，你每个选择最新版即可。

或者说v4版本可以在vue3中正常使用吗？

**Comment by wangfupeng1988** [comment]
@ZHT131 稍等，我今天下午就搞定这个问题。

**Comment by ZHT131** [comment]
> @ZHT131 稍等，我今天下午就搞定这个问题。

好的，感谢

**Comment by wangfupeng1988** [comment]
重新发布了，再安装试试吧。
