### ISSUE TITLE
Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement]

### ISSUE THREAD

**Issue by pupillxy** [wangeditor-team/wangEditor-v5#276]
## 问题描述

自己实例化 写一个组件  然后 if 去判断是否显示   第一次显示正常 第二次就  Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement]
去掉  Boot.registerMenu(menuConf)  就不会报错 

## wangEditor 版本

0.12.7

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

class customVideo implements IButtonMenu {
      readonly title = '插入视频';
      readonly iconSvg = CUSTOM_VIDEO_SVG;
      readonly tag = 'button';

      getValue(editor: IDomEditor): string | boolean {
        // 用不到 getValue
        return '';
      }

      isActive(editor: IDomEditor): boolean {
        const node = DomEditor.getSelectedNodeByType(editor, 'blockquote');
        return !!node;
      }

      isDisabled(editor: IDomEditor): boolean {
        if (editor.selection == null) return true;

        const [nodeEntry] = Editor.nodes(editor, {
          match: n => {
            const type = DomEditor.getNodeType(n);

            // 只可用于 p 和 blockquote
            if (type === 'paragraph') return true;
            if (type === 'blockquote') return true;

            return false;
          },
          universal: true,
          mode: 'highest', // 匹配最高层级
        });

        // 匹配到 p blockquote ，不禁用
        if (nodeEntry) {
          return false;
        }
        // 未匹配到，则禁用
        return true;
      }

      exec(editor: IDomEditor, value: string | boolean) {

        state.uoloadKey = 'video';
        state.uploadType = [4];
        state.show = true;

      }

    }

![V`VFGX3`Y 1V3Y)$9YN W45](https://user-images.githubusercontent.com/41733945/144006891-dba3b3d2-fcb9-41b5-8d94-cbd55820d749.png)

**Comment by wangfupeng1988** [comment]
需要能复现问题的，比较详细的代码。例如：
1. 不知道你用的什么技术栈，vue 还是 react ？
2. 你说“写一个组件 然后 if 去判断是否显示”，是怎么实现的？

否则我们复现不了问题。

PS：你代码可以提交到 github 给我们链接。也可以提交到 https://codesandbox.io/

**Comment by pupillxy** [comment]
https://codesandbox.io/embed/beautiful-kirch-oguy9?fontsize=14&hidenavigation=1&theme=dark

**Comment by pupillxy** [comment]
> 需要能复现问题的，比较详细的代码例如：
> 
> 1. 不知道你还是用什么技术栈，vue react ？
> 2. 你说“写一个组件然后如果去判断是否显示”，是怎么实现的？
> 
> 否则我们复现不了问题。
> 
> PS：你代码可以提交到github给我们链接。也可以提交到https://codesandbox.io/


这个  麻烦看一下哦 不知道啥原因  字号文字不会关闭  链接等 报错
https://codesandbox.io/embed/beautiful-kirch-oguy9?fontsize=14&hidenavigation=1&theme=dark

**Comment by pupillxy** [comment]
> 需要能复现问题的，比较详细的代码。例如：
> 
> 1. 不知道你用的什么技术栈，vue 还是 react ？
> 2. 你说“写一个组件 然后 if 去判断是否显示”，是怎么实现的？
> 
> 否则我们复现不了问题。
> 
> PS：你代码可以提交到 github 给我们链接。也可以提交到 https://codesandbox.io/

文字 字号不会自动关闭  链接等报错  隐藏显示后报错  麻烦看一下哦
https://codesandbox.io/embed/beautiful-kirch-oguy9?fontsize=14&hidenavigation=1&theme=dark

**Comment by pupillxy** [comment]
这个&nbsp; &nbsp;那些问题都在~&nbsp; &nbsp; https://codesandbox.io/embed/beautiful-kirch-oguy9?fontsize=14&amp;hidenavigation=1&amp;theme=dark




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 下午5:17
收件人: ***@***.***&gt;; 
抄送: "(10E4W20) 活 动 中 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor-v5] Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement] (Issue #276)





 
需要能复现问题的，比较详细的代码。例如：
  
不知道你用的什么技术栈，vue 还是 react ？
 
你说“写一个组件 然后 if 去判断是否显示”，是怎么实现的？
  
否则我们复现不了问题。
 
PS：你代码可以提交到 github 给我们链接。也可以提交到 https://codesandbox.io/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
https://codesandbox.io/embed/beautiful-kirch-oguy9?fontsize=14&hidenavigation=1&theme=dark 报错
![image](https://user-images.githubusercontent.com/9583120/144153003-f0978f9a-4aca-4666-9220-35ea8505dcae.png)

**Comment by wangfupeng1988** [comment]
看代码，你这种显示隐藏方式肯定是不对的。你只管限制隐藏 DOM ，而不管 editor 对象。你在 nextTick 里 createEditor ，即每次组件更新都 createEditor ，但是去从没有 destroy editor ，这就是问题。

你如果要显示/隐藏 ，不应该只切换 DOM ，应该是针对整个 editor 的（且隐藏时要销毁 editor）。参考这里 https://github.com/wangeditor-team/wangEditor-for-vue/blob/main/example/App.vue

**Comment by wangfupeng1988** [comment]
我还有一个疑问。在 vue 下，你为何不用 编辑器 [vue 组件](https://www.wangeditor.com/v5/guide/for-frame.html#vue3)呢？为啥非要自己重新写。

**Comment by pupillxy** [comment]
我从头往下翻的&nbsp; &nbsp;等到看到&nbsp; 已经写了一些了 就随便了&nbsp; &nbsp;我改成组件看看&nbsp; 谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 上午9:17
收件人: ***@***.***&gt;; 
抄送: "(10E4W20) 活 动 中 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor-v5] Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement] (Issue #276)





 
我还有一个疑问。在 vue 下，你为何不用 编辑器 vue 组件呢？为啥非要自己重新写。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pupillxy** [comment]
这个不知道啥原因&nbsp; 第一次进去就这样&nbsp; 刷新下就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 上午9:06
收件人: ***@***.***&gt;; 
抄送: "(10E4W20) 活 动 中 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor-v5] Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement] (Issue #276)





 
https://codesandbox.io/embed/beautiful-kirch-oguy9?fontsize=14&amp;hidenavigation=1&amp;theme=dark 报错
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
