### ISSUE TITLE
选字体 字号等 下拉选项  都不会自动关闭 需要重新再点一次

### ISSUE THREAD

**Issue by pupillxy** [wangeditor-team/wangEditor-v5#277]
## bug 描述

1、自己实例化的  然后修改字号 字体 这些 选择后  下拉框需要重新点掉
![image](https://user-images.githubusercontent.com/41733945/144008269-53729abb-d206-4c9a-afe4-9c004feab77c.png)

2、选择链接  网络图片  报错： Cannot find textarea instance by editor
![image](https://user-images.githubusercontent.com/41733945/144008233-a415e165-e0ab-47e7-aabf-d4396febf559.png)

## 你预期的样子是？
选择后自动关闭

## 系统和浏览器及版本号

- 操作系统 w11
- 浏览器和版本 Google Chrome  版本 96.0.4664.45

## wangEditor 版本

^0.12.7

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤
具体不清楚是怎么回事   想来请教一下  是不是我自己哪里没配置了

**Comment by wangfupeng1988** [comment]
未回复，先关闭了

**Comment by itshizhan** [comment]
编辑器 放在 element-ui 的dialog 中时会出现

**Comment by wangfupeng1988** [comment]
统一在这个 issue 跟踪 https://github.com/wangeditor-team/wangEditor-v5/issues/435
