### ISSUE TITLE
遇到的一些问题

### ISSUE THREAD

**Issue by wulibaibao** [wangeditor-team/wangEditor-v5#278]
## bug 描述

1. 空文档直接插入表格、代码段、分割线会插入空白行
![image](https://user-images.githubusercontent.com/22147011/144158413-9f384612-b2c2-4dc1-bfa6-6cdd0eea2350.png)

2. 表格最后回车换行会插入1空白行
![image](https://user-images.githubusercontent.com/22147011/144158453-0c84ec15-b0db-4870-9e19-f41e64083c5e.png)

3. 点击文字颜色左边工具颜色下拉不会关闭（右边其他弹框都不会关闭）
![image](https://user-images.githubusercontent.com/22147011/144158493-3fb05768-78ab-4c59-b9c8-1bebd5756ef3.png)

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
1 和 2 是故意这么做的，否则表格上面、下面就不方便写入内容了。

3 请描述如何复现，我用 chrome 在 demo 没复现这个问题。

**Comment by wangfupeng1988** [comment]
没回复，先关闭了。
