### ISSUE TITLE
test: 测试粘贴 html ( editor.dangerouslyInsertHtml )

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#283]
## 背景

粘贴遇到 `text/html` 格式，会执行 `editor.dangerouslyInsertHtml`  （**注意：dangerously ，不保证识别所有 html**）

当遇到 `text/plain` 或者 `text/rtf` 时照常走之前的逻辑：粘贴纯字符串

## 测试地址

http://106.12.198.214:8882/feature-insert-html/examples/ （其中随便一个页面）

## 浏览器兼容性

测试浏览器兼容性：主流的 PC 浏览器，如 Chrome Firefox Safari Edge 等

## 可识别的 html 标签

- `<p>`
- `<h1>` `<h2>` 等标题 —— 内部只粘贴纯文本
- `<a>`
- `<img>`
- `<pre><code>...</code></pre>`
- `<ul>` `<ol>` `<li>` —— 内部只粘贴纯文本

其他不识别的标签，则走默认的逻辑：粘贴纯文本

## 测试过程和要求

过程
- 复制一段网页的内容，粘贴到编辑器中，可识别上述 html 标签
- 复制 word excel 等其他工具的文本（`text/rtf` 格式），粘贴到编辑器中，仍然粘贴纯文本

打开 chrome 控制台，**不要出现 js 报错**

**Comment by wangfupeng1988** [comment]
也可以直接在 chrome 控制台执行 `editor.dangerouslyInsertHtml(`<p>123123</p>`)` 插入 html ，和粘贴是一个逻辑。

**Comment by wangfupeng1988** [comment]
用户希望支持 table 粘贴 

但目前 table 还不支持单元格合并，万一粘贴进一个 merged-cell table ，会出现混乱，因为[这里](https://github.com/wangeditor-team/wangEditor-v5/blob/main/packages/table-module/src/module/plugin.ts#L156)

需要处理

**Comment by wangfupeng1988** [comment]
`insertDomElem` 要增加 maxLength 判断

**Comment by cced3000** [comment]
建议加上 <strong> 和 <em>标签。文本编辑常用的，复制场景里也是非常常见。

**Comment by cced3000** [comment]
黏贴HTML，顶部会自动插入空白区块。确定不是黏贴的HTML问题，随便复制都会。测试的案例：http://www.techweb.com.cn/it/2021-12-03/2868150.shtml
![image](https://user-images.githubusercontent.com/300924/144558485-30cd4546-6110-4b81-b0e2-1bc2351e8888.png)

**Comment by wangfupeng1988** [comment]
@cced3000 你提的建议，我优化了一下，可以在测试页试试。

**Comment by cced3000** [comment]
@wangfupeng1988 上面的两个问题，测试正常了。又发现一种场景，就是复制黏贴的图文内容，如果复制到图文存在换行br 标签，不会过滤，导致复制到wangEditor编辑器里，又会出现大量到空行情况，目前编辑器没有比较好到格式化选择，无法去除此类问题，需要手动删除。类似到情况我估计还会有，最合理到做法还是应该通过设置保留标签来提升复制黏贴到编辑器里到效果。

**Comment by wangfupeng1988** [comment]
@cced3000 我刚测试了一下，如果复制的内容里有 2 行 `<br>` ，粘贴到编辑器会是 4 个空行，这是一个 bug 。

修复以后，2 行 `<br>` 粘贴出来依然是 2 个空行，而不是去掉空行。

**Comment by wangfupeng1988** [comment]
@cced3000 粘贴空行`<br>`的问题你可以再试试。目前的策略是，复制了一个 `<p><br><p>` 空行，粘贴时也是一个空行。

**Comment by a835100635** [comment]
![image](https://user-images.githubusercontent.com/65208676/145023159-d6615427-62c7-499b-b43e-cb7575b1cc3a.png)
![image](https://user-images.githubusercontent.com/65208676/145023997-869cc9e6-3db9-4e60-941c-615d56ffd137.png)

excel 上复制的内容 粘贴在编辑器中，变成了图片
环境：mac  Chrome 火狐

**Comment by a835100635** [comment]
![image](https://user-images.githubusercontent.com/65208676/145027094-85d387d4-aaa4-478f-aac0-a3927c82dfd3.png)
http://106.12.198.214:8882/feature-insert-html/examples/simple-mode.html 测试的结果如下图
![image](https://user-images.githubusercontent.com/65208676/145027115-529479b5-1ca8-4a97-9f0e-46dfbe50f329.png)
https://www.wangeditor.com/demo/zh-CN/  测试的结果如下图
![image](https://user-images.githubusercontent.com/65208676/145027163-33edd3e2-9b7c-45d9-8573-0f6f5e8dcfd0.png)

**Comment by a835100635** [comment]
粘贴的内容格式发生变化

**Comment by q378532364** [comment]
win10 谷歌 版本 95.0.4638.69
粘贴excel 变成图片
![image](https://user-images.githubusercontent.com/43435489/145162105-990ea9a4-76b9-4142-8e70-7c927d120cf0.png)

**Comment by wangfupeng1988** [comment]
@q378532364 粘贴 excel ，以及粘贴 https://www.toutiao.com/a6930511507121832452/?channel=&source=search_tab 的问题搞定了，使用测试页 http://106.12.198.214:8882/feature-insert-html/examples/default-mode.html （强制刷新）

**Comment by a835100635** [comment]
![image](https://user-images.githubusercontent.com/65208676/146187516-87f9e806-bca2-4df7-bae1-c74772a6936c.png)
粘贴excel 格式内容 样式错乱

**Comment by wangfupeng1988** [comment]
表格问题已修复

**Comment by wangfupeng1988** [comment]
已发布，下载最新的 `@wangeditor/editor`

**Comment by z1948296027** [comment]
复制粘贴后样式丢失
![image](https://user-images.githubusercontent.com/28519207/146318984-22c7ae89-46dd-48af-b8e1-6740f4775114.png)

**Comment by wangfupeng1988** [comment]
@z1948296027 第一，用 [测试页](http://106.12.198.214:8882/feature-insert-html/examples/simple-mode.html) 测试，官网 demo 会有延迟。第二，不保证所有的样式都支持，粘贴会调用 `dangerouslyInsertHtml` ，关键词 **dangerously**

**Comment by SunJary** [comment]
> @z1948296027 第一，用 [测试页](http://106.12.198.214:8882/feature-insert-html/examples/simple-mode.html) 测试，官网 demo 会有延迟。第二，不保证所有的样式都支持，粘贴会调用 `dangerouslyInsertHtml` ，关键词 **dangerously**

测试页粘贴一个网页进去是纯文本，没有样式呀
