### ISSUE TITLE
打包出来的 js 不是 ES5 ，有箭头函数

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#284]
## bug 描述

如题

## 你预期的样子是？

ES5 标准

**Comment by echoLC** [comment]
初步定位比较大的可能是因为 babel 和 ts 配置 exclude 了 node_modules 下的包，所以，如果 node_modules 使用了 es6 模块的包，就会可能打包出来有问题。

**Comment by wangfupeng1988** [comment]
去掉 exclude 试试

**Comment by wangfupeng1988** [comment]
我今晚试的结果

第一，按照 pr 增加 `mainFields: ['main']` ，打包不会报错，但结果中依然有箭头函数

第二，删除 babel 中的 `exclude` 和 `include` ，打包结果没有箭头函数（非常慢...），但运行 example 会报错：`e is not a function `

```js
  babel({
    rootMode: 'upward',
    babelHelpers: 'runtime',
    // exclude: 'node_modules/**',
    // include: 'src/**',
    extensions,
  }),
```

**Comment by echoLC** [comment]
原因是我们依赖的第三方包 nanoid 和 @uppy/core 等一系列的包是含有箭头函数的，所以导致我们打包出来后含有箭头函数，暂时没有找到解决方案。

**Comment by wangfupeng1988** [comment]
不好搞就先这样吧，还好目前的用户环境基本都支持 es6
