### ISSUE TITLE
行间距：1、1.15、1.5，编辑区行间距并没有没有发生改变

### ISSUE THREAD

**Issue by lianghuiyong** [wangeditor-team/wangEditor-v5#285]
## 行间距：1、1.15、1.5，编辑区行间距并没有没有发生改变
![DZ9Q03O@8JS$_%QBWD@GIOH](https://user-images.githubusercontent.com/10268228/144716307-8d880b54-8850-406c-8780-2816de126e1b.png)

![3BT{Y{G8I2(1AVW DK%}PS7](https://user-images.githubusercontent.com/10268228/144716281-61483760-fd9b-45c1-8dcf-ca2e2b276239.png)

![)8KS~@HQZ GLV(ZY YW{}F7](https://user-images.githubusercontent.com/10268228/144716289-6f6adc4a-f1f5-41a3-b42f-07a9ad107858.png)

![6S3EJ6WP06)%9W1)R`@LHLV](https://user-images.githubusercontent.com/10268228/144716297-44af1084-853b-4db9-bb25-40c1bcdcf116.png)

## 你预期的样子是？

行间距正常显示

## wangEditor 版本

"@wangeditor/editor-for-vue": "^0.6.12-2"

**Comment by wangfupeng1988** [comment]
测试了一下，demo 可以复现
DOM 里确实已经修改了 line-height ，但显示效果没有发生变化。

**Comment by wangfupeng1988** [comment]
已修复，下个版本就发布
