### ISSUE TITLE
设置代码块后，无法将光标定位到结尾

### ISSUE THREAD

**Issue by yaniswang** [wangeditor-team/wangEditor-v5#290]
## bug 描述

*设置代码块后，如果代码块是最后面的内容，光标就无法定位在结尾*

## 你预期的样子是？

*设置代码块后，光标可以定位到代码块的后面，方便在代码块的后面添加新的内容*

## 系统和浏览器及版本号

- mac
- chrome 96

## wangEditor 版本

*v5 0.12.8*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 步骤一： 打开DEMO：https://www.wangeditor.com/demo/zh-CN/
- 步骤二： 输入：abc
- 步骤三：设置代码块

这个时候，就再也无法将光标移动到结尾

![image](https://user-images.githubusercontent.com/970390/144811180-ad92de85-0868-492d-a3b7-18a95069fba7.png)

**Comment by wangfupeng1988** [comment]
连续换行多次，即可退出。

不过这个策略目前确实有体验问题，正在考虑优化。

**Comment by yaniswang** [comment]
代码块内部我觉得应该允许连续换行。

代码块的结尾，也应该允许进行光标定位。

**Comment by wangfupeng1988** [comment]
`代码块的结尾，也应该允许进行光标定位。` —— 这是什么意思？

**Comment by wangfupeng1988** [comment]
> 连续换行多次，即可退出。
> 
> 不过这个策略目前确实有体验问题，正在考虑优化。

最新版本做了优化，下载安装试试
