### ISSUE TITLE
创建一个Table时能不能显示“行”和“列”的数量

### ISSUE THREAD

**Issue by BOKE2014** [wangeditor-team/wangEditor-v5#292]
## 问题描述
创建一个Table时能不能显示“行”和“列”的数量

*请输入遇到的问题...*
插入Table时需要自己数数，比较麻烦，能不能显示“行”和“列”的数量

## wangEditor 版本
V5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
好建议，可以在这两个地方加。

![image](https://user-images.githubusercontent.com/9583120/144987639-2267a7dd-f11a-47c7-ac08-04e3c86765ad.png)

**Comment by wangfupeng1988** [comment]
下载最新版本试试。

**Comment by BOKE2014** [comment]
好的
