### ISSUE TITLE
编辑器中输入的空格进行保留

### ISSUE THREAD

**Issue by 1316168367** [wangeditor-team/wangEditor-v5#295]
## 功能描述

*编辑器中输入的空格进行保留*

## 提炼几个功能点

在连续输入空格时 希望在content 中保留的数据能够把空格转换成&nbsp; 

## 原型图

无

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
需要在 `getHtml()` 时候把空格改为 `&nbsp;` 

但，content （即 `editor.children`）是不会改的，空格就是空格。

**Comment by wangfupeng1988** [comment]
> 需要在 getHtml() 时候把空格改为 &nbsp;

其实不用这样改，你是要在显示的时候加 `white-space: pre-wrap;` 样式即可
