### ISSUE TITLE
使用 加粗、下划线、斜体、删除线 时调用 getHtml() 返回的字符串会多返回几个空格

### ISSUE THREAD

**Issue by JJLau626** [wangeditor-team/wangEditor-v5#296]
## bug 描述

如题，当我不用以上的功能时不会返回多余空格 比如：另起一行。

但在编辑器下是没有显示有空格

## 你预期的样子是？

希望不要带有非人为输入的空格返回

## 系统和浏览器及版本号

win10
chrome 96.0.4664.93（正式版本） （64 位）

## wangEditor 版本

0.12.7

## demo 能否复现该 bug ？

不能。因为 demo 没有调用 getHtml() 返回的结果值

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 单独选一行文字进行以上的 加粗、下划线、斜体、删除线 操作即可
- 调用 getHtml() 得到 html 字符串
- 在 css 的 white-space: pre-wrap 下的容器去渲染以上的返回值就会在该行的首部多出几个空格

**Comment by wangfupeng1988** [comment]
demo 中没有复现你说的空格。
![image](https://user-images.githubusercontent.com/9583120/145524619-59cc49fa-d8f1-4888-8fa4-e560d91085db.png)

你可以升级 `@wangeditor/editor` 最新版本试试，我记得之前有一个类似的 bug ，前几天解决了。

**Comment by JJLau626** [comment]
> demo 中没有复现你说的空格。 ![image](https://user-images.githubusercontent.com/9583120/145524619-59cc49fa-d8f1-4888-8fa4-e560d91085db.png)
> 
> 你可以升级 `@wangeditor/editor` 最新版本试试，我记得之前有一个类似的 bug ，前几天解决了。

仍然不行，我在demo上重新尝试一次。我是 ctrl + a 选取整段内容，再点击 ‘加粗’ 然后执行 getHtml() 方法返回了如图所示的空格。

![image](https://user-images.githubusercontent.com/26458821/145527255-bcb2ef19-c50a-4af8-902b-97975348a392.png)

如图：打框的地方会有几个空格。

**Comment by wangfupeng1988** [comment]
哦，我知道了。这不是空格，这是格式化。不顾我正在打算去掉它。会高优处理。

**Comment by JJLau626** [comment]
> 哦，我知道了。这不是空格，这是格式化。不顾我正在打算去掉它。会高优处理。

好的，先麻烦王哥了。

**Comment by JJLau626** [comment]
> 哦，我知道了。这不是空格，这是格式化。不顾我正在打算去掉它。会高优处理。

那么，我有什么办法可以自行解决这个问题吗？

**Comment by wangfupeng1988** [comment]
你可以先使用 `editor.getHtml({ withFormat: false })`

**Comment by wangfupeng1988** [comment]
下载 `@wangeditor/editor` 最新版，然后直接使用 `editor.getHtml()` 试试
