### ISSUE TITLE
剪切之后html标签依然存在

### ISSUE THREAD

**Issue by 1316168367** [wangeditor-team/wangEditor-v5#297]
## bug 描述
在新建一个超链接之后 ，再剪切改链接 ，getHtml获取到的数据中新建的a标签依然存在，文本信息没有了，然后再次粘贴刚刚复制的东西还是会新增一个a标签

## 你预期的样子是？
希望能够去除原来的a标签

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本  Chrome 96.0.4664.93

## wangEditor 版本
v5

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 步骤一  新建 链接
- 步骤二  剪切新建的链接
- 步骤三  粘贴链接  查看getHtml

**Comment by wangfupeng1988** [comment]
demo 可复现
![image](https://user-images.githubusercontent.com/9583120/145545064-b0d09731-6c2a-489f-b58a-b3072d751ce4.png)

**Comment by wangfupeng1988** [comment]
解决方案：link module 中可以加一个 `normalizeNode` ，判断内容为空则删除链接

**Comment by wangfupeng1988** [comment]
解决了。下载 `@wangeditor/editor` 最新版本试一下
