### ISSUE TITLE
是否可以增加公式功能

### ISSUE THREAD

**Issue by jkfan** [wangeditor-team/wangEditor-v5#298]
## 是否可以增加公式功能

*由于要做试题相关的页面，里面需要使用富文本编辑器插入公式*
现在使用的是ueditor+kityformula-plugin的方式，但这种方式有一个缺点，就是项目的体积增大了许多，如果wangeditor中能集成或者以插件的方式可以加入公式功能，就太完美了，万分感谢。

**Comment by wangfupeng1988** [comment]
v5 是可以支持的。
这个功能我早就记录下了，会在 v5 正式发布之后慢慢更新上。需要一些时间。

**Comment by wangfupeng1988** [comment]
v5 已经支持数学公式 https://github.com/wangeditor-team/wangEditor-plugin-formula
