### ISSUE TITLE
editor.children方式保存，转成html后报错 " Cannot get table row node by cell node "

### ISSUE THREAD

**Issue by zys-1024** [wangeditor-team/wangEditor-v5#300]
## 问题描述
编辑器插入了table，以editor.children方式保存。前端请求到数据后转成html后报错 " Cannot get table row node by cell node "

## wangEditor 版本
v5

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

- 前端获取 editor.children
- 发送到后端存储
- 前端请求保存的数据
- const editor = createEditor({content: JSON.stringify( 数据)})
- const html = editor.gethtml()
- 把html插入到指定位置
- 报错 Cannot get table row node by cell node

**Comment by wangfupeng1988** [comment]
`把html插入到指定位置` 是指什么？

PS：不知道你 `@wangeditor/editor` 版本是不是最新的，我记得之前有一个类似的 bug ，早就修复了。

**Comment by zys-1024** [comment]
> `把html插入到指定位置` 是指什么？
> 
> PS：不知道你 `@wangeditor/editor` 版本是不是最新的，我记得之前有一个类似的 bug ，早就修复了。

就是转换成html，然后渲染到页面，好像不是新版本，我直接npm install wangeditor下载的 没有指定版本下载

**Comment by wangfupeng1988** [comment]
`npm install wangeditor` 那你安装的是 v4 ，不是 v5
v5 的文档 https://wangeditor.com/v5
