### ISSUE TITLE
如果可以输出PDF和Word就完美了

### ISSUE THREAD

**Issue by BOKE2014** [wangeditor-team/wangEditor-v5#301]
## 功能描述
PDF和Word输出
*请输入内容……*
不可否认Wangeditor是目前看到的一款非常棒的开源编辑器，在线功能非常好。从使用者的角度讲：很多时候还是离不开PDF和Word，如果在不久的将来Wangeditor可以实现PDF和Word的输出将会把基于网页的应用和传统的应用高效的结合在一起，这就像是一个纽带，可以利用Wangeditor在任意浏览器上进行修改和创作（也需要移动端必要的编辑功能），需要的时候可以输出PDF和Word与传统模式结合。
## 提炼几个功能点
输出PDF
输出Word
- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
你意思应该是导出 pdf 或者 word 文档吧？
这种导出功能，需要服务端支持。而 wangEditor 仅仅是一个前端的工具，没有服务端能力。

例如，给你一段 `<h1>title</h1><p>hello world</p>` html 代码，让你去导出它的 pdf 和 word ，其实这跟编辑器没有关系。

**Comment by BOKE2014** [comment]
完全明白。我们不可能要求开源的项目面面俱到，前端和后端都要做，目前的V5版本已经很棒了。只是在实际的场景里面确实有类似的需求。总之，非常感谢这个开源的项目。

**Comment by wangfupeng1988** [comment]
感谢你们的支持，我会继续慢慢的完善其他功能~
