### ISSUE TITLE
图片位置的调整

### ISSUE THREAD

**Issue by BOKE2014** [wangeditor-team/wangEditor-v5#303]
## 问题描述
调整图片放置位置的快捷方式
*请输入遇到的问题...*
插入一个图片后，如果像选中文字一样选中图片是可以利用Toolbar里的工具使图片靠左，居中和靠右放置的的，但是比较麻烦。如果能够在“点中”图片弹出的小toolbar里增加靠左，居中和靠右放置的选项就方便太多了
## wangEditor 版本
V5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
你可以通过修改 hoverbarKeys 的配置来实现，文档参考 https://www.wangeditor.com/v5/guide/editor-config.html#hoverbarkeys

核心代码

```js
    editorConfig.hoverbarKeys = {
      'image': {
        menuKeys: [
          'imageWidth30',
          'imageWidth50',
          'imageWidth100',
          'editImage',
          'viewImageLink',
          'deleteImage',
          'justifyLeft',
          'justifyCenter',
          'justifyRight',
        ],
      }
    }
```
