### ISSUE TITLE
使用标题如：H1、H2 等后就不能使用“加粗”选项

### ISSUE THREAD

**Issue by JJLau626** [wangeditor-team/wangEditor-v5#309]
## 问题描述

如标题

## wangEditor 版本

0.12.9

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 写上一行文字
- 选择任意一个标题
- 在点击“加粗”

![image](https://user-images.githubusercontent.com/26458821/146295468-2f505470-4f27-4bda-ba66-70b061797876.png)

**Comment by wangfupeng1988** [comment]
是的，故意这么设置的。标题不能取消加粗。

**Comment by JJLau626** [comment]
> 是的，故意这么设置的。标题不能取消加粗。

我看V4版可以这么做，不知道V5能否用配置去控制，因为标题确实有是用到加粗的场景。😭😭😭😭😭😭

**Comment by JJLau626** [comment]
>

**Comment by JJLau626** [comment]
> 是的，故意这么设置的。标题不能取消加粗。

可是这里会遇到一个问题，我使用‘正文’写一段文字，然后加粗，再选 ‘H1’ 就不能取消加粗，会让人产生疑惑。

![image](https://user-images.githubusercontent.com/26458821/146343444-b92c3d30-84a2-45d3-9b97-29c13b2b8b81.png)

**Comment by JJLau626** [comment]
> 是的，故意这么设置的。标题不能取消加粗。

可是这里会遇到一个问题，我使用‘正文’写一段文字，然后加粗，再选 ‘H1’ 就不能取消加粗，会让人产生疑惑。

![image](https://user-images.githubusercontent.com/26458821/146343444-b92c3d30-84a2-45d3-9b97-29c13b2b8b81.png)

**Comment by wangfupeng1988** [comment]
这确实是一个问题，待我优化一下

**Comment by JJLau626** [comment]
> 这确实是一个问题，待我优化一下

我看V4版就可以这么操作，相对自由一些，有时候我们根本不知道真实用户是以一个怎样的姿势使用你的产品。😂😂😂

**Comment by wangfupeng1988** [comment]
自由的代价就是：bug 太多改不过来。
我得找平衡。
