### ISSUE TITLE
工具栏配置了excludeKeys，但是结果跟期望的不太一致

### ISSUE THREAD

**Issue by wang-cola** [wangeditor-team/wangEditor-v5#310]
## bug 描述
配置了excludeKeys，已经排除掉了大部分功能，但是很多图标还留了下来，比如左右对齐 还有缩进图标等
![image](https://user-images.githubusercontent.com/21015798/146335504-3c4c9738-3d77-45e6-ba5f-265c11b2a7e6.png)

## 你预期的样子是？

预期就是 排除了的功能，那些图标也应该小时掉

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

"@wangeditor/editor": "^0.12.8",
"@wangeditor/editor-for-react": "^0.6.14",

## demo 能否复现该 bug ？

不能 因为demo的工具栏是默认的 没有进行配置

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
 const excludeKeys = [
            "underline",
            "italic",
            "through",
            "code",
            "sub",
            "sup",
            "clearStyle",
            "headerSelect",
            "header1",
            "header2",
            "header3",
            "header4",
            "header5",
            "color",
            "bgColor",
            "insertLink",
            "editLink",
            "unLink",
            "viewLink",
            // "insertImage",
            // "deleteImage",
            // "editImage",
            "viewImageLink",
            "imageWidth30",
            "imageWidth50",
            "imageWidth100",
            "blockquote",
            "emotion",
            "fontSize",
            "fontFamily",
            "indent",
            "delIndent",
            "justifyLeft",
            "justifyRight",
            "justifyCenter",
            "justifyJustify",
            "lineHeight",
            "redo",
            "undo",
            "divider",
            "deleteDivider",
            "codeBlock",
            "fullScreen",
            "bulletedList",
            "numberedList",
            "insertTable",
            "deleteTable",
            "insertTableRow",
            "deleteTableRow",
            "insertTableCol",
            "deleteTableCol",
            "tableHeader",
            "tableFullWidth",
            "insertVideo",
            "deleteVideo",
            // "uploadImage",
            "codeSelectLang",
            // 排除菜单组，写菜单组 key 的值即可
        ]
- 步骤二
  把上面的excludeKeys配置给toolbarConfig
 const toolbarConfig: Partial<IToolbarConfig> = {
        /* 工具栏配置 */
        excludeKeys: excludeKeys,// 排除菜单组
    }
- 步骤三

**Comment by wangfupeng1988** [comment]
你都把那么多菜单去掉了，干嘛要用 `excludeKeys` 呢？直接用 `toolbarkeys` 多方便啊
https://www.wangeditor.com/v5/guide/toolbar-config.html#toolbarkeys

**Comment by wangfupeng1988** [comment]
你需要把 group menu 也移除掉，通过 `toolbar.getConfig().toolbarKeys` 可以查看到

![image](https://user-images.githubusercontent.com/9583120/146343592-6760e423-0053-48ee-a924-7e2dcf61fd87.png)

**Comment by wang-cola** [comment]
> 你都把那么多菜单去掉了，干嘛要用 `excludeKeys` 呢？直接用 `toolbarkeys` 多方便啊 https://www.wangeditor.com/v5/guide/toolbar-config.html#toolbarkeys

因为我设置了toolbarkeys，也有问题，所以就想用excludeKeys试试，然后发现了这个问题。。。我最近的需求只需要一点加粗，link和上传图片就够用了

**Comment by wang-cola** [comment]
> 你需要把 group menu 也移除掉，通过 `toolbar.getConfig().toolbarKeys` 可以查看到
> 
> ![image](https://user-images.githubusercontent.com/9583120/146343592-6760e423-0053-48ee-a924-7e2dcf61fd87.png)

![image](https://user-images.githubusercontent.com/21015798/146349427-59b4647c-97b3-4935-a036-98a37eaf0fd4.png)
呼叫大佬 请问我在excludeKeys里加了group的key

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/guide/toolbar-config.html#excludekeys
这就有写
