### ISSUE TITLE
工具栏配置toolbarKeys，但是与预期不太一致

### ISSUE THREAD

**Issue by wang-cola** [wangeditor-team/wangEditor-v5#311]
## bug 描述

我只需求上传图片或文字加粗等一丢丢功能，所以给toolbarKeys做了配置
const toolbarKeys = [
            "bold",
            'image',
            "insertLink",
            "editLink",
            "unLink",
            "viewLink",
            "insertImage",
            "deleteImage",
            "editImage",
            "viewImageLink",
            "uploadImage"
            // 菜单组，写菜单组 key 的值即可
       ]
但是工具栏里就显示了一个加粗的图标，还是灰色disabled的
![image](https://user-images.githubusercontent.com/21015798/146336315-7904c34a-da8b-474b-a802-b87fb125daaa.png)

## 你预期的样子是？

预期按照toolbarKeys配置的数组来显示工具栏功能

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

"@wangeditor/editor": "^0.12.8",
"@wangeditor/editor-for-react": "^0.6.14",

## demo 能否复现该 bug ？

不能 因为demo没有进行工具栏配置

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  设置一个
  const toolbarKeys = [
            "bold",
            'image',
            "insertLink",
            "editLink",
            "unLink",
            "viewLink",
            "insertImage",
            "deleteImage",
            "editImage",
            "viewImageLink",
            "uploadImage"
            // 菜单组，写菜单组 key 的值即可
        ]
- 步骤二
  给工具栏进行配置
  const toolbarConfig: Partial<IToolbarConfig> = {
        /* 工具栏配置 */
        toolbarKeys: toolbarKeys
    }
- 步骤三
查看页面

**Comment by wangfupeng1988** [comment]
注意看一下页面的 js 报错
![image](https://user-images.githubusercontent.com/9583120/146343087-1032ff96-3931-4c1c-a120-df0b7acc094b.png)

`'image'` 是非法的菜单 key ，删掉就好了。
所有菜单 key 都可以通过 `editor.getAllMenuKeys()` 来获取
