### ISSUE TITLE
设置了hoverbarKeys，但是与预期的不太一致

### ISSUE THREAD

**Issue by wang-cola** [wangeditor-team/wangEditor-v5#312]
## bug 描述

hoverBar我只需求一丢丢的功能，所以想自定义配置一下，但是配置完，hover的时候什么都不显示了

## 你预期的样子是？
const hoverbarKeys = {
            'text': {
                menuKeys: ["bold"],
            },
        }
做了这个配置，预期是输入文字后 选中hover会出现加粗的功能图标

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

"@wangeditor/editor": "^0.12.8",
 "@wangeditor/editor-for-react": "^0.6.14",

## demo 能否复现该 bug ？

不能 demo没有做自定义配置

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  const hoverbarKeys = {
            'text': {
                menuKeys: ["bold"],
            },
        }
- 步骤二
  const editorConfig: Partial<IEditorConfig> = {
        hoverbarKeys: hoverbarKeys,
    }
- 步骤三
查看页面

**Comment by wangfupeng1988** [comment]
这个确实发现了问题。你可以先这样补救

```js
import { SlateRange, DomEditor, SlateText } from '@wangeditor/editor'

// 判断是否选中了 text
function isSelectedText(editor, n) {
  const { selection } = editor
  if (selection == null) return false // 无选区
  if (SlateRange.isCollapsed(selection)) return false // 未选中文字，选区的是折叠的

  const selectedElems = DomEditor.getSelectedElems(editor)
  const notMatch = selectedElems.some((elem) => {
    if (editor.isVoid(elem)) return true

    const { type } = elem
    if (['pre', 'code', 'table'].includes(type)) return true
  })
  if (notMatch) return false

  if (SlateText.isText(n)) return true // 匹配 text node
  return false
}

const hoverbarKeys = {
  'text': {
    match: isSelectedText,
    menuKeys: ["bold"],
  },
}
```

待下次版本发布之后，你再把 `match: isSelectedText` 删掉就行（不删也没关系，就是无用代码）
