### ISSUE TITLE
Vue3下defaultContent预设HTML和dangerouslyInsertHtml无法使用问题

### ISSUE THREAD

**Issue by Lrunlin** [wangeditor-team/wangEditor-v5#316]
## bug 描述

Vue3下官方提供Demo为：
`const defaultContent = [
     { type: 'paragraph', children: [{ text: '<p>1</p>ajax 异步获取的内容' }] }
]`
来预设text文本，文档中并没有预设HTML的方法，在onCreated生命中期中使用:
`function onCreated(editor) {
    editor.dangerouslyInsertHtml(props.html);
};`
无法实现HTML的插入
## 你预期的样子是？

编辑器在defaultContent中可以初始化HTML内容或者在onCreated生命周期中可以通过  editor.dangerouslyInsertHtml(props.html); 对内容进行重新设置

## 系统和浏览器及版本号

- 操作系统：WIN10
- 浏览器和版本：Chrome

## wangEditor 版本
"@wangeditor/editor": "^0.13.3",
  "@wangeditor/editor-for-vue": "^5.1.8-4",

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

Vue3创建子组件父组件传值或修改Key后渲染编辑器组件

**Comment by wangfupeng1988** [comment]
加一个 `setTimeout` 即可以了
```
const onCreated = (editor) => {
      // console.log('created', editor)
      setTimeout(() => {
          editor.dangerouslyInsertHtml('<p>hello</p>')
      })
    }
```

**Comment by Lrunlin** [comment]
使用setTimeout似乎是一个微任务和宏任务的问题，尝试了一下在父组件数据获取完成后使用v-if开始渲染编辑器组件时在onCreated生命周期中使用：
`function onCreated(editor) {
    setTimeout(() => {
        editor.dangerouslyInsertHtml(props.html)
    });
};`
编辑器中也是没有任何内容，但是console.log打印的值确是没有问题的

**Comment by wangfupeng1988** [comment]
你可以试试我做的 vue3 demo ，把我上次回复的代码加到这里 https://github.com/wangfupeng1988/vue3-wangeditor-demo/blob/main/src/components/MyEditor.vue#L71 。我试着是没问题的
