### ISSUE TITLE
希望增加“源码”编辑模式

### ISSUE THREAD

**Issue by kustone** [wangeditor-team/wangEditor-v5#318]
### 源码编辑模式

> 希望在工具中添加“查看/编辑”html源代码模式，方便对html及样式代码进行实时的编辑与导出。虽然可以自行实现，但还是希望能集成到项目中去。

**Comment by wangfupeng1988** [comment]
V5 的富文本模型是基于 vdom 的，不是基于 html的，所以不可能增加源码模式。

**Comment by kustone** [comment]
感谢答复，了解了。
