### ISSUE TITLE
设置了maxLength之后遇到的问题

### ISSUE THREAD

**Issue by wang-cola** [wangeditor-team/wangEditor-v5#319]
## 问题描述

设置了maxLength，比如maxLength=20，不能像textarea一样 显示0/20，其次，在复制了超过20长度的文本后，不能粘贴，要复制小于maxLength才能粘贴，还有就是加了换行之后，可输入的内容小于20
![image](https://user-images.githubusercontent.com/21015798/146860437-db90996d-502e-489c-899e-8c73f78f4092.png)
现在想做一些输入长度的限制，比如超出之后的报错提示，如何补救

## wangEditor 版本

"@wangeditor/editor": "^0.12.8",
"@wangeditor/editor-for-react": "^0.6.14",

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
 const maxLength=20
- 步骤二
 const editorConfig: Partial<IEditorConfig> = {
        maxLength: maxLength,
  }
- 步骤三
 查看页面

**Comment by wangfupeng1988** [comment]
说明一点：`不能像textarea一样 显示0/20` —— 这个你自己实现即可，编辑器不会默认实现。你可以通过 `editor.getText()` 获取当前文本内容。

**Comment by wangfupeng1988** [comment]
maxLength 优化了一些，可以在这个测试页试一试 http://106.12.198.214:8882/refactor-maxlength/examples/maxlength.html

不过，maxLength 情况非常复杂，目前还无法做到很完美，先能保证最基本的使用吧。

**Comment by wangfupeng1988** [comment]
又优化了一下，无法做到和 `<textarea>` 一样，不过已经算是做到成本和收益的最大化。
（粘贴、插入非纯文本，截取过程太复杂了，先不做）

强制刷新 http://106.12.198.214:8882/refactor-maxlength/examples/maxlength.html 测试
