### ISSUE TITLE
代码块无法选择滚动条拖动

### ISSUE THREAD

**Issue by liu724551711** [wangeditor-team/wangEditor-v5#320]
## bug 描述

添加代码块之后，通过鼠标选择代码块语言类型选择的滚动条时，整个选择窗口直接消失，只能通过鼠标滚轮进行选择语言

## 你预期的样子是？

能够正常拖动滚动条进行选择

## 系统和浏览器及版本号

win10
Google Chrome 94

## wangEditor 版本

v5

**Comment by wangfupeng1988** [comment]
请补充问题复现的步骤（否则复现不了问题，我也无法解决），然后再 reopen issue 。
