### ISSUE TITLE
vue版本在chrome（version<69）浏览器上传图片功能报错

### ISSUE THREAD

**Issue by DotQjw** [wangeditor-team/wangEditor-v5#321]
## bug 描述

*vue版本的富文本在版本低于<69的chrome浏览器使用富文本的上传图片功能报错，提示**Object.values(...).flat  is not a function**
 没有处理好这个兼容问题。
并且core-js 2.X版本不支持flat兼容
解决方案：单独安装引入array-flat-polifill.
*

## 你预期的样子是？

*打包时处理好兼容性问题， 不需要单独引包解决*

## 系统和浏览器及版本号

- windos
-chrome  version<69 （实测 v66,v62）
## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 在<69版本上的chrome浏览器使用上传图片功能
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
chrome 版本太低了，自己引入 polyfill  兼容一下吧，也不麻烦。
