### ISSUE TITLE
能否提供段间距功能，图片超链接功能或者跳转小程序

### ISSUE THREAD

**Issue by Only-silence** [wangeditor-team/wangEditor-v5#322]
## 功能描述

可以设置选中段落的段间距
添加图片时可否同时添加超链接，点击图片可跳转url
可配置小程序SDK后，添加点击图片跳转小程序功能

## 提炼几个功能点

- 设置段间距
- 图片超链接
- 图片跳转小程序

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
1. 段间距不会加了，需求量不大。需要的话自行扩展吧。
2. 现在添加图片就支持链接功能。如下图

![image](https://user-images.githubusercontent.com/9583120/147316935-f0b2d445-3d64-4b66-a836-6a83dba2d4d3.png)
