### ISSUE TITLE
每次发布时 @wangeditor/core 版本不会更新

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#326]
## bug 描述

每次发布时，所有 `peerDependencies` 依赖中， `@wangeditor/core` 的版本不会更新。

例如现在 packages/core 的版本是 `0.13.0` ， 而在 packages/basic-modules/package.json 中，依然是 `"@wangeditor/core": "^0.7.1"`

同时，packages/upload-image-module/package.json 的 `peerDependencies` 中，`@wangeditor/basic-modules` 的版本也不会随着发布更新。

## 你预期的样子是？

版本会随着发布更新。

## wangEditor 版本

V5

**Comment by echoLC** [comment]
如果是  peerDependencies，npm 机制就是这样的，所以 lerna 也不会去更新，详细解释参考：[
peerDependencies shouldn't be updated](https://github.com/lerna/lerna/issues/1018)。

**Comment by wangfupeng1988** [comment]
好吧，那先这样。
