### ISSUE TITLE
 Can not get editor instance

### ISSUE THREAD

**Issue by centersxy** [wangeditor-team/wangEditor-v5#329]
## 问题描述

使用yarn下载v5版本，页面切换时提示错误

*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/24762779/147634383-d0a6e41a-dc59-4c81-97ab-acd7ad5e2e29.png)

## wangEditor 版本
    "@wangeditor/editor": "^0.13.4",
    "@wangeditor/editor-for-vue": "^5.1.8-5",

## 是否查阅了文档 ？
[Vue3](https://www.wangeditor.com/v5/guide/for-frame.html#vue3)
使用文档上vue3的代码测试，无任何修改

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

  tab页切换时，控制台就打印该错误，

**Comment by wangfupeng1988** [comment]
还需要提供给一下，能复现问题的核心代码。

**Comment by centersxy** [comment]
### 编辑器代码使用vue3--官网例子未改动
```
<template>
  <div style="border: 1px solid #ccc">
    <Toolbar :editorId="editorId" :defaultConfig="toolbarConfig" :mode="mode" style="border-bottom: 1px solid #ccc" />
    <Editor
      :editorId="editorId"
      :defaultConfig="editorConfig"
      :defaultContent="getDefaultContent"
      :mode="mode"
      style="height: 500px"
    />
  </div>
</template>

<script>
  import { computed, onBeforeUnmount, ref } from 'vue';
  import { Editor, Toolbar, getEditor, removeEditor } from '@wangeditor/editor-for-vue';
  import cloneDeep from 'lodash.clonedeep';

  export default {
    components: { Editor, Toolbar },
    setup() {
      const editorId = `w-e-${Math.random().toString().slice(-5)}`; //【注意】编辑器 id ，要全局唯一

      const defaultContent = [{ type: 'paragraph', children: [{ text: '一行文字' }] }];
      const getDefaultContent = computed(() => cloneDeep(defaultContent)); // 注意，要深拷贝 defaultContent ，否则报错

      const toolbarConfig = {};
      const editorConfig = { placeholder: '请输入内容...' };

      // 组件销毁时，也及时销毁编辑器
      onBeforeUnmount(() => {
        const editor = getEditor(editorId);
        if (editor == null) return;

        editor.destroy();
        removeEditor(editorId);
      });

      return {
        editorId,
        mode: 'default',
        getDefaultContent,
        toolbarConfig,
        editorConfig,
      };
    },
  };
</script>
```

### 调用
![)2 S)YUHWVSOY18EO9`MZZD](https://user-images.githubusercontent.com/24762779/147644396-67414b3c-31ba-4dfb-bee2-a0e857b07e37.png)



###  tab切换
`<component :is="activeKey" :detail="detail" @refresh="getPageData()" />`

总结：当component 切换时会出现上述描述问题

**Comment by liuqh0609** [comment]
> 

你tab切换是怎么进行的？还是用的某个组件库的tab？如果可以的话麻烦提供一个最小复现的代码仓库，地址贴一下

**Comment by centersxy** [comment]
### 使用ant-design-vue
![image](https://user-images.githubusercontent.com/24762779/147719794-b7a4567b-1984-4ff2-9c26-9eda5fee3bda.png)

我刚才测试不使用a-tab组件进行切换，未出现 Can not get editor instance 错误

###  补充问题 ： 添加了自定义按钮切换时还会有此警告
![image](https://user-images.githubusercontent.com/24762779/147719984-dea7598c-056f-401c-b6cf-c6a8ba62760f.png)

### 代码实现
```
  // 定义清除菜单 class
  class InsertClearMenu implements IButtonMenu {
    readonly title = '清除';
    readonly tag = 'button';
    getValue() {
      return '';
    }
    isActive() {
      return false;
    }
    isDisabled() {
      return false;
    }
    async exec(editor) {
      editor.clear();
    }
  }

  Boot.registerMenu({
    key: 'InsertClearMenu', // menu key ，唯一。注册之后，可配置到工具栏
    factory() {
      return new InsertClearMenu();
    },
  });

  const toolbarConfig = {
    insertKeys: {
      index: 100,
      keys: ['InsertClearMenu'],
    },
  };
```

**Comment by liuqh0609** [comment]
你这个补充的问题可以另开一个issue，我看一下antd-vue的tab组件问题

**Comment by centersxy** [comment]
我猜想是实例没有销毁掉导致的重复添加，所以就补充在了下面。

**Comment by clinfc** [comment]
问题的原因很简单，你切换之前编辑器处于聚焦状态，然而当你点击编辑器外时刚好触发了编辑器的 blur 事件，此时内部还在执行 blur 的一些列回调。结果你却直接把编辑器销毁了，blur 的某些回调中拿不到编辑器实例就报错了呗。最快的解决方法如下：
```ts
onBeforeUnmount(() => {
  if (instance) {
    // 销毁前先手动失去焦点
    instance.blur()
    // 然后再异步销毁编辑器（异步延迟的最小值不能小于 500，即使为 500 仍有很小的概率会报错）
    setTimeout(() => {
      instance?.destroy()
      instance = null
    }, 1000)
  }
})
```

你可以尝试在切换前先让编辑器失去焦点，此时再切换将不再报错。

**Comment by shehuaqigai** [comment]
最新版本中还未解决这个问题，我在v3中也出现了这个问题，好像不是失去焦点的问题，我改成3秒会保存 no find textarea,加try catch都不行

**Comment by wangfupeng1988** [comment]
@shehuaqigai 提供给一个可以复现的 demo ，或者详细的复现步骤
