### ISSUE TITLE
添加了自定义按钮,切换页面或者重新打开提示重复注册

### ISSUE THREAD

**Issue by centersxy** [wangeditor-team/wangEditor-v5#330]
## 问题描述
添加了自定义按钮切换时会有此警告

![image](https://user-images.githubusercontent.com/24762779/147725293-f13ae14d-80b2-4a6b-97b7-7e08d2f91d58.png)

## wangEditor 版本

`  "@wangeditor/editor": "^0.13.4",
  "@wangeditor/editor-for-vue": "^5.1.8-5",
`

## 是否查阅了文档 ？

[文档链接: 注册菜单](https://www.wangeditor.com/v5/guide/development.html#buttonmenu)

## 最小成本的复现步骤

```
 // 定义清除菜单 class
  class InsertClearMenu implements IButtonMenu {
    readonly title = '清除';
    readonly tag = 'button';
    getValue() {
      return '';
    }
    isActive() {
      return false;
    }
    isDisabled() {
      return false;
    }
    async exec(editor) {
      editor.clear();
    }
  }

  Boot.registerMenu({
    key: 'InsertClearMenu', // menu key ，唯一。注册之后，可配置到工具栏
    factory() {
      return new InsertClearMenu();
    },
  });

  const toolbarConfig = {
    insertKeys: {
      index: 100,
      keys: ['InsertClearMenu'],
    },
  };
```

**Comment by wangfupeng1988** [comment]
你先不要写 `insertKeys`，直接初始化编辑器，然后打印 `toolbar.getConfig().toolbarKeys` 看看结果中有没有这个 `InsertClearMenu `？

------

获取 toolbar 可参考这个

```
import { DomEditor } from '@wangeditor/editor'
const toolbar = DomEditor.getToolbar(editor)
```

**Comment by centersxy** [comment]
使用的此api
```
    const editor= getEditor(editorId);
    console.log(editor.getAllMenuKeys());
```
![image](https://user-images.githubusercontent.com/24762779/147737356-77542e80-7768-4f16-ac95-0cd7efbbdfa5.png)

**Comment by centersxy** [comment]
@(https://github.com/wangeditor-team/wangEditor-v5/issues/330#issuecomment-1002925557)
使用你刚说的方法调用结果为：
![image](https://user-images.githubusercontent.com/24762779/147737674-8f6f4199-2e4f-49ae-9f6d-ab04d124fc71.png)

**Comment by wangfupeng1988** [comment]
我用这个 demo 复现了 https://github.com/wangfupeng1988/vue3-wangeditor-demo/blob/main/src/components/MyEditorExtend.vue

我这边的情况是：1. 直接创建编辑器不会报错；2. 如果异步渲染编辑器，就会报错；

我作为 bug 来跟踪吧。
