### ISSUE TITLE
悬浮编辑器的下拉框增加提示框

### ISSUE THREAD

**Issue by idllllll** [wangeditor-team/wangEditor-v5#334]
## 功能描述

鼠标放在悬浮编辑器的下拉框的条目上时，出现提示框，提示内容为条目内容（因为下拉框内容过长时，会被横向滚动条遮挡）

## 提炼几个功能点

- 下拉框增加提示框

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
没看懂，截个图详细说明一下吧。

**Comment by idllllll** [comment]
![image](https://user-images.githubusercontent.com/88028100/148153079-76548c51-2ab9-4dca-9513-d9cb77eb4ee3.png)

**Comment by idllllll** [comment]
鼠标放在下拉条目上时，出现提示框
![image](https://user-images.githubusercontent.com/88028100/148153850-e46b2a3b-a203-46c2-938d-4d328b37ad78.png)

**Comment by wangfupeng1988** [comment]
这里不会加提示了，太麻烦了。加一个 `title` 吧

![image](https://user-images.githubusercontent.com/9583120/148182863-fdb204ba-e0fa-4fce-a269-4321c181d057.png)

如果你依然觉得体验不好，那可以自行修改一下这个 DOM 的宽度，自己用 css 改就行。
