### ISSUE TITLE
editor.dangerouslyInsertHtml 解析会丢失color

### ISSUE THREAD

**Issue by f-jm** [wangeditor-team/wangEditor-v5#337]
## bug 描述

使用editor.dangerouslyInsertHtml 赋值会丢失color, 如：
`editor.dangerouslyInsertHtml('<strong style="color:#f00;">wangeditor</strong>')`
## 你预期的样子是？

`<strong style="color:#f00;">wangeditor</strong>`

## 系统和浏览器及版本号

- 操作系统 win10-x64
- 浏览器和版本 Microsoft Edge

## wangEditor 版本
@wangeditor/editor 0.13.4
@wangeditor/editor-for-vue 5.1.8-5

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

`editor.dangerouslyInsertHtml('<strong style="color:#f00;">wangeditor</strong>')`

**Comment by wangfupeng1988** [comment]
这符合预期，`dangerouslyInsertHtml ` 就是低成本的解析 html 并插入，不会考虑所有样式。
否则就不会加 `dangerously` 这个词了

**Comment by f-jm** [comment]
> 这符合预期，`dangerouslyInsertHtml ` 就是低成本的解析 html 并插入，不会考虑所有样式。 否则就不会加 `dangerously` 这个词了

用v5的编辑器将文本加粗并设置颜色，保存后二次编辑不能正常显示，这也算符合预期的？

**Comment by wangfupeng1988** [comment]
二次编辑，现在不支持 html 格式，只支持 JSON 格式。（后面会支持 html 格式，还在设计中）

`dangerouslyInsertHtml` 不是用于二次编辑的，仅仅是用于插入一些第三方的 html  ，如粘贴。
