### ISSUE TITLE
文字长度接近 maxLength 时，insertNode 会 js 报错

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#340]
## bug 描述

如题。

好在只有 js 报错，不影响后续的使用。

## 你预期的样子是？

没有 js 报错

## 系统和浏览器及版本号

- Mac OS
- Chrome 96

## wangEditor 版本

v5

## demo 能否复现该 bug ？

不能
用这个测试页 http://106.12.198.214:8882/refactor-maxlength/examples/maxlength.html

## 最小成本的复现步骤

- 进入测试页 http://106.12.198.214:8882/refactor-maxlength/examples/maxlength.html 
- 输入 99 个字，字数要接近 maxLength（maxLength 是 100 ）
- 控制台执行 `editor.insertNode({type: 'paragraph', children: [{text: 'aaaa'}]})` ，即可看到 js 报错

**Comment by wangfupeng1988** [comment]
修复时，可能需要直接在 refactor-maxlength 分支修改，到时候提前跟我沟通

**Comment by 1247748612** [comment]
而且这个文字数量是算上了换行符号的，是符合预期的吗

**Comment by wangfupeng1988** [comment]
@1247748612 

你贴的 js 报错，看样子和我发现的一样。

文字数量已经去掉换行符了，多次回车不会增加文字数量

**Comment by 1247748612** [comment]
按照复现步骤报的错不是同一个

![image](https://user-images.githubusercontent.com/29533304/148185488-a9f0c050-d2d1-4fe5-8a2f-9813e6aab11b.png)

**Comment by wangfupeng1988** [comment]
@1247748612 又优化了一下，不会报错了。不过，对于插入或粘贴非纯文本，依然无法做到和 `<textarea>` 一样。先这样吧，否则复杂度太高了。

强制刷新 http://106.12.198.214:8882/refactor-maxlength/examples/maxlength.html 测试
