### ISSUE TITLE
##可以在编辑器中 @ 某人 吗？

### ISSUE THREAD

**Issue by DoggyYao** [wangeditor-team/wangEditor-v5#344]
## 可以在编辑器中@某个人吗？

【vue2 + ts + wangEditor】我这边准备做个论坛，用贵编辑器来作为发帖页面的编辑器，请问有@某个人的功能吗，没有的话是不是要自己写。。。辛苦解答下~

**Comment by wangfupeng1988** [comment]
目前没有，后面会逐步开发，不过需要时间。
现在只能自己去实现。

**Comment by DoggyYao** [comment]
> 目前没有，后面会逐步开发，不过需要时间。 现在只能自己去实现。

好的，谢谢
