### ISSUE TITLE
API 优化： 使用 getHtml 方法获取编辑器 html 字符串返回一些冗余的属性

### ISSUE THREAD

**Issue by echoLC** [wangeditor-team/wangEditor-v5#347]
## API 优化

在创建编辑器传入默认的 content 内容后，使用 `getHtml` 方法获取 html 字符串，返回的内容有一些冗余的属性。

例如：
```ts
const editor = createEditor({
    content: [
        { type: 'paragraph', children: [{ text: 'hello', bold: true }] },
        { type: 'image', children: [{ text: '' }], src: 'test.jpg' },
    ],
})

const html = editor.getHtml()
// 输出 <p><span><strong>hello</strong></span></p><img src="test.jpg" alt="" data-href="" style=""/>
```

## 你预期的样子是？

```ts
const html = editor.getHtml()
// 输出 <p><span><strong>hello</strong></span></p><img src="test.jpg" alt="" />
```

## 系统和浏览器及版本号

- macOS
- chrome 最新版

## wangEditor 版本

v0.13.6

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 创建编辑器，传入默认的带有图片类型的 content
- 调用 `editor.getHtml()` 方法，打印查看结果

**Comment by wangfupeng1988** [comment]
`data-href=""` 是图片的链接，`style` 是图片宽高。如果没有这些信息，就是空字符串。这里没啥影响，不用修复。
