### ISSUE TITLE
【vue2 + wangEditor4.7.11 + @wangeditor/editor0.13.6】 emotion中可以增加自定义的表情包吗？

### ISSUE THREAD

**Issue by DoggyYao** [wangeditor-team/wangEditor-v5#349]
如题。  我想在emotion中配置多组表情，["手势", "表情",  “自定义” ......]
wangEditor 3 中，使用  editor.customConfig.emotions 来增加自定义的表情，请问 wangEditor 4 和 wangEditor 5 中支持这种增加自定表情的方式吗？

我看官网中只写了通过 
editorConfig.MENU_CONF['emotion'] = {
    emotions: '😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉'.split(' ') // 数组
}
的方式增加表情。通过这种方式 怎么增加 多 组 表情?

**Comment by wangfupeng1988** [comment]
第一，先确定是哪个版本
第二，请按照 issue 模板来
