### ISSUE TITLE
从表格复制内容时，粘贴后是普通span文本而不是table

### ISSUE THREAD

**Issue by LiuYuLu** [wangeditor-team/wangEditor-v5#350]
## bug 描述

从表格复制内容时，粘贴后是普通span文本而不是table

## 你预期的样子是？

复制的表格内容转换成table编辑数据

## 系统和浏览器及版本号

- 操作系统 mac
- 浏览器和版本 chrome 97

## wangEditor 版本

0.13.6

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

https://element.eleme.cn/#/zh-CN/component/table 复制表格数据，然后粘贴

**Comment by wangfupeng1988** [comment]
这个目前还不支持，还在开发中

**Comment by wangfupeng1988** [comment]
http://106.12.198.214:8882/feature-parse-html/examples/simple-mode.html 这个测试页支持粘贴表格了，可以去试试。
有 bug 在这里回复即可。

**Comment by 6tJaCeF** [comment]
这个例子的源码可以看一下吗

**Comment by 6tJaCeF** [comment]
> 这个例子的源码可以看一下吗

我发现表格复制到https://www.wangeditor.com/demo/zh-CN/
然后中转再复制到react组件是可行的

**Comment by wangfupeng1988** [comment]
@6tJaCeF 该 issue 提交的功能这两天才刚刚发布，你需要升级最新的 npm 包，就可以具备和官网 demo 相同的功能。
