### ISSUE TITLE
【邀请大家测试】回显 html 功能（初始化内容支持 html 格式）

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#351]
## 背景

当前 V5 仅支持[传入 JSON 格式初始化内容](https://www.wangeditor.com/v5/guide/getting-started.html#content-%E5%88%9D%E5%A7%8B%E5%8C%96%E5%86%85%E5%AE%B9)，很多用户反应这样不友好。存在的问题：

- 服务端需要存储 JSON 和 html 两份内容，前者用于编辑回显，后者用于显示内容。增加了服务端存储负担，且内容是冗余的
- 无法从 V4 升级到 V5

我近期高优跟进，核心功能已经开发完，兴趣的朋友可以一起测试。遇到 bug 直接回复到下面即可。

## 本次改动

第一，支持通过 html 传入内容

```js
editor = E.createEditor({
    selector: '#editor-text-area',
    html: '<p>hello world</p>' // 传入 html ，而非 JSON content
})
```

第二，支持绝大部分 V4 的代码。除了：
- 对文本设置了复杂的组合样式，如同时加粗、设置颜色、字体等 —— 转换可能会异常
- todo 代办事项 —— V5 目前不支持 todo ，需等待继续开发

## 测试准备

测试页面 http://106.12.198.214:8882/feature-parse-html/examples/parse-html.html （每次打开都强制刷新一下）

注意：**页面中填入的 html 必须是 wangEditor （V4，V5）产出的 html** ，不可自定义 html （html 格式太灵活，不会全部支持）

- 获取 V4 的 html ：访问 [V4 测试页](http://106.12.198.214:8881/master/examples/)，编辑内容，然后控制台执行 `console.log(editor.txt.html())` 即可得到 html
- 获取 V5 的 html ：访问 [V5 demo](https://www.wangeditor.com/demo/zh-CN/) ，编辑内容，然后控制台执行 `console.log(editor.getHtml())` 即可得到 html

## 开始测试

第一，使用 V4 的各个功能（加粗、颜色、表格、连接、视频...等等，全部的）产出 html ，然后创建编辑器，都能成功创建并正确渲染内容。

第二，使用 V5 的各个功能（加粗、颜色、表格、连接、视频...等等，全部的）产出 html ，然后创建编辑器，都能成功创建并正确渲染内容。

## 提交 bug 和建议

有 bug 或建议直接回复评论即可。**但一定要写明详细的复现步骤**，多谢~

**Comment by wangfupeng1988** [comment]
另外，粘贴 html 功能也做了重构（删除了之前的 `insertDomElem` 改用现在的 parse-html 方法）需要重新测试。
测试具体参考之前 issue https://github.com/wangeditor-team/wangEditor-v5/issues/283

**Comment by wangfupeng1988** [comment]
单元测试已经写完，预计最晚下周发布

**Comment by a835100635** [comment]
1、
![image](https://user-images.githubusercontent.com/65208676/149764949-831dba31-c3ab-46dc-8112-eeb672ba8597.png)
复制含有链接内容复制粘贴至编辑器中，控制台报错,谷歌火狐Safari都是一样的
![image](https://user-images.githubusercontent.com/65208676/149764695-88a51a74-88f8-4a0d-8986-426179ce0d79.png)

2、
![image](https://user-images.githubusercontent.com/65208676/149765022-4c25a189-3842-4fa9-80df-fb0e46b6680d.png)
复制含有图片内容复制粘贴至编辑器中，并没有图片哦
![image](https://user-images.githubusercontent.com/65208676/149765067-b0311e3b-95c4-4093-9d1f-97760e1d80ed.png)

3、
![image](https://user-images.githubusercontent.com/65208676/149765246-c32b241b-7f52-40b7-accd-f30604c396d3.png)
复制标题链接 控制报错且没有粘贴上，谷歌火狐Safari都是一样的
![image](https://user-images.githubusercontent.com/65208676/149765202-a7d2dbf0-62cd-415f-8b04-51a8c5452cc8.png)

**Comment by a835100635** [comment]
原文链接：https://www.toutiao.com/a7054114739474956839/?log_from=1c9bd535e5976_1642418026014

**Comment by wangfupeng1988** [comment]
@a835100635 你提出的问题，第 1 3 已经修复，可再去测试一下。第 2 个符合预期，不用修复。

**Comment by cjx19961030** [comment]
想问一下vue3初始化怎么复制html呢？ @wangfupeng1988

**Comment by wangfupeng1988** [comment]
> 想问一下vue3初始化编译器的时候怎么赋值html呢？ @wangfupeng1988

@cjx19961030 这要等正式发布之后再支持，大约在下周。

**Comment by cjx19961030** [comment]
这样吗，然后我还发现我的旧数据导过来，以前的html内容的img会包在strong或者其他标签里面，就不显示出来了，这个问题后续会解决吗 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
> img会包在strong或者其他标签里面

这种非规范 html ，不会兼容。

**Comment by cjx19961030** [comment]
可是我现在发现img翻在div这种标签里面也不会显示呢,是否一定要放在p标签里面才会被解析吗？

**Comment by wangfupeng1988** [comment]
> 是否一定要放在p标签里面才会被解析吗？
目前是这样的。因为 wangEditor 产出的代码中，也没有 `<div>` 标签。

> img翻在div这种标签里面也不会显示呢
这个目前还不支持，未来可能会支持，但不确定时间。

**Comment by wangfupeng1988** [comment]
“回显 HTML”功能已经发布，可参考文档 https://www.wangeditor.com/v5/guide/getting-started.html#%E8%AE%BE%E7%BD%AE-html

但可继续测试，有问题继续在这里回复。

**Comment by czphappy** [comment]
谢谢，很给力

**Comment by comxza** [comment]
`<p><span id="topic" value="40">#测试信息5#</span>。。。。。  <span id="member" value="1">@测试1234</span>  </p>`
不知是bug还是我的数据问题，我以上代码在回显demo中无法渲染出来  ，错误如下
![image](https://user-images.githubusercontent.com/21981010/150508913-6ff7f4e9-a2a7-4efc-b4d6-f175f09f0c1c.png)

**Comment by wangfupeng1988** [comment]
@comxza 这种结构目前无法识别，因为编辑器解析之后，其实是 4 个普通的 text 节点，如下图。而这 4 个普通的 text 节点应该合并为一个，不能分开。

![image](https://user-images.githubusercontent.com/9583120/150533636-742b0358-20de-4a45-8901-b9a7fe14dcff.png)

它应该是这样的 `<p>#测试信息5#。。。。。&nbsp;@测试1234&nbsp;</p>` 或者 `<p><span>#测试信息5#。。。。。&nbsp;@测试1234&nbsp;</span></p>`

文档中也重点写了一句：**html 内容必须是 wangEditor 生成的 HTML 格式，不可以自己随意写** https://www.wangeditor.com/v5/guide/getting-started.html#%E8%AE%BE%E7%BD%AE-html

**Comment by yixinagqingyuan** [comment]
详细测试v4,v5 产出html复制粘贴后，产出问题如下：
v4
缩进：期望正常显示-实际结果无法正常显示（有问题）
行高：期望正常显示-实际结果无法正常显示（有问题）
序列：期望正常显示-实际结果无法正常显示（有问题）
待办事项：期望正常显示-实际结果无法正常显示（有问题,暂不支持）
对齐：期望正常显示-实际结果无法正常显示（有问题）
表情：期望正常显示-实际结果无法正常显示（有问题）
视频：期望正常显示-实际结果无法正常显示（有问题）

v5
上标下标：期望正常显示-实际结果无法正常显示（有问题）

对应的用例详见请移步链接：https://note.youdao.com/s/p9S32LN 链接中包含了详细的测试用例

**Comment by wangfupeng1988** [comment]
> 上标下标：期望正常显示-实际结果无法正常显示（有问题）

@yixinagqingyuan 改功能已经修复（尚未发布），可通过 http://106.12.198.214:8882/main/examples/parse-html.html 测试

**Comment by yixinagqingyuan** [comment]
在v4编辑器中输入内容，使用shiif+回车 ，在使用backspace 撤回（之前使用的缩进、行高、表情都是此原因导致）

用例：
<p>asdf<br/></p>

**Comment by yixinagqingyuan** [comment]
在v4编辑器中输入内容，使用shiif+回车 ，在使用backspace 撤回（之前使用的缩进、行高、表情都是此原因导致）

用例：
<p>asdf<br/></p>

**Comment by yixinagqingyuan** [comment]
在v4编辑器中输入内容，使用shiif+回车 ，在使用backspace 撤回（之前使用的缩进、行高、表情都是此原因导致）

用例：
<p>asdf<br/></p>

**Comment by wangfupeng1988** [comment]
> 在v4编辑器中输入内容，使用shiif+回车 ，在使用backspace 撤回（之前使用的缩进、行高、表情都是此原因导致）
> 
> 用例：
> 
> ```
> <p>asdf<br/></p>
> ```

这个在最新版本中已经修复。
