### ISSUE TITLE
连续回车，光标超出了编辑区域的下边框，没有自动滚动

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#354]
## bug 描述

如题

## 你预期的样子是？

编辑区域随着光标自动滚动

## 系统和浏览器及版本号

-  Mac OS
- Chrome 96

## wangEditor 版本

V5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 官网 demo
- 连续回车 15 次，直到光标超出了编辑区域的下边框
- 编辑区域没有随着滚动

**Comment by wangfupeng1988** [comment]
修改这个问题要同时关注如下问题，别再复现
- https://github.com/wangeditor-team/wangEditor-v5/issues/2
- https://github.com/wangeditor-team/wangEditor-v5/issues/8
- https://github.com/wangeditor-team/wangEditor-v5/issues/282

**Comment by TGuoW** [comment]
问题是两个月前的这个 commit 中带来的 https://github.com/wangeditor-team/wangEditor-v5/commit/d2a87629cedc3533e268a31ca822f414082bf48d  ，相关issue是https://github.com/wangeditor-team/wangEditor-v5/issues/8

因此revert掉该代码即可解决，问题转换为如何修复 https://github.com/wangeditor-team/wangEditor-v5/issues/8。

控制滚动的逻辑是
![image](https://user-images.githubusercontent.com/26541572/154545066-a2998ac5-3995-4570-afd2-20047332f9c7.png)

排查发现之所以滚动到莫名其妙的位置，选中图片时 leafEl 是 `data-slate-spacer `，`data-slate-spacer`是绝对定位，与图片真正的位置相差较远，scroll 到了`data-slate-spacer`，所以位置错误。

因此在 `data-slate-spacer` 的父节点上设置 `position: relative` 即可。

slate 同样有 `data-slate-spacer`，但 slate 没有这个bug是因为 它的 `data-slate-spacer` 的父节点是 div，自带了 `position: relative`

**Comment by wangfupeng1988** [comment]
@TGuoW  http://106.12.198.214:8882/fix-edit-scroll/examples/default-mode.html 那你分支的 demo 进行测试，发现 https://github.com/wangeditor-team/wangEditor-v5/issues/2 还可以复现。

MacOS Chrome 98

**Comment by TGuoW** [comment]
https://github.com/wangeditor-team/wangEditor-v5/issues/2 已解决
