### ISSUE TITLE
Next.js引入wangEditor编译时会提示关于useLayoutEffect的警告

### ISSUE THREAD

**Issue by CheaterScript** [wangeditor-team/wangEditor-v5#357]
## bug 描述

Next.js引入wangEditor编译时会提示关于useLayoutEffect的警告，警告内容如下：

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```

## 你预期的样子是？

消除警告

## 系统和浏览器及版本号

- 操作系统：window10
- Next.js：v11.1.2

## wangEditor 版本

v0.13.6

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：使用Next.js脚手架构建项目
- 步骤二：新建页面引入wangEditor，引入代码如下：
```
import { createEditor, createToolbar } from '@wangeditor/editor'
```
- 步骤三：保存编译

**Comment by hahaaha** [comment]
暂时没有复现这种情况～
nextjs的使用可以参考下这里https://github.com/wangeditor-team/wangEditor-for-react
