### ISSUE TITLE
Shadow DOM 中的问题（CSS 样式 + 无法在 modal 中输入文字）

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#358]
## bug 描述

测试页 http://106.12.198.214:8882/main/examples/shadow-dom.html

### CSS 样式问题

样式问题有很多，需要继续详细排查，例如

第一，icon 和 placeholder 的 color 不对

![image](https://user-images.githubusercontent.com/9583120/149779097-106341ec-e873-4bff-965d-d4008aff9085.png)

第二，tooltip 没有背景色

![image](https://user-images.githubusercontent.com/9583120/149779186-966cf811-0da0-4727-8cd9-fac3d40765d5.png)

第三，下拉菜单没有背景色

![image](https://user-images.githubusercontent.com/9583120/149779263-69cf87d5-0856-4c92-bda0-c5451c958804.png)

![image](https://user-images.githubusercontent.com/9583120/149779303-4fb53723-c8eb-4f9a-a487-a83286c07cf7.png)

第四 ，编辑区域内部的元素，也没有样式，例如 blockquote table 等

![image](https://user-images.githubusercontent.com/9583120/149779470-5dec8943-54b8-42ab-8b58-8ca61d751f77.png)

![image](https://user-images.githubusercontent.com/9583120/149779560-0339bb68-a7ce-48f5-b53c-b0cbd143c5a0.png)

还有挺多的，需要继续排查

### modal 的 input 无法 focus 并输入

例如，插入链接，或者插入网络图片时，弹出的 modal 无法聚焦 input 也无法输入内容。一点击 modal 就会自动关闭

![image](https://user-images.githubusercontent.com/9583120/149779795-efd0ef13-fe7d-4f58-91f9-266fd8f66f09.png)

## 你预期的样子是？

- 样式没问题
- 能正常从 modal 中输入

## 系统和浏览器及版本号

- Mac OS
- Chrome 96

## wangEditor 版本

V5

## demo 能否复现该 bug ？

不能，看上文的测试页

## 最小成本的复现步骤

参考上文的 bug 描述

**Comment by wangfupeng1988** [comment]
CSS 样式问题已经在 https://github.com/wangeditor-team/wangEditor-v5/pull/359 中解决。

但第二个问题（无法在 modal 中输入文字）还在排查中

**Comment by clinfc** [comment]
modal 中无法聚焦原因很简单，Dom7 默认是在 document 中查找某个指定节点，然而在 shadowRoot 下的节点在通过 document 是无法被获取到的，因而引发了这个问题

以 insertLink 举例：
![image](https://user-images.githubusercontent.com/39868400/149877173-8eebdc8a-3960-4213-8f52-8ee883b8cd8d.png)
因为输入框聚焦失败，因而引发了后续的一点击 modal 框，modal 框就消失的异常状况

同样在 modal 框点击确认时，同样存在问题：
![image](https://user-images.githubusercontent.com/39868400/149877520-5852c200-7fb3-40bb-a932-8a3247d5c9df.png)

**Comment by wangfupeng1988** [comment]
> 因为输入框聚焦失败，因而引发了后续的一点击 modal 框，modal 框就消失的异常状况

@clinfc 在非 shadow dom 的示例中，即便是 modal input 失焦，点击 modal 空白处， modal 也不会消失。这一点是否考虑到？

**Comment by clinfc** [comment]
> >   输入框放大成功，模态就适用的情况，模态消失的异常
> 
> @clinfc在非阴影域的示例中，是模态输入失焦，不会点击模态空白处，模态也消失。这一点是否考虑？

无论在 shadowRoot 下还是在常规 document 中，只要 modal 中的输入框自动聚焦失败，都会引发上面的问题。然而只要自动聚焦成功，后续的输入、失焦再聚焦都不会有问题

**Comment by wangfupeng1988** [comment]
新发现的 bug ，点击“全屏”会报错。如下图：

![image](https://user-images.githubusercontent.com/9583120/149904354-6447b390-feb9-41ad-93f6-b3e0f71a1189.png)

**Comment by wangfupeng1988** [comment]
全屏问题已经解决
