### ISSUE TITLE
菜单栏中字体大小、文字颜色等需要下拉选项的功能无法正常关闭

### ISSUE THREAD

**Issue by czphappy** [wangeditor-team/wangEditor-v5#361]
## bug 描述

*菜单栏中字体大小、文字颜色等需要下拉选项的功能无法正常关闭比*

## 你预期的样子是？

*字体大小功能下拉弹出框选中后，选择其中一个选项，发现下拉框无法自动回缩，点击其他区域也无法正常回缩*
![image](https://user-images.githubusercontent.com/31985427/150292609-a6fd9e37-2962-4348-aa48-730ecbf20460.png)

## 系统和浏览器及版本号

- WIN10
- 谷歌浏览器 97.0.4692.71（正式版本） （64 位）

## wangEditor 版本

*V5.1.8-7*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请描述具体的复现步骤。

**Comment by czphappy** [comment]
这个问题是直接引用组件出现的，复现是直接显现的，出现如下bug问题

![image](https://user-images.githubusercontent.com/31985427/150293565-64d15db1-e7c6-4c4e-a72f-11a474be48f8.png)

**Comment by wangfupeng1988** [comment]
参考 https://juejin.cn/post/7027977252331585544 来做就可以了。
文末有源码。

**Comment by czphappy** [comment]
因为需要对菜单进行配置，所以我使用的是createEditor进行注册，使用源码示例不会出现上诉问题，但对菜单栏进行配置后，就会出现上诉的bug。

**Comment by wangfupeng1988** [comment]
源码中也可以修改菜单配置啊。

**Comment by liuqh0609** [comment]
麻烦提供一下，可以复现这个问题的完整代码，我来验证一下问题。

**Comment by czphappy** [comment]
不好意思，部门的代码不支持复制和截图，或者你们能提供手动配置的完整代码，（通过creat方式），我对比下

**Comment by liuqh0609** [comment]
你的意思是你引用了vue3的组件之后，又用了createEditor的方式去注册吗？

**Comment by czphappy** [comment]
对的。

**Comment by liuqh0609** [comment]
> 对的。

组件已经把基本功能都封装好了，方便用户开箱即用的，不需要你再去注册editor了。

你既然需要自己创建editor，那就不需要用当前这个vue组件了。可以直接使用`@wangeditor/editor` 包去实现自己的需求，具体使用方式请参考：[创建空白编辑器](https://www.wangeditor.com/v5/guide/getting-started.html#%E5%88%9B%E5%BB%BA%E7%A9%BA%E7%99%BD%E7%BC%96%E8%BE%91%E5%99%A8)

**Comment by liuqh0609** [comment]
如果没什么其他问题的话，这个issu就关闭了。

**Comment by czphappy** [comment]
按照你们的方案写得一个issue，你们看看问题
<template>
  <div id="toolbar-container"></div>
  <div id="editor-container"></div>
</template>

<script>
import {
  getEditor,
  removeEditor,
} from '@wangeditor/editor-for-vue'
import { createToolbar, createEditor } from '@wangeditor/editor'
import cloneDeep from 'lodash.clonedeep'
import '@wangeditor/editor/dist/css/style.css'
export default {
  name: 'richText',
  data: () => ({
    editor: '', //富文本的句柄
    editorId: 'wangeEditor-1',
    editorConfig: '',
    toolbarConfig: '',
  }),
  mounted () {
    this.editorConfig = {
    }
    this.editor = new createEditor({
      selector: '#editor-container',
      config: this.editorConfig,
      content: [],
      mode: 'default',
    })
    this.toolbarConfig = {
    }
    const toolbar = createToolbar({
      editor: this.editor,
      selector: '#toolbar-container',
      config: this.toolbarConfig,
      mode: 'default',
    })
  },
  methods: {
   
  },
  // 组件销毁时，及时销毁编辑器
  beforeUnmount() {
    const editor = getEditor(this.editorId)
    if (editor == null) return
    editor.destroy()
    removeEditor(this.editorId)
  },
}
</script>
