### ISSUE TITLE
@wangeditor/editor": "^0.14.1无法复制Intelli Jetbrains全家桶里的内容，如无法复制IDE、WebStorm里面的代码

### ISSUE THREAD

**Issue by withyanni** [wangeditor-team/wangEditor-v5#370]
## bug 描述

@wangeditor/editor": "^0.14.1无法复制Intelli Jetbrains全家桶里的内容，如无法复制IDE、WebStorm里面的代码

## 你预期的样子是？

可以正常带样式复制

## 系统和浏览器及版本号

win10 2004
chrome&edge最新最新版本

@wangeditor/editor": "^0.14.1

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 直接复制代码到官网demo即可，控制台报错
![image](https://user-images.githubusercontent.com/28222123/150793844-dae959bb-f632-4553-9d76-fea0907d0be6.png)

**Comment by wangfupeng1988** [comment]
提供一段 html 吧。

可以临时在 editor 增加一个 customPaste 配置，参考 https://www.wangeditor.com/v5/guide/editor-config.html#custompaste

然后打印事件中的 `event.clipboardData.getData('text/html')` ，贴到这里

**Comment by withyanni** [comment]
@wangfupeng1988 多谢！
我复制的是
![image](https://user-images.githubusercontent.com/28222123/150797099-bc781083-ad12-4dfb-ba59-1f0c349bacf1.png)
打印的结果是
<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body><pre style="background-color:#2b2b2b;color:#a9b7c6;font-family:'JetBrains Mono',monospace;font-size:13.5pt;"><span style="color:#9876aa;font-weight:bold;font-style:italic;">console</span>.<span style="color:#ffc66d;">log</span><span style="color:#9876aa;font-style:italic;">(</span>event.<span style="color:#9876aa;">clipboardData</span>.<span style="color:#ffc66d;">getData</span><span style="color:#9876aa;font-style:italic;">(</span><span style="color:#6a8759;">'text/html'</span><span style="color:#9876aa;font-style:italic;">))</span></pre></body></html>

**Comment by wangfupeng1988** [comment]
已修复，在这个测试页 http://106.12.198.214:8882/fix-parse-html-pre/examples/simple-mode.html

把你所有的场景都试一下吧
直接在控制台执行 `editor.dangerouslyInsertHtml('xxx')` 即可，这跟粘贴是一个逻辑。如下图：

![image](https://user-images.githubusercontent.com/9583120/150802605-6d2cb5a3-bd4f-4bf4-b4b0-0c3d0b218c0d.png)

**Comment by withyanni** [comment]
目前验证可以了，感谢 @wangfupeng1988

**Comment by withyanni** [comment]
请问发布节奏是？

**Comment by wangfupeng1988** [comment]
已发布了，更新最新版本即可

**Comment by withyanni** [comment]
感谢！
