### ISSUE TITLE
插入表情后输入文字，表情与文字重叠

### ISSUE THREAD

**Issue by YiQingWang** [wangeditor-team/wangEditor-v5#372]
## bug 描述

- 插入表情后输入文字，表情与文字重叠
- ![image](https://user-images.githubusercontent.com/16113453/150936747-531349a6-bab1-4d6d-a79a-99f3031ea259.png)

## 你预期的样子是？

- 不重叠

## 系统和浏览器及版本号

- macos 12.0.1
- chrome 97.0.4692.99

## wangEditor 版本

- v5 官网 demo 默认模式
- https://www.wangeditor.com/demo/zh-CN/

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：打开官网 demo ：https://www.wangeditor.com/demo/zh-CN/
- 步骤二：用工具栏加入一个表情
- 步骤三：输入一个字

**Comment by wangfupeng1988** [comment]
我也是 MacOS 12，Chrome 97 ，使用官网 demo 并没有复现。如下图：

![image](https://user-images.githubusercontent.com/9583120/150940014-a6bdccd9-cf4b-450f-90eb-1b0ded649b62.png)

**Comment by YiQingWang** [comment]
镜像外接显示器的问题，mac 本机显示器没事
