### ISSUE TITLE
第一个字符输入字母a会导致外部其它组件a标签被删除，显示成空白

### ISSUE THREAD

**Issue by withyanni** [wangeditor-team/wangEditor-v5#373]
## bug 描述

第一个字母输入英文会导致外部其它组件样式丢失，显示空表

## 你预期的样子是？

不影响其它组件

## 系统和浏览器及版本号

win10 2004
chrome&edge最新版本

## wangEditor 版本

"@wangeditor/editor": "^0.14.2"

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  只发现第一个输入的是字母，就会导致外部组件样式丢失，全显示成空白。
需要提供什么信息？

![image](https://user-images.githubusercontent.com/28222123/151091701-949aba4c-3370-4ce6-872c-3be946eaed90.png)

输入英文字母后
![image](https://user-images.githubusercontent.com/28222123/151091766-b4374e23-7acb-4846-a22c-11b8b345f30f.png)

F12只发现
![image](https://user-images.githubusercontent.com/28222123/151091807-09106c0d-fea2-4d72-8dc7-30ddc9c1efa3.png)

增加高度之后依然不行

**Comment by withyanni** [comment]
目前没找到最小复现条件，我能提供什么信息？

**Comment by withyanni** [comment]
貌似是a标签丢失

**Comment by wangfupeng1988** [comment]
跟高度没有关系。

不知道如何复现你的问题，你需要提供复现步骤。
最好在 https://codesandbox.io/ 中提供一个复现问题的项目，发链接过来

**Comment by withyanni** [comment]
https://codesandbox.io/s/bold-water-nid9o?file=/src/components/HelloWorld.vue
第一个字母输入英文，即可复现 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
@withyanni 既然是 vue的项目，推荐使用 vue 组件 https://www.wangeditor.com/v5/guide/for-frame.html#vue2 ，别自己 createEditor

**Comment by withyanni** [comment]
当前问题能帮忙看下有解决方式么，生产环境在用，替换需要点时间。

**Comment by wangfupeng1988** [comment]
codesanbox 我这刷新了好几次，一直报错。

![image](https://user-images.githubusercontent.com/9583120/151095887-5a37e97c-1304-479e-882c-afc43324d1a2.png)


你先试试 vue 组件有没有问题。

**Comment by withyanni** [comment]
我下午搭一个吧，我跑了一下刚才的在线demo，应该是只输入字母a，会导致a标签显示成空白

**Comment by withyanni** [comment]
可以复现，如果把这个注掉就不复现，第一个字母输入a必现 @wangfupeng1988 
https://codesandbox.io/s/nervous-shockley-0dv1s?file=/src/components/HelloWorld.vue

![image](https://user-images.githubusercontent.com/28222123/151117352-602e01e1-e192-4bff-b1b2-44fbec5e08d9.png)
