### ISSUE TITLE
菜单“uploadImage”有customBrowseAndUpload可配置自己实现选择图片、上传图片，并插入图片，是否菜单“insertImage”和菜单“insertVideo”也有类似的配置来自己实现插入图片和插入视频？

### ISSUE THREAD

**Issue by ChuangShiOS** [wangeditor-team/wangEditor-v5#374]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
之前就应记录了这个需求，后面会陆续做出来，需要一些时间。
