### ISSUE TITLE
能否提供一下用自定义扩展注册菜单ButtonMenu的React版本例子？文档上只有用TypeScript版本的例子

### ISSUE THREAD

**Issue by ChuangShiOS** [wangeditor-team/wangEditor-v5#375]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
在 React 中也是这样用，Vue 中也是这样用，参考文档即可。
文档中的 typescript 你也可以用 javascript 写，都一样的。

**Comment by ChuangShiOS** [comment]
import { IButtonMenu } from '@wangeditor/core'
import { Boot } from '@wangeditor/editor'

// 定义菜单 class
class MyButtonMenu implements IButtonMenu {
    // 菜单配置，参考“引用”菜单源码
}

// 定义菜单配置
export const menuConf = {
  key: 'menu1', // menu key ，唯一。注册之后，可配置到工具栏
  factory() {
    return new MyButtonMenu()
  },
}

// 注册到 wangEditor
Boot.registerMenu(menuConf)


好像react没有implements这种写法的吧？ 还是我不会写？ 不好意思哈

**Comment by wangfupeng1988** [comment]
@ChuangShiOS `implements` 是 ts 语法，如果你用 js ，可以把 `implements IButtonMenu` 删掉，直接定义 class 即可。
