### ISSUE TITLE
表格里的表头输入文字后，敲回车调试里报错

### ISSUE THREAD

**Issue by yunweibang** [wangeditor-team/wangEditor-v5#376]
## bug 描述

*表格里的表头输入文字后，敲回车调试里报错*

## 系统和浏览器及版本号

- macos
- chrome

## wangEditor 版本

V5版本

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 创建表单
- 步骤二
- 表头输入文字
- 
- 步骤三
- 表头文字输入回车

chrome调试就报错：
index.22708c4f.js:25 Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by wangfupeng1988** [comment]
不知道你说的`创建表单`是什么操作。
你可以说一下，在官网 demo 如何复现？

**Comment by yunweibang** [comment]
创建表单 就是 插入N行N列的表格

**Comment by wangfupeng1988** [comment]
如下图，没有复现问题。你需要详细描述复现步骤 @yunweibang 

![image](https://user-images.githubusercontent.com/9583120/151724662-3284fcba-db1f-4caf-9f6e-dc75861e76ae.png)
