### ISSUE TITLE
设置文字为H1后，清除格式不能清除H1格式，只能清除颜色的格式

### ISSUE THREAD

**Issue by yunweibang** [wangeditor-team/wangEditor-v5#377]
## bug 描述

*清除格式不能用*

## 你预期的样子是？

*清除格式*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN

## 最小成本的复现步骤

- 步骤一
- 设置文字为H1后，清除格式不能清除H1格式，只能清除颜色的格式

![image](https://user-images.githubusercontent.com/5226861/151706540-673f5703-fd80-49a8-8fb0-0b0160b85ee7.png)

**Comment by wangfupeng1988** [comment]
是的，只能清楚文字格式，header 无法清除
