### ISSUE TITLE
建议增加查看和编辑源码功能

### ISSUE THREAD

**Issue by luker2013** [wangeditor-team/wangEditor-v5#385]
还是非常有用的一个功能，有时候复制来的内容可能出现样式不可直接使用的情况，如果有源码，编辑者可以自行修改不可见的样式代码。

**Comment by wangfupeng1988** [comment]
v5 不会默认集成“修改源码”功能。

如果确实需要，你可以自己扩展“源码”菜单，目前的能力是支持的。
