### ISSUE TITLE
从后台接口获取到的数据怎么设置到编辑器中，之前的版本是通过editor.txt.html("html内容来设置")，v5版本有没有类似的setHtml方法

### ISSUE THREAD

**Issue by milletGuo** [wangeditor-team/wangEditor-v5#386]
## 问题描述

*我之前使用v4版本将数据存储在后台，现在改用v5版本，从后台返回的数据不能设置到编辑器里面*

## wangeditor/editor: 0.15.0,
      wangeditor/editor-for-vue: 0.6.13,

*想通过类似于setHtml的方法设置内容*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：创建编辑器
- 步骤二：从后台接口拿到数据
- 步骤三：将数据设置到编辑器中(这一步不能实现)

**Comment by wangfupeng1988** [comment]
参考文档 https://www.wangeditor.com/v5/guide/content.html#%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AE%B9

vue2 组件的设置内容 https://www.wangeditor.com/v5/guide/for-frame.html#%E5%BC%82%E6%AD%A5%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AE%B9
