### ISSUE TITLE
modal hoverbar 定位问题

### ISSUE THREAD

**Issue by NgChiKin** [wangeditor-team/wangEditor-v5#387]
## bug 描述
内容很长然后输入框是滚动的，内容的最后是 一种有 modal hoverbar 的元素，并且这个元素 被手动删去了自动生成的空格
例如 a 标签原本是这样的：`<p>&nbsp;<a>link</a>&nbsp;<p>`
但我就是不这样，删掉默认生成的后面的一个空格变成： `<p>&nbsp;<a>link</a><p>`

场景: 从服务端获取内容, 通过 dangerouslyInsertHtml  插入内容, 会默认聚焦到最后，
不要跟编辑器 所在 页面有任何影响编辑器失焦的交互, 这时候这个  modal hoverbar 定位就会计算错误，远远超出了输入框
整个页面都被拉长了， 就因为这个  modal hoverbar, 如果跟编辑器失焦, 那个 modal hoverbar 就不会显示啦

## 你预期的样子是？
判断是否显示？不在编辑器可视区域内就不显示？
或者 [#354 ](https://github.com/wangeditor-team/wangEditor-v5/issues/354) 自动滚动到聚焦的地方?
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/57823909/153692037-08f6d109-99a5-4770-9a12-f6796c85d332.png">

## 系统和浏览器及版本号

- 操作系统  window & mac
- 浏览器和版本 chrome 最新版本

## wangEditor 版本

@wangeditor/editor 0.14.0，试了最新版 0.15.1也会， 那么就是所有都会这样

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤
写了 demo： https://codesandbox.io/s/festive-feynman-hkycy
进入demo， 加载完毕, 编辑器时聚焦状态
点击 dangerouslyInsertHtml 按钮，然后不要跟编辑器 所在 页面有任何影响编辑器失焦的交互, 就会出现
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/57823909/153692161-2eadc009-9f02-4714-afe0-af0d0d869c7e.png">

**Comment by wangfupeng1988** [comment]
根据你提供的 demo ，没有发现异常。MacOS + chrome98

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/9583120/153693858-ba0d7d29-f0e6-4dfb-89ab-4b0dde39bed7.png">

**Comment by NgChiKin** [comment]
在滚动的时候不要去 滚动编辑器

**Comment by wangfupeng1988** [comment]
@NgChiKin 哦，看到了。作为 bug 处理。

**Comment by wangfupeng1988** [comment]
@NgChiKin 在 `<Editor>` 组件样式中加 `overflow: 'hidden'` 即可解决

```
        <Editor
          defaultConfig={editorConfig}
          defaultContent={defaultContent}
          // defaultHtml={defaultHtml}
          mode="default"
          style={{ height: "500px", overflow: 'hidden' }}
```

**Comment by NgChiKin** [comment]
@wangfupeng1988 这个 Editor 的 属性类型定义
style 应该是 React.CSSProperties | undefined，现在是 object， 写的时候都没有提示

**Comment by hahaaha** [comment]
@NgChiKin 最新版本react组件（v0.6.23）style类型的问题已经修复了
