### ISSUE TITLE
V5 在对Table进行操作时，编辑器未对colSpan进行计算，包含合并单元格的行，会自动增加多余的列

### ISSUE THREAD

**Issue by 13408381254** [wangeditor-team/wangEditor-v5#388]
## bug 描述

V5 在对Table进行操作时，编辑器未对colSpan进行计算，包含合并单元格的行，会自动增加多余的列
如：
![image](https://user-images.githubusercontent.com/33079106/153850702-f99aeafc-e60d-45ce-8745-6b8f0cb5ed24.png)

## 你预期的样子是？

不应有最右侧的列

**Comment by wangfupeng1988** [comment]
目前不支持合并单元格。
改功能在排队支持中。

**Comment by 13408381254** [comment]
好，谢谢
