### ISSUE TITLE
插入代码块后，设置 html 出错

### ISSUE THREAD

**Issue by leiwuhen1715** [wangeditor-team/wangEditor-v5#392]
## 问题描述

通过编辑器插入代码块，重新去设置会出错

## wangEditor 版本

wangEditor 新版本 V5

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 在编辑器插入代码块，提交保存
- 步骤二
- 二次设置html出错，设置json没有问题

**Comment by wangfupeng1988** [comment]
出错的 html 具体内容是什么？

**Comment by leiwuhen1715** [comment]
<p>超文本标记语言（英语：HyperText Markup Language，简称：HTML）是一种用于创建网页的标准标记语言。</p><p>您可以使用 HTML 来建立自己的 WEB 站点，HTML 运行在浏览器上，由浏览器来解析。</p><p>在本教程中，您将学习如何使用 HTML 来创建站点。</p><p>HTML 很容易学习！相信您能很快学会它！</p><p>HTML 实例</p><p>本教程包含了数百个 HTML 实例。</p><p>使用本站的编辑器，您可以轻松实现在线修改 HTML，并查看实例运行结果。</p><p>注意：对于中文网页需要使用 <meta charset="utf-8"> 声明编码，否则会出现乱码。有些浏览器(如 360 浏览器)会设置 GBK 为默认编码，则你需要设置为 <meta charset="gbk">。</p><p>HTML 实例</p><pre><code class="language-html"><!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
</head>
<body>
    <h1>我的第一个标题</h1>
    <p>我的第一个段落。</p>
</body>
</html></code></pre><p>尝试一下</p><p>点击“尝试一下”按钮查看在线实例</p><div data-w-e-type="todo"><input type="checkbox" disabled checked>123456</div><div data-w-e-type="todo"><input type="checkbox" disabled checked>65465546</div><div data-w-e-type="todo"><input type="checkbox" disabled checked>456456</div><p>实例解析</p><ol><li><span style="color: rgb(56, 158, 13);"><!DOCTYPE html> 声明为 HTML5 文档</span></li><li><span style="color: rgb(56, 158, 13);"><html> 元素是 HTML 页面的根元素</span></li><li><span style="color: rgb(56, 158, 13);"><head> 元素包含了文档的元（meta）数据，如 定义网页编码格式为 utf-8。</span></li><li><span style="color: rgb(56, 158, 13);"><title> 元素描述了文档的标题</span></li><li><span style="color: rgb(56, 158, 13);"><body> 元素包含了可见的页面内容</span></li><li><span style="color: rgb(56, 158, 13);"><h1> 元素定义一个大标题</span></li><li><span style="color: rgb(56, 158, 13);"><p> 元素定义一个段落</span></li></ol><p>注：在浏览器的页面上使用键盘上的 F12 按键开启调试模式，就可以看到组成标签。</p>

**Comment by leiwuhen1715** [comment]
`<p>超文本标记语言（英语：HyperText Markup Language，简称：HTML）是一种用于创建网页的标准标记语言。</p><p>您可以使用 HTML 来建立自己的 WEB 站点，HTML 运行在浏览器上，由浏览器来解析。</p><p>在本教程中，您将学习如何使用 HTML 来创建站点。</p><p>HTML 很容易学习！相信您能很快学会它！</p><p>HTML 实例</p><p>本教程包含了数百个 HTML 实例。</p><p>使用本站的编辑器，您可以轻松实现在线修改 HTML，并查看实例运行结果。</p><p>注意：对于中文网页需要使用 <meta charset="utf-8"> 声明编码，否则会出现乱码。有些浏览器(如 360 浏览器)会设置 GBK 为默认编码，则你需要设置为 <meta charset="gbk">。</p><p>HTML 实例</p><pre><code class="language-html"><!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
</head>
<body>
    <h1>我的第一个标题</h1>
    <p>我的第一个段落。</p>
</body>
</html></code></pre><p>尝试一下</p><p>点击“尝试一下”按钮查看在线实例</p><div data-w-e-type="todo"><input type="checkbox" disabled checked>123456</div><div data-w-e-type="todo"><input type="checkbox" disabled checked>65465546</div><div data-w-e-type="todo"><input type="checkbox" disabled checked>456456</div><p>实例解析</p><ol><li><span style="color: rgb(56, 158, 13);"><!DOCTYPE html> 声明为 HTML5 文档</span></li><li><span style="color: rgb(56, 158, 13);"><html> 元素是 HTML 页面的根元素</span></li><li><span style="color: rgb(56, 158, 13);"><head> 元素包含了文档的元（meta）数据，如 定义网页编码格式为 utf-8。</span></li><li><span style="color: rgb(56, 158, 13);"><title> 元素描述了文档的标题</span></li><li><span style="color: rgb(56, 158, 13);"><body> 元素包含了可见的页面内容</span></li><li><span style="color: rgb(56, 158, 13);"><h1> 元素定义一个大标题</span></li><li><span style="color: rgb(56, 158, 13);"><p> 元素定义一个段落</span></li></ol><p>注：在浏览器的页面上使用键盘上的 F12 按键开启调试模式，就可以看到组成标签。</p>`

**Comment by leiwuhen1715** [comment]
<xml><p>超文本标记语言（英语：HyperText Markup Language，简称：HTML）是一种用于创建网页的标准标记语言。</p><p>您可以使用 HTML 来建立自己的 WEB 站点，HTML 运行在浏览器上，由浏览器来解析。</p><p>在本教程中，您将学习如何使用 HTML 来创建站点。</p><p>HTML 很容易学习！相信您能很快学会它！</p><p>HTML 实例</p><p>本教程包含了数百个 HTML 实例。</p><p>使用本站的编辑器，您可以轻松实现在线修改 HTML，并查看实例运行结果。</p><p>注意：对于中文网页需要使用 <meta charset="utf-8"> 声明编码，否则会出现乱码。有些浏览器(如 360 浏览器)会设置 GBK 为默认编码，则你需要设置为 <meta charset="gbk">。</p><p>HTML 实例</p><pre><code class="language-html"><!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
</head>
<body>
    <h1>我的第一个标题</h1>
    <p>我的第一个段落。</p>
</body>
</html></code></pre><p>尝试一下</p><p>点击“尝试一下”按钮查看在线实例</p><div data-w-e-type="todo"><input type="checkbox" disabled checked>123456</div><div data-w-e-type="todo"><input type="checkbox" disabled checked>65465546</div><div data-w-e-type="todo"><input type="checkbox" disabled checked>456456</div><p>实例解析</p><ol><li><span style="color: rgb(56, 158, 13);"><!DOCTYPE html> 声明为 HTML5 文档</span></li><li><span style="color: rgb(56, 158, 13);"><html> 元素是 HTML 页面的根元素</span></li><li><span style="color: rgb(56, 158, 13);"><head> 元素包含了文档的元（meta）数据，如 定义网页编码格式为 utf-8。</span></li><li><span style="color: rgb(56, 158, 13);"><title> 元素描述了文档的标题</span></li><li><span style="color: rgb(56, 158, 13);"><body> 元素包含了可见的页面内容</span></li><li><span style="color: rgb(56, 158, 13);"><h1> 元素定义一个大标题</span></li><li><span style="color: rgb(56, 158, 13);"><p> 元素定义一个段落</span></li></ol><p>注：在浏览器的页面上使用键盘上的 F12 按键开启调试模式，就可以看到组成标签。</p>
</xml>

**Comment by leiwuhen1715** [comment]
<xmp><pre><code class="language-php">$a = 1;
$b = 2;
echo $a=$b;</code></pre><p><br></p><xmp>

**Comment by wangfupeng1988** [comment]
@leiwuhen1715 你这段 html 是从哪里得到的？是否是 wangEditor（v4 或者 v5）产出的？

**Comment by leiwuhen1715** [comment]
没有那个xmp标签，是v5插入《插入代码块》产生的

**Comment by wangfupeng1988** [comment]
> 没有那个xmp标签，是v5插入《插入代码块》产生的

用这个 demo http://106.12.198.214:8882/main/examples/parse-html.html
我试着可正常转换 ，如下图

<img width="498" alt="image" src="https://user-images.githubusercontent.com/9583120/154935117-b7fadf53-1a31-4a33-9e68-c669af098035.png">

**Comment by wangfupeng1988** [comment]
如果你那边还不成功，可以给一个完整的 demo ，让我们复现问题。

**Comment by leiwuhen1715** [comment]
好的
