### ISSUE TITLE
【文档勘误】自定义扩展新功能——styleToHtml 第 15 行出现未知字符 $(elemHtml) 的 $

### ISSUE THREAD

**Issue by YiQingWang** [wangeditor-team/wangEditor-v5#394]
## 问题描述

自定义扩展新功能——styleToHtml 第 15 行出现未知字符 $(elemHtml) 的 $
https://www.wangeditor.com/v5/guide/development.html#styletohtml

## wangEditor 版本

v5
 "@wangeditor/editor": "^0.14.2"
## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是
https://www.wangeditor.com/v5/guide/development.html#styletohtml

## 最小成本的复现步骤

[（请告诉我们，如何**最快的**复现该问题？）

文档地址：https://www.wangeditor.com/v5/guide/development.html#styletohtml
参考源码：https://github.com/wangeditor-team/wangEditor-v5/blob/main/packages/basic-modules/src/modules/font-size-family/style-to-html.ts
源码中可以看到 $ 相关的引用，但是在 npm package dist 目录相同文件下没有找到 export default $ 
此 $ 最终在源码中找到来源于 'dom7' ，建议文档中添加引用声明

**Comment by wangfupeng1988** [comment]
感谢指正，我今晚就修改
