### ISSUE TITLE
如需要其他语言，如何提取所有需要翻译的词句去翻译

### ISSUE THREAD

**Issue by huangxinbo** [wangeditor-team/wangEditor-v5#395]
## wangEditor 版本

*wangEditor-v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/v5](https://www.wangeditor.com/v5/guide/i18n.html#%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80) ）

*是*

**Comment by wangfupeng1988** [comment]
就参考 https://www.wangeditor.com/v5/guide/i18n.html#%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80 这个文档即可。

- 添加新的语言，文档里有
- 切换语言，文档里有
- 使用语言，就像文档里 `t('header.title')` 这样使用即可

PS：在项目源码中搜索所有的 `locale/en.ts` 文件，即可找到所有的语言词汇。

**Comment by wangfupeng1988** [comment]
新增了 `i18nGetResources ` 获取所有语言词汇
https://www.wangeditor.com/v5/guide/i18n.html
