### ISSUE TITLE
【优化】点击 menu 触发由 mousedown 改为 click

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor-v5#396]
如题，点击 menu 触发由 mousedown 改为 click

## 注意1

当前使用 mousedown 并且 preventDefault ，不会导致编辑器 blur 。

而要使用 click ，默认会导致编辑器 blur 。需要考虑如何如何避免 blur ，或者每次都使用 `editor.restoreSelection()` 恢复选区（要结合使用体验选择）

## 注意2

当前点击 ModalMenu （如插入图片、编辑图片）会弹出 modal ，此时再点击 body 或编辑区域 ，modal 会自动隐藏 —— 这个功能是用 click 实现的。

而当“点击 menu 触发由 mousedown 改为 click” 之后，这里的 click 会不会和上述 click 有冲突？需要测试确定。

## 注意3

要考虑三种类型的菜单
- ButtonMenu ，如加粗
- SelectMenu ，如设置标题、设置字号等 —— 特别是 select 下拉框的自动隐藏
- ModalMenu ，如插入链接、编辑链接、插入图片 —— 特别是 modal 的自动隐藏

**Comment by wangfupeng1988** [comment]
测试地址 http://106.12.198.214:8882/refactor-mousedown-to-click/examples/default-mode.html
功能参照 http://106.12.198.214:8882/main/examples/default-mode.html

浏览器兼容性
- chrome
- safari （仅 MacOS）
- firefox
- edge
- QQ 浏览器（仅 windows）

主要测试
- ButtonMenu 菜单，如加粗等常规菜单
- SelectMenu 菜单，如设置标题、设置字号等 —— 特别是 select 下拉框显示之后，能否点击其他地方隐藏
- DropPanelMenu 菜单，如设置颜色、表情、插入表格等 —— 特别 dropPanel 显示之后，能否点击其他地方而隐藏
- ModalMenu 菜单，如插入链接、编辑链接、插入图片等 —— 特别是 modal 显示之后，能否点击其他地方被隐藏

测试完成之后，在语雀[这里](https://wangeditor.yuque.com/wangeditor/gtoqwe)新建一个测试记录，然后链接发到这个 issue 。

**Comment by a835100635** [comment]
测试记录：https://wangeditor.yuque.com/wangeditor/gtoqwe/fi1lf6#hoGz

**Comment by wangfupeng1988** [comment]
@a835100635 记录的问题里，我看到有“其他问题”。
如果是和该 issue 无关的问题（参考的网页，也有这个问题），可以去提交新 issue ，然后在测试记录中删掉。

如果有关，那就继续在测试记录里放着。

**Comment by clinfc** [comment]
测试记录：https://wangeditor.yuque.com/wangeditor/gtoqwe/os8afp#0yXn
