### ISSUE TITLE
windows QQ浏览器 使用 customPaste 出错

### ISSUE THREAD

**Issue by NgChiKin** [wangeditor-team/wangEditor-v5#397]
## bug 描述
windows QQ浏览器 使用 customPaste 出错, 自定义 粘贴 返回 false, 自己再使用 inserText 插入内容
会插入 两次内容,并且控制台报错 Cannot resolve a Slate point from DOM point

## 你预期的样子是？
只 插入一次内容

## 系统和浏览器及版本号

- windows10
- qq 浏览器 最新版本 10.8.4559.400

## wangEditor 版本

最新版本也会.

## demo 能否复现该 bug ？

不能

demo 没有自定义粘贴

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤
demo: https://codesandbox.io/s/summer-fast-xqq7u5

随意 复制点文本 粘贴便能复现

**Comment by wangfupeng1988** [comment]
复现了。
可以加一行 `e.preventDefault()` 试试

<img width="555" alt="image" src="https://user-images.githubusercontent.com/9583120/154913546-4c3f789b-2757-424a-8899-9c63fbfb3d3c.png">

**Comment by NgChiKin** [comment]
加这行能解决。刚看了一下代码，试了 阻止编辑器  paste 的默认事件也能解决。
自定义粘贴返回 false，在不支持  beforeInput 的浏览器，还是去执行了 paste。
是这个问题吗，不支持return 出去了， 没有 阻止到。然后 handleOnPaste 在执行完 customPaste 就 return 了，也没有执行到 
preventDefault。
<img width="920" alt="image" src="https://user-images.githubusercontent.com/57823909/154917481-18128a6a-6002-48f8-a1bc-28c662b70cf8.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/57823909/154917983-4e314982-c333-4369-a4c4-b4833bf9d127.png">

**Comment by wangfupeng1988** [comment]
是的。我回头补充到文档里。
