### ISSUE TITLE
加载之前编辑的富文本，打开之后显示为空

### ISSUE THREAD

**Issue by withyanni** [wangeditor-team/wangEditor-v5#398]
## bug 描述
加载这段文本不能显示，打开之后显示为空。另外还有个问题就是，有序列表无序列表，不显示圆圈和数字编号。
*请输入内容……*
```
<ol><p>1、xx：&nbsp;（1）xx（&nbsp;）：</p><p>1），xxx&nbsp;&nbsp;&nbsp;xx&nbsp;xx%</p><p>2），xx&nbsp;&nbsp;&nbsp;xx&nbsp;&nbsp;x%</p><p>2、xx：</p><p>xx</p><p>3、x：&nbsp;xx</p></ol>
```
外面v-html显示
![image](https://user-images.githubusercontent.com/28222123/155051461-a04c9fa0-f857-43fb-9c96-b8350b469b62.png)
打开之后显示，列表也没显示圆圈或者数字编号
![image](https://user-images.githubusercontent.com/28222123/155051446-30da25d7-62b2-4bab-9079-0ef5bf7ecc10.png)

## 你预期的样子是？
打开之后能正常显示
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 edge最新版本

## wangEditor 版本
"@wangeditor/editor": "^0.14.3",
"@wangeditor/editor-for-vue": "^0.6.13",
*请输入内容……*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by withyanni** [comment]
```
<ol><p>111</p></ol>
```
这个也不行，不知道是什么问题了，，，只有这个不行

**Comment by withyanni** [comment]
ol标签去掉可以显示

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/guide/content.html#%E8%AE%BE%E7%BD%AE-html

如下图：
<img width="860" alt="image" src="https://user-images.githubusercontent.com/9583120/155052878-dff47a02-57e4-4b8a-9ed6-9d8959f96343.png">
