### ISSUE TITLE
无序列表和有序列表，不显示前面的圆圈和数字编号

### ISSUE THREAD

**Issue by withyanni** [wangeditor-team/wangEditor-v5#399]
## bug 描述
```
<ul><li>111</li></ul>
```

![image](https://user-images.githubusercontent.com/28222123/155053893-004585f2-4b91-464e-8797-ec4c4d03c3e4.png)

## 你预期的样子是？

![image](https://user-images.githubusercontent.com/28222123/155053954-7ec1e54f-71f7-4453-a052-0245ca0f12da.png)

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 edge最新版

## wangEditor 版本

"@wangeditor/editor": "^0.14.3",
    "@wangeditor/editor-for-vue": "^0.6.13",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by withyanni** [comment]
目前不知道和啥冲突了，我能提供什么数据？

**Comment by wangfupeng1988** [comment]
你看在这里能复现吗？http://106.12.198.214:8882/main/examples/parse-html.html

如下图：

<img width="523" alt="image" src="https://user-images.githubusercontent.com/9583120/155056690-0c7ede91-256f-4312-a84a-23425267a0f6.png">

**Comment by withyanni** [comment]
在上面网站不可以复现，本地F12显示如下，我还能提供哪些信息？
![image](https://user-images.githubusercontent.com/28222123/155057828-b257a8ce-fb84-4a23-a7f9-acc3b54bb0f1.png)

**Comment by wangfupeng1988** [comment]
看下你浏览器中 `<ul>` 和 `<li>` 的样式，我怀疑你本地的 CSS 把 `list-style` 给覆盖了。

**Comment by withyanni** [comment]
确实被覆盖了，公司自己的组件库影响了。。。感谢！
![image](https://user-images.githubusercontent.com/28222123/155058803-90ab7338-9233-4b6b-9171-9d475fae8a7c.png)

**Comment by wangfupeng1988** [comment]
客气

**Comment by windf17** [comment]
我用antd也遇到了这个问题，那应该怎么解决呢？

**Comment by wangfupeng1988** [comment]
> 我用antd也遇到了这个问题，那应该怎么解决呢？

自己追加 css 样式即可。
