### ISSUE TITLE
粘贴图片不会进入customUpload上传流程吗？

### ISSUE THREAD

**Issue by sandywk** [wangeditor-team/wangEditor-v5#401]
## 问题描述

复制或截图后粘贴，编辑器会显示图片，但是没有上传处理。

## wangEditor 版本

editor@0.15.8

## 是否查阅了文档 ？

是的 查看了文档 https://www.wangeditor.com/v5/guide/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD

## 最小成本的复现步骤

在图片菜单配置了 customUpload 上传到自己服务器的逻辑，并且通过工具栏选择图片上传是正常的。
但是发现编辑器里粘贴图片不会走 customUpload 逻辑，设置 base64LimitSize 后只会生成base64图片。
我需要粘贴到编辑器的图片也走 customUpload 上传到服务器怎么设置呢？

**Comment by wangfupeng1988** [comment]
可以的。你用这个 demo 试试 http://106.12.198.214:8882/main/examples/upload-image.html

微信或 qq 截图，然后粘贴，会上传到服务器。

**Comment by sandywk** [comment]
@wangfupeng1988 这个demo没有用到customUpload自定义上传，我用的是自定义上传。

**Comment by sandywk** [comment]
搞定了 去除 base64LimitSize 这个参数就会走上传流程
