### ISSUE TITLE
关于vue中想要自定义按钮的问题

### ISSUE THREAD

**Issue by Heart-lin** [wangeditor-team/wangEditor-v5#402]
我想实现一个自定义按钮功能,但是文档得做法是.ts文件,使用demo之后直接报错了,有没有.js的demo我学习一下!!!!

**Comment by wangfupeng1988** [comment]
ts 去掉类型，就是 js 代码了。或者直接用工具转换 https://blog.csdn.net/weixin_46752896/article/details/105269878

**Comment by Heart-lin** [comment]
感谢你的帮助&nbsp;&nbsp;
另外&nbsp; 我这边比较菜&nbsp; &nbsp;能多问你几个问题吗?
1.关于svg 文件引入的问题 上图是我引入的svg&nbsp; 用来创建自定义按钮
var QUOTE_SVG = require("@/icons/svg/pdf.svg");

this.iconSvg = QUOTE_SVG;

但是图标没有显示
2.这边文档说全局只能注册一次，不要重复注册,那对于vue来说&nbsp; 是在哪里注册呢&nbsp; &nbsp; main函数里面注册吗,


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor-v5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月24日(星期四) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor-v5] 关于vue中想要自定义按钮的问题 (Issue #402)





 
ts 去掉类型，就是 js 代码了。或者直接用工具转换 https://blog.csdn.net/weixin_46752896/article/details/105269878
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
全局注册一次，参考这里

https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithMention.vue

https://github.com/wangfupeng1988/vue3-wangeditor-demo/blob/main/src/components/MyEditorExtend.vue
