### ISSUE TITLE
dangerouslyInsertHtml  方法 插入 getHtml 导出的 文本，多个空格只显示了 一个空格

### ISSUE THREAD

**Issue by NgChiKin** [wangeditor-team/wangEditor-v5#405]
## bug 描述

dangerouslyInsertHtml  方法 插入 getHtml 导出的 文本，多个空格只显示了 一个空格

文档说的完美还不够完美
<img width="949" alt="image" src="https://user-images.githubusercontent.com/57823909/155493001-393f1abb-6c73-4781-9ca1-7d04d97b83af.png">

## 你预期的样子是？

编辑怎么显示，导出文本，再插入就怎么显示

## 系统和浏览器及版本号

最新

## wangEditor 版本

最新

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤
https://codesandbox.io/s/summer-fast-xqq7u5

点击按钮，对比编辑器内容 与 插入的文本

**Comment by wangfupeng1988** [comment]
这个问题正好今天在解决

**Comment by wangfupeng1988** [comment]
v5 最新版本已经解决该问题
https://www.npmjs.com/package/@wangeditor/editor
