### ISSUE TITLE
have any plan to support mobile device？

### ISSUE THREAD

**Issue by llcat** [wangeditor-team/wangEditor-v5#407]
## 功能描述
最近打算换掉`quill`使用功能更全面的`wangEditor V5`， 但是看到文档说暂时还不支持移动端, 但我们的文章需要在移动端做查看, 请问您近期是否有计划做移动端的兼容呢? 或者对于简单的展示需求, 我换用`wangEditor`后, 能快速的兼容移动端的建议吗?

*请输入内容……*

## 提炼几个功能点

- 功能1
兼容移动端展示富文本内容

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
> 我们的文章需要在移动端做查看 + 于简单的展示需求

可以详细说明你的需求点，我再分析是否可以全面支持。

PS：如果仅仅是展示和查看，那肯定是没问题的。但要想在移动端使用 wangEditor 编辑文章，那近期不好实现。

**Comment by llcat** [comment]
> > 我们的文章需要在移动端做查看 + 于简单的展示需求
> 
> 可以详细说明你的需求点，我再分析是否可以全面支持。
> 
> PS：如果仅仅是展示和查看，那肯定是没问题的。但要想在移动端使用 wangEditor 编辑文章，那近期不好实现。

- 移动端不需要编辑, 仅查看, 文章内容一般比较简单
- 文章包含的内容有:
  1. 简单文本(标题, 正文...)
  2. 图片
  3. 链接 (可能是一个附件的下载地址)

我准备近期尝试一下, 感谢您的回复!
