### ISSUE TITLE
希望只读模式下，也能使用全屏按钮

### ISSUE THREAD

**Issue by zhm84** [wangeditor-team/wangEditor-v5#408]
## 功能描述

希望只读模式下，也能使用全屏按钮

## 提炼几个功能点

1. 将编辑器的disable和全屏按钮的disable分开，使得开发者可以自定义全屏按钮的状态，这样只读模式下，也能全屏阅读编辑器内容，优化了用户体验。

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

不清楚其他编辑器

**Comment by wangfupeng1988** [comment]
受理。排队开发

**Comment by wangfupeng1988** [comment]
最新版本修复了 https://www.npmjs.com/package/@wangeditor/editor

这个 demo 可以看到效果 http://106.12.198.214:8882/main/examples/default-mode.html

**Comment by zhm84** [comment]
感谢！
