### ISSUE TITLE
Next.js构建报错

### ISSUE THREAD

**Issue by CheaterScript** [wangeditor-team/wangEditor-v5#409]
## bug 描述

Next.js引入wangEditor执行Build会报错

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: document is not defined
    at new StyleSheet (D:\WebProjects\wang_editor\node_modules\styled-jsx\dist\index\index.js:136:35)
    at new StyleSheetRegistry (D:\WebProjects\wang_editor\node_modules\styled-jsx\dist\index\index.js:491:33)
    at Object.createStyleRegistry (D:\WebProjects\wang_editor\node_modules\styled-jsx\dist\index\index.js:667:10)
    at renderToHTML (D:\WebProjects\wang_editor\node_modules\next\dist\server\render.js:364:46)
    at async D:\WebProjects\wang_editor\node_modules\next\dist\export\worker.js:269:36
    at async Span.traceAsyncFn (D:\WebProjects\wang_editor\node_modules\next\dist\trace\trace.js:75:20)
```

## 你预期的样子是？

构建成功

## 系统和浏览器及版本号

- 操作系统：window10
- Next.js：v12.1.0

## wangEditor 版本

v0.15.10

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一：使用Next.js脚手架构建项目
- 步骤二：新建页面引入wangEditor，引入代码如下：
```
import { createEditor, createToolbar } from '@wangeditor/editor'
```
- 步骤三：保存执行yarn build。

**Comment by wangfupeng1988** [comment]
看下这里 https://github.com/wangeditor-team/wangEditor-for-react#%E5%9C%A8nextjs%E4%B8%8B%E4%BD%BF%E7%94%A8

**Comment by CheaterScript** [comment]
> 看下这里 https://github.com/wangeditor-team/wangEditor-for-react#%E5%9C%A8nextjs%E4%B8%8B%E4%BD%BF%E7%94%A8

是按照这个引导出现的bug，我给的复现步骤有问题吗？如果是我有地方弄错了，请解释一下这个bug是为什么，感谢。

**Comment by CheaterScript** [comment]
我已经验证过我给的复现步骤，什么多余的代码都不用，直接import就会出现该Bug，我也在该项目代码里搜过没有使用过styled-jsx，不知道为什么会出现这个错误。

**Comment by hahaaha** [comment]
`import '@wangeditor/editor/dist/css/style.css'`这个有引入么

**Comment by CheaterScript** [comment]
> `import '@wangeditor/editor/dist/css/style.css'`这个有引入么 另外你是直接使用 '@wangeditor/editor'的么还是使用的 '@wangeditor/editor-for-react' 我这边使用 链接里的案例跑了下是没什么问题的😂

没有引入样式文件，链接里的样例没问题，用next.js官方脚手架创建的项目会出现这个Bug，请确认一下next.js的版本是否是v12.1.0。

**Comment by CheaterScript** [comment]
最小复现的代码如下：/pages/index.jsx：
```javascript
import { createEditor } from '@wangeditor/editor'

export default function Home() {
  return (
    <div>
    </div>
  )
}

```

**Comment by CheaterScript** [comment]
> 这个还是你next的用法有问题 你可以看下样例中引入的方式 另外可以看下这个 https://www.jianshu.com/p/0b3541ab4a94

已解决，感谢！
