### ISSUE TITLE
使用vue2组件，编辑器内容为空时，输入中文会报错

### ISSUE THREAD

**Issue by 754304364** [wangeditor-team/wangEditor-v5#413]
## bug 描述

*使用vue2组件，编辑器内容为空时，输入中文会报错，并且输入的内容会被清除
`Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node`

## 你预期的样子是？

*能正常输入

## 系统和浏览器及版本号

- 操作系统 macOS11.2.3
- 浏览器和版本 Chorme

## wangEditor 版本
@wangeditor/editor-for-vue  0.6.14
@wangeditor/editor 0.15.2

## 最小成本的复现步骤
- 编辑器的 autoFocus设为false，让编辑器失去焦点，并且编辑器内容为空
- 输入中文，控制台会报错

**Comment by wangfupeng1988** [comment]
我没有复现你的问题。

-------

升级一下最新的版本。

然后用这个 demo 看看能否复现 https://github.com/wangfupeng1988/vue2-wangeditor-demo （如复现了，告诉我们修改了哪些代码，或者提交一个 pr ）

或者，你直接在 codesandbox 上做一个能复现的 demo 。
