### ISSUE TITLE
在富文本添加表格并编辑完成并保存，在新页面解析完数据后表格的边框消失

### ISSUE THREAD

**Issue by noob001rightnow** [wangeditor-team/wangEditor-v5#414]
## bug 描述

*在富文本添加表格并编辑完成并保存，在新页面解析完数据后表格的边框消失*

## 你预期的样子是？

*在富文本添加表格并编辑完成并保存，在新页面解析完数据后表格的仍然有边框，或者想知道原因*

## 系统和浏览器及版本号
- 操作系统
- win10
- 浏览器和版本
chrome 版本84.0.4147.135(正式版本)(64位)

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 在富文本里插入表格并编辑
- 步骤二
- 保存到后台
- 步骤三
- 新页面调取数据解析并渲染

**Comment by wangfupeng1988** [comment]
看文档 https://www.wangeditor.com/v5/guide/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
