### ISSUE TITLE
单元测试报错

### ISSUE THREAD

**Issue by zhm84** [wangeditor-team/wangEditor-v5#417]
## bug 描述

引入wangeditor V5，单元测试报错
错误提示：Your browser does not have secure random generator. If you don't need unpredictable IDs, you can use nanoid/non-secure.
报错位置：
at ../../node_modules/@wangeditor/editor/dist/index.js:12453:13
at Object.<anonymous>.info (../../node_modules/@wangeditor/editor/dist/index.js:2:66)

## 你预期的样子是？

无报错，单测正常运行

## 系统和浏览器及版本号

- 操作系统：Windows 10
- 浏览器和版本：chrome 98

## wangEditor 版本

0.15.11

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：组件引入wangeditor V5
- 步骤二:  测试文件引入jest进行单元测试
- 步骤三：运行单测

**Comment by echoLC** [comment]
因为 `jest` 的环境里面没有包含 `nanoid ` 需要的 `crypto` 方法，所以目前的解决一个方案是在 jest 的 `setup` 文件中添加全局的实现：

```ts
import nodeCrypto from 'crypto'

global.crypto = {
  getRandomValues: function (buffer: any) {
    return nodeCrypto.randomFillSync(buffer)
  },
}
```

reference: [[Nanoid can't be used in react-native](https://stackoverflow.com/questions/66852077/nanoid-cant-be-used-in-react-native)](https://stackoverflow.com/questions/66852077/nanoid-cant-be-used-in-react-native)。

目前我们的仓库里面也是通过这种方式来解决这个问题的。具体可以参看 `jest` 的配置和 [setup.ts](https://github.com/wangeditor-team/wangEditor-v5/blob/main/tests/setup/index.ts)。

**Comment by zhm84** [comment]
感谢！
