### ISSUE TITLE
excludeKeys 无法影响 default 模式下鼠标工具栏、无法影响下拉集合，header4、header5 对工具栏&鼠标工具栏 headerSelect 均无效

### ISSUE THREAD

**Issue by YiQingWang** [wangeditor-team/wangEditor-v5#418]
## bug 描述

<img width="1014" alt="企业微信截图_90787f25-ea5c-4b22-90de-29ae1e85e6e3" src="https://user-images.githubusercontent.com/16113453/156097376-49ca81b7-af40-4e96-89bf-87bd70dcb50a.png">

1. excludeKeys 无法影响 default 模式下鼠标工具栏
2. excludeKeys 无法影响 default 模式下的下拉集合
3. header4、header5 对工具栏&鼠标工具栏 headerSelect 均无效

## 你预期的样子是？

- [ ] 1. excludeKeys 排除的工具在 default 模式下鼠标工具栏内也去除
- [ ] 2. 下拉集合内没有任何内容不要生成这个下拉按钮
- [ ] 3. header4、header5 对工具栏&鼠标工具栏 headerSelect 应该生效。

另外

- [ ] - 是否现存 / 能否 开个口子在 simple 模式下配置启用鼠标工具栏，这样就可以规避上述问题，既能排除掉不需要的工具按钮，也能使用鼠标工具栏，但是鼠标工具栏存在的 excludeKeys 不管用仍然是个问题。
- [ ] - 是否现存 / 能否 提供鼠标工具栏的配置项

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

`"@wangeditor/editor": "^0.15.9",
"@wangeditor/editor-for-react": "^0.6.23",`

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- `const toolbarConfig = {
        insertKeys: {
            index: 12, // 插入的位置，基于当前的 toolbarKeys
            keys: [],
        },
        excludeKeys: [
            'blockquote', // 引用
            'italic', // 斜体
            'through', // 删除线
            'code', // 代码行
            'sub', // 下标
            'sup', // 上标
            'clearStyle', // 清除格式
            'color', // 字体颜色
            'bgColor', // 背景色
            'fontSize', // 字号
            'fontFamily', // 字体
            'indent', // 缩进
            'delIndent', // 取消缩进
            'justifyLeft', // 左对齐
            'justifyRight', // 右对齐
            'justifyCenter', // 居中对齐
            'justifyJustify', // 两端对齐
            'header4', // 标题4
            'header5', // 标题5
            'divider', // 分割行
            'emotion', // 表情
            'todo', // 待办
        ],
    };`
- `<Toolbar
                        editor={editor}
                        defaultConfig={toolbarConfig}
                        mode="default"
                        style={{ borderBottom: '1px solid #ccc' }}
                    />
                    <Editor
                        defaultConfig={editorConfig}
                        defaultContent={defaultContent}
                        // defaultHtml={defaultHtml}
                        mode="default"
                        style={{ minHeight: '400px' }}
                    />`
- 步骤三

**Comment by wangfupeng1988** [comment]
获取工具栏默认配置 https://www.wangeditor.com/v5/guide/toolbar-config.html#getconfig ，其中 `toolbar.getConfig().toolbarKeys` 就是当前菜单栏的配置。你想去掉哪个，写上 key 即可。

你说的“下拉集合”也在这个配置里。

**Comment by YiQingWang** [comment]
> 获取工具栏默认配置 https://www.wangeditor.com/v5/guide/toolbar-config.html#getconfig ，其中 `toolbar.getConfig().toolbarKeys` 就是当前菜单栏的配置。你想去掉哪个，写上 key 即可。
> 
> 你说的“下拉集合”也在这个配置里。
> 
> <img alt="image" width="713" src="https://user-images.githubusercontent.com/9583120/156105301-d722c8c3-d072-45fa-9b85-2760c16b8c69.png">

首先我参考的就是文档这部分内容，这里提到的 toolbar.getConfig().toolbarKeys 在 react 下并没有这个实例，采用 editor.getAllMenuKeys() 方法 只能获取到如下内容：
<img width="534" alt="WX20220301-124130@2x" src="https://user-images.githubusercontent.com/16113453/156106102-0b451982-20c3-4323-9837-df3ba9916798.png">
其中不存在这些“下拉集合” group，如何在 react 下取到 toolbar 实例？

其次以上答复只能解决部分问题，请注意看截图，通过配置 excludeKeys 顶部工具栏已经不存在**删除线**这个功能，但是在鼠标弹出工具栏中仍然有删除线，这个怎么解决？

**Comment by wangfupeng1988** [comment]
如何在 react 下取到 toolbar 实例？ —— 看我刚才贴的文档。

鼠标弹出工具栏中仍然有删除线 —— 看这里 https://www.wangeditor.com/v5/guide/editor-config.html#hoverbarkeys

**Comment by YiQingWang** [comment]
> 

look good

**Comment by YiQingWang** [comment]
> 如何在 react 下取到 toolbar 实例？ —— 看我刚才贴的文档。
> 
> 鼠标弹出工具栏中仍然有删除线 —— 看这里 https://www.wangeditor.com/v5/guide/editor-config.html#hoverbarkeys
感谢答复~
小小的建议：感觉 hoverbarKeys 这部分内容在https://www.wangeditor.com/v5/guide/toolbar-config.html#toolbarkeys 工具栏配置这里做一句话的关联比较好，个人觉得这两个 bar 是同类功能，在 #toolbarkeys 没有找到相关内容就可能会以为没有。

**Comment by wangfupeng1988** [comment]
我见过有写编辑器，只要 hoverbar ，不要 toolbar 。
