### ISSUE TITLE
CDN引入@wangEditor/core时如何从window对象上获取到构造函数

### ISSUE THREAD

**Issue by ZiuChen** [wangeditor-team/wangEditor-v5#421]
## 问题描述

通过`CDN`引入`wangEditor`，从v4升级到v5，自定义注册菜单时需要引入`@wangeditor/core`中的`IButtonMenu`类，但是我查阅了文档与现有的Demo，仍然不太清楚如何通过`CDN`引入此功能。

```js
// npm
import { IButtonMenu } from '@wangeditor/core'
import { Boot } from '@wangeditor/editor'

// cdn
const { IButtonMenu } = window // any hint ?
const { Boot } = window.wangEditor;
```

## wangEditor 版本

`wangEditor/editor@0.15.11`
`wangEditor/core@0.14.12`

## 是否查阅了文档 ？

是，未找到相关Demo

## 最小成本的复现步骤

`none`

**Comment by wangfupeng1988** [comment]
用 CDN ，你直接把 `IButtonMenu` 相关的删掉即可。`IButtonMenu`  是用于 TS 的 interface

**Comment by ZiuChen** [comment]
谢谢，问题已经解决了！
