### ISSUE TITLE
word文档中复制图片加文字粘贴到编辑器，图片会显示不出来

### ISSUE THREAD

**Issue by noob001rightnow** [wangeditor-team/wangEditor-v5#424]
## bug 描述

*在word中复制图片和文字到富文本中图片不显示，部分表格的样式也会丢失*

## 你预期的样子是？

*图片能显示，表格也有表格样式*

## 系统和浏览器及版本号

- 操作系统
- w10
- 浏览器和版本
- chrome 84.0

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
在word里添加多张表格，挨个复制 或者一起复制
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前还不能完全支持 word 所有格式。后续再开发
