### ISSUE TITLE
全选中文本后进行中文输入，placeholder错误显示

### ISSUE THREAD

**Issue by nlyrthiia** [wangeditor-team/wangEditor-v5#426]
## bug 描述

如题

## 你预期的样子是？

全选文本后，中文输入时placeholder不显示

## 系统和浏览器及版本号

- Mac OS
- Microsoft edge 96.0.1054.43 

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 官网demo
- 切换中文输入法，ctr + c全选中文本，进行中文输入
- placeholder会出现在用户输入的文本上

**Comment by nlyrthiia** [comment]
复现过程第二步： ctr + c 改为 ctr + a

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor-v5/pull/425 已经合并，等待下次发布

**Comment by wangfupeng1988** [comment]
> #425 已经合并，等待下次发布

这个 pr 有问题，已 revert。再重新转为 bug 处理吧。

**Comment by wangfupeng1988** [comment]
最新版本已经解决
