### ISSUE TITLE
style标签编译问题

### ISSUE THREAD

**Issue by andylcl** [wangeditor-team/wangEditor-v5#427]
## 问题描述

*通过向编辑器插入一段style设置编辑器页边距，但是style标签在getHtml时似乎没有被编译*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 用过dangerouslyInsertHtml插入一行style设置padding, Padding可生效
- 步骤二 调用editor.getHtml(), 此时style标签不会被编译

**Comment by wangfupeng1988** [comment]
目前不支持这种方式。

建议你作为一个新需求（而非 bug），新提交一个 issue ，我们再考虑下怎么实现。
