### ISSUE TITLE
工具栏中无序列表和有序列表这2个按钮状态不会随着内容重置而复位！

### ISSUE THREAD

**Issue by windf17** [wangeditor-team/wangEditor-v5#430]
## bug 描述

工具栏中无序列表和有序列表这2个按钮状态不会随着内容重置而复位！

## 你预期的样子是？
我使用react，在左侧目录选择内容后，右侧WangEditor编辑区注入相应的内容。
            editor.select([])  // 全选编辑器中的内容
            editor.deleteFragment()  // 删除编辑器中被选中内容
            editor.dangerouslyInsertHtml(init.desc)  // 插入html内容
但是我发现之前的编辑区当前内容状态是“无序列表”或“有序列表”时，注入新的内容也会变成“无序列表”或“有序列表状态”。
请检查代码，在清空编辑器中的内容注入新的内容之前，工具栏中的“无序列表”和“有序列表”状态是否重置？

![Peek 2022-03-07 12-17](https://user-images.githubusercontent.com/65995709/156967160-47716071-e577-4258-ae91-bd9c8449f416.gif)

请认真看gif，仔细看无序列表按钮的状态！

**Comment by wangfupeng1988** [comment]
这样试试

```ts
import { SlateTransforms } from '@wangeditor/editor'

editor.select([]) // 全选编辑器中的内容
editor.deleteFragment() // 删除编辑器中被选中内容
SlateTransforms.setNodes(editor, { type: 'paragraph' }, [0]) // 设置为 p 标签
editor.dangerouslyInsertHtml(init.desc) // 插入html内容
```

**Comment by windf17** [comment]
![2022-03-07_17-11](https://user-images.githubusercontent.com/65995709/157001445-ea18c340-0afb-447f-806e-5d9fb026772c.png)

另外我感觉是治标不治本的方法，这样子编辑一次内容都会在外面套一对p标签……
另外我在react里面用还报错了！

**Comment by wangfupeng1988** [comment]
改一下这一行，第三个参数

```js
SlateTransforms.setNodes(editor, { type: 'paragraph' }, { mode: 'highest' });
```

**Comment by windf17** [comment]
> 改一下这一行，第三个参数
> 
> ```js
> SlateTransforms.setNodes(editor, { type: 'paragraph' }, { mode: 'highest' });
> ```

收到，确实可以了！没有出现按钮状态不复位的状况，也没有插入重复的标签。
但是作为完美主义者，我看到代码飘红，但始终没找到应该引入什么类型会更好一些。
请看截图，代码工作虽然正常，但是ide提示飘红。
![Uploading 2022-03-07_18-41.png…]()

**Comment by wangfupeng1988** [comment]
代码飘红参考这里
- https://github.com/wangeditor-team/wangEditor-plugin-md/blob/main/src/module/plugin.ts#L78
- https://github.com/wangeditor-team/wangEditor-plugin-md/blob/main/src/extends.d.ts

相关文档 https://www.wangeditor.com/v5/guide/for-ts.html
