### ISSUE TITLE
@wangeditor/core的版本接口现在是否已基本稳定

### ISSUE THREAD

**Issue by chuck-ma** [wangeditor-team/wangEditor-v5#431]
## 问题描述

自定义组件的时候发现，@wangeditor/core的 0.12和 0.14版本之间，API差异还挺多的，担心现在投入实际生产，会面临较多不确定性。
其正式投产有大概时间节点吗？

## wangEditor 版本
wangEditor v5
@wangeditor/core的 0.14
## 是否查阅了文档 ？

是

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
前段时间做过一点改动，那会儿我正在开发[第三方插件](https://www.wangeditor.com/v5/guide/plugins.html)，发现有不足就补充了一下。
近期没动过，现在已经稳定了。预计 4 月就会正式发布 v5 。
