### ISSUE TITLE
数据库里的内容是纯文本，通过dangerouslyInsertHtml提交到编辑器时程序会崩溃！

### ISSUE THREAD

**Issue by windf17** [wangeditor-team/wangEditor-v5#432]
## bug 描述

我在react中使用：
    useEffect(() => {
        formRef.current?.setFieldsValue(init)  // 初始化表单默认值
        if (editor) {
            editor.select([])  // 全选编辑器中的内容
            editor.deleteFragment()  // 删除编辑器中被选中内容
            editor.dangerouslyInsertHtml(init.desc)  // 插入html内容
        }
    }, [init])
init中提交的内容就是字符串"1"、"2"，结果程序崩溃了：
![2022-03-07_18-41](https://user-images.githubusercontent.com/65995709/157015969-03846c0b-e920-47be-9a82-bcb2a542a631.png)

**Comment by wangfupeng1988** [comment]
显示纯文本参考这里 https://www.wangeditor.com/v5/guide/content.html#%E8%AE%BE%E7%BD%AE-text

**Comment by windf17** [comment]
这样兼容性不好啊，我注入编辑器的内容还得判断是html或者是text？
能不能更方便使用，把insertHtml改进一下？O(∩_∩)O谢谢

> 显示纯文本参考这里 https://www.wangeditor.com/v5/guide/content.html#%E8%AE%BE%E7%BD%AE-text

**Comment by wangfupeng1988** [comment]
API 名字是 insertHtml （不是 insertHtmlOrText ），语义很明确，所以不做兼容。

**Comment by windf17** [comment]
好吧，收到，谢谢！
这个问题可以关闭，我能接收！
