### ISSUE TITLE
insertNode传入json数据的问题

### ISSUE THREAD

**Issue by qiang9420d** [wangeditor-team/wangEditor-v5#434]
## 问题描述

insertNode传入json数据的时候，style不生效

## wangEditor 版本

*V5

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*
是

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/22925262/157604174-cff01ec4-e12c-45ae-a357-cc3ba210e968.png)

**Comment by wangfupeng1988** [comment]
insertNode 不是插入 vnode ，具体看这里 https://www.wangeditor.com/v5/guide/node-define.html
