### ISSUE TITLE
选字体 字号等 下拉选项 都不会自动关闭 需要重新再点一次

### ISSUE THREAD

**Issue by itshizhan** [wangeditor-team/wangEditor-v5#435]
## 问题描述

1. 菜单不能自己隐藏

![image](https://user-images.githubusercontent.com/36762970/157843957-7f249f62-6d48-4893-8075-7384454cbd8e.png)

2. 上传图片报错
选择链接 网络图片 报错： Cannot find textarea instance by editor

## 是否查阅了文档 ？

是

## 官网能否复现该 bug ？
不能

## 最小成本的复现步骤

- 步骤一  创建一个vue3的项目
- 步骤二  安装element-plus 和 @wangeditor/editor
- 步骤三  将编辑器放置在 dialog 中

##  最小Reproduction link
https://gitee.com/itshizhan/wangeditor-v5-demo

##  相关
#277

**Comment by itshizhan** [comment]
可以打开了，忘了gitee默认是私有仓库

**Comment by clinfc** [comment]
经过对你提供示例代码的分析，定位为响应式 API 对编辑器实例的 污染/串改 所造成，如果你希望在组件其它地方能拿取到编辑器实例，请使用 `shallowRef`/`shallowReactive` 存储编辑器实例，而不是使用 `ref`/`reactive` 存储编辑器实例。
![QQ截图20220311212303](https://user-images.githubusercontent.com/39868400/157875376-f27c1492-6a99-4ee7-a836-4a326b3e8fef.png)

**Comment by wangfupeng1988** [comment]
@itshizhan Vue3 中可以直接用 Vue 组件，不用自己 createEditor https://www.wangeditor.com/v5/guide/for-frame.html#vue3

**Comment by clinfc** [comment]
> 

这是我个人写的 vue3 组件库，不过没有官方背景，是一个第三方组件库，希望能对你有帮助。[wangeditor5-for-vue3](https://clinfc.github.io/wangeditor5-for-vue3/)

**Comment by clinfc** [comment]
> @clinfc感谢感谢，之前引用会污染编辑器的数据，没有重给编辑器本身也有影响。
> 
> @wangf1988我当时尝试了官方的@wangedit/editor-vue@ nextue组件。好像有编辑过一些问题。目前的情况是，创建同一张照片 的数量，需要使用中的动态，并且所有动态创建的编辑器展示在同一个对话框中。
> 
> 我，对话框显示的时候，获取数据，重新创建实例，并且可以显示当前的编辑器和当前编辑器之间的类似获取数据之间的关系，可以做到动态的数据同步。
> 
> 官方的文档中有提到：
> 
> ```
> const isEditorShow = ref(false)
> 
> // 模拟 ajax 异步获取内容
> setTimeout(() => {
>     // defaultContent (JSON 格式) 和 defaultHtml (HTML 格式) ，二选一
>     defaultHtml.value = 'ajax&nbsp;异步获取的内容'
>     defaultContent.value =  [
>         { type: "paragraph", children: [{ text: "ajax 异步获取的内容" }] },
>     ]
> 
>     isEditorShow.value = true
> }, 1000)
> ```
> 
> 这里内容虽然看起来相似的渲染了编辑器，但是我还是觉得同一个吧。
> 
> 我再研究下。 谢谢

这是我个人写的 vue3 组件库，不过没有官方背景，是一个第三方组件库，希望能对你有帮助。[wangeditor5-for-vue3](https://clinfc.github.io/wangeditor5-for-vue3/)
