### ISSUE TITLE
我尝试将WangEditor封装成编辑器和阅读器双功能，遇到了关于readOnly状态的问题！

### ISSUE THREAD

**Issue by windf17** [wangeditor-team/wangEditor-v5#436]
## bug 描述
我尝试在编辑时使用wangEditor编辑通知内容，没有问题。但是给用户阅读通知时使用readOnly状态遇到了问题，内容不刷新。

## 你预期的样子是？

我在editorConfig里配置了readOnly为true时，用户确实不可以编辑内容，但是我代码里也不能插入内容。
editor.dangerouslyInsertHtml(context)  // 插入html内容
上述代码执行毫无效果，编辑器内容始终为空！

然后我尝试使用editor.enable()，再插入内容，再editor.disable()，结果通知内容始终是第一条的数据，其他的数据进不了编辑器。
请观察下面2个gif文件的表现：

![注释enable](https://user-images.githubusercontent.com/65995709/157849504-af6ad82f-4d81-4b69-9f9d-97c239574bb8.gif)
![取消注释enable](https://user-images.githubusercontent.com/65995709/157849529-3fb36fa7-2859-4f24-ac28-865e36183fde.gif)

**Comment by wangfupeng1988** [comment]
readOnly 状态下无法输入，也无法执行 API ，这个是符合预期的。

**Comment by wangfupeng1988** [comment]
> 然后我尝试使用editor.enable()，再插入内容，再editor.disable()，结果通知内容始终是第一条的数据，其他的数据进不了编辑器。

看你代码截图，感觉后面更新时，都没有走到 `editor.enable()` 这段代码中，只有第一次走到了。

**Comment by wangfupeng1988** [comment]
我试了一下，这样没问题。

```js
  // 点击一个按钮，插入一个段落。连续点击，能连续插入
  document.getElementById('btn1').addEventListener('click', () => {
    editor.enable()
    if (editor.selection === null) {
      editor.select([0, 0])
    }
    editor.dangerouslyInsertHtml(`<p>${Date.now().toString()}</p><p><br></p>`)
    editor.disable()
  })
```

**Comment by windf17** [comment]
![测试插入数据代码是否执行](https://user-images.githubusercontent.com/65995709/157858790-9acbc131-7ad7-46c7-9ab4-621b0f829478.gif)

**Comment by wangfupeng1988** [comment]
参考我刚才的代码，加这几行试试。

```js
    if (editor.selection === null) {
      editor.select([0, 0])
    }
```

**Comment by windf17** [comment]
搞定了，我发现在enable之前执行select和delete、insert都没用！
多谢提示！！非常感谢！！

**Comment by windf17** [comment]
useEffect(() => {
        if (editor) {
            if (readOnly) {
                editor.enable()
                editor.select([])  // 全选编辑器中的内容
                editor.deleteFragment()  // 删除编辑器中被选中内容
                SlateTransforms.setNodes(editor, newNode, { mode: "highest" })  // 配置编辑器使用新节点，节点模式设为最高级
                const context = init.id === 0 ? "<p></p>" : init.desc
                editor.dangerouslyInsertHtml(context) // 插入html内容
                editor.disable()
            } else {
                editor.select([])  // 全选编辑器中的内容
                editor.deleteFragment()  // 删除编辑器中被选中内容
                SlateTransforms.setNodes(editor, newNode, { mode: "highest" })  // 配置编辑器使用新节点，节点模式设为最高级
                editor!.dangerouslyInsertHtml(init.id === 0 ? "<p></p>" : init.desc)  // 插入html内容
            }
        }
    }, [init])

**Comment by windf17** [comment]
问题已经解决，谢谢！
