### ISSUE TITLE
使用npm按照文档所说引用第三方插件wangEditor-plugin-formula 时报错

### ISSUE THREAD

**Issue by wanzi-2** [wangeditor-team/wangEditor-v5#440]
## bug 描述

使用npm按照文档所说引用第三方插件wangEditor-plugin-formula 时报错

Failed to compile with 2 errors 

These dependencies were not found:

* WangEditorCore in ./node_modules/@wangeditor/plugin-formula/dist/index.js
* wangEditor in ./node_modules/@wangeditor/plugin-formula/dist/index.js

To install them, you can run: npm install --save WangEditorCore wangEditor

## 你预期的样子是？

正常使用

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
macos
chrome  99.0.4844.51

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

按照https://juejin.cn/post/7066954260142882823  文档使用wangEditor-plugin-formula

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
下载这个源码试试 https://github.com/wangfupeng1988/webpack-wangeditor-demo

源码里有 formula 插件的使用。

**Comment by wanzi-2** [comment]
> 

这个源码也同样会报错
Module not found: Error: Can't resolve 'wangEditor' in '/Users/maruko/Downloads/webpack-wangeditor-demo-main/node_modules/@wangeditor/plugin-formula/dist'
Module not found: Error: Can't resolve 'WangEditorCore' in '/Users/maruko/Downloads/webpack-wangeditor-demo-main/node_modules/@wangeditor/plugin-formula/dist'

**Comment by wangfupeng1988** [comment]
@wanzi-2 我用 demo 在本地运行，没这个问题

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/9583120/158126906-c0a7af4c-3ee6-4fe9-89ad-6fece5b86d0f.png">

你可以把 demo 搞到 codesanbox 中，看能否复现这个问题。

**Comment by wanzi-2** [comment]
这个源码在codesanbox中运行没有问题 https://github.com/wangfupeng1988/webpack-wangeditor-demo
但是在这个源码 https://github.com/wangfupeng1988/vue2-wangeditor-demo 里使用wangEditor-plugin-formula 时会报同样的错误
![WechatIMG451](https://user-images.githubusercontent.com/56372879/158144162-57ea322f-3933-48a3-bb64-8bab53e7640b.jpeg)

**Comment by wangfupeng1988** [comment]
@wanzi-2 已复现，会高优处理这个问题。

**Comment by wangfupeng1988** [comment]
已经解决。
需升级最新的 `@wangeditor/plugin-formula`
