### ISSUE TITLE
HTML加了contentEditable="false"属性的元素

### ISSUE THREAD

**Issue by qiang9420d** [wangeditor-team/wangEditor-v5#442]
## bug 描述

HTML加了contentEditable="false"属性的元素 没办法删除

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请说明复现步骤。

link card 插件也是 contentEditable="false" ，但它是可以删除的 https://github.com/wangeditor-team/wangEditor-plugin-link-card/blob/main/src/module/render-elem.ts#L44
