### ISSUE TITLE
同一页面新增多个编辑器填写内容后，移除某一个，只能倒序移除，乱序移除会导致对应的富文本内容回显错误

### ISSUE THREAD

**Issue by 1210649858** [wangeditor-team/wangEditor-v5#445]
## 问题描述

*页面通过表单动态新增富文本编辑器，多个富文本编辑器只能倒序删除，乱序删除会导致富文本的内容回显错误，由于我的表单数据是响应更新，其他表单组件都是正常的，只有富文本编辑器显示有误*

## wangEditor 版本

*  "@wangeditor/editor": "^0.15.13",
    "@wangeditor/editor-for-vue": "^0.6.14-3",*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
![image](https://user-images.githubusercontent.com/45088070/158510404-ce4e4d15-1576-49b6-a4ca-9936c3eaf6a0.png)

![image](https://user-images.githubusercontent.com/45088070/158510492-4ed13b71-8532-407b-a030-e4013ec80a2d.png)
如图我新增了两个富文本并且editorId是生成唯一的，由于一开始数据是已经绑定好所以在富文本编辑时是响应表单的更新的，
![image](https://user-images.githubusercontent.com/45088070/158511484-39526e37-18d4-4ca1-b498-c86b0e510c10.png)

当移除前第一个时候，第一个富文本数据同时被删除了，但是删除后第二个富文本还是回显的原先第一个富文本的值，
但我input是第二项的值，
这就说明删除第一项，富文本编辑器回显是有问题的，但是如果倒序删除先删除第二个那么就都是正常的不会出现这种情况

- 步骤二
- 步骤三

**Comment by liuqh0609** [comment]
麻烦问一下，您看您方便提供一下你在执行**删除操作时**的相关代码吗？

**Comment by liuqh0609** [comment]
大概知道你的问题了，你在`v-for` 的时候`key`值是用的数组的下标吧？
如果是的话，在你删除第一个编辑器时，你数组的下标会发生变化，下面的编辑器会重新渲染，其实显示的应该是你的`defaultcontent`而不是上一个被删除的编辑器的值。

这边给你一个方案。你编辑器`Id`生成的时候可以采用`uuid`，并且遍历的时候key值采用`wangEditorId`，不要用`index`。
你可以参考下面的代码：
```vue
<template>
  <div id="app">
    <div style="margin-bottom: 20px">
      <el-button type="primary" @click="handleAdd">新增编辑器</el-button>
    </div>
    <!--  注意这里的key值一定是唯一的，不要用index -->
    <div v-for="(item, index) in list" :key="item">
      <el-button type="danger" @click="() => handleDelete(index)"
        >删除</el-button
      >
      <my-editor :editor-id="item"></my-editor>
    </div>

  
  </div>
</template>

<script>
import MyEditor from "./components/MyEditor.vue";
import { v4 as uuidv4 } from "uuid";

export default {
  name: "App",
  components: {
    MyEditor,
  },
  data() {
    return {
      dialogVisible: false,
      list: [uuidv4()],
    };
  },
  methods: {
    // 编辑器id最好使用uuid来生成，不要用list的下标来生成。
    handleAdd() {
      this.list.push(uuidv4());
    },
    handleDelete(index) {
      console.log(`删除掉第${index}个编辑器`, this.list[index]);
      this.list.splice(index, 1);
    },
  },
};
</script>
```

**Comment by 1210649858** [comment]
> 大概知道你的问题了，你在`v-for` 的时候`key`值是用的数组的下标吧？ 如果是的话，在你删除第一个编辑器时，你数组的下标会发生变化，下面的编辑器会重新渲染，其实显示的应该是你的`defaultcontent`而不是上一个被删除的编辑器的值。
> 
> 这边给你一个方案。你编辑器`Id`生成的时候可以采用`uuid`，并且遍历的时候key值采用`wangEditorId`，不要用`index`。 你可以参考下面的代码：
> 
> ```
> <template>
>   <div id="app">
>     <div style="margin-bottom: 20px">
>       <el-button type="primary" @click="handleAdd">新增编辑器</el-button>
>     </div>
>     
>     <div v-for="(item, index) in list" :key="item">
>       <el-button type="danger" @click="() => handleDelete(index)"
>         >删除</el-button
>       >
>       <my-editor :editor-id="item"></my-editor>
>     </div>
> 
>   
>   </div>
> </template>
> 
> <script>
> import MyEditor from "./components/MyEditor.vue";
> import { v4 as uuidv4 } from "uuid";
> 
> export default {
>   name: "App",
>   components: {
>     MyEditor,
>   },
>   data() {
>     return {
>       dialogVisible: false,
>       list: [uuidv4()],
>     };
>   },
>   methods: {
>     // 编辑器id最好使用uuid来生成，不要用list的下标来生成。
>     handleAdd() {
>       this.list.push(uuidv4());
>     },
>     handleDelete(index) {
>       console.log(`删除掉第${index}个编辑器`, this.list[index]);
>       this.list.splice(index, 1);
>     },
>   },
> };
> </script>
> ```

是的由于我是把表单数据和编辑器渲染的结构数据分开处理的，换成编辑器Id作为key已经解决了，thanks!
