### ISSUE TITLE
使用问题:请问工具栏的图标和提示文字怎么修改呢

### ISSUE THREAD

**Issue by liuhai1024** [wangeditor-team/wangEditor-v5#446]
## 问题描述

*工具栏的图标和提示文字能修改吗 ?文档里半天没找到修改的方法*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/v5/guide/toolbar-config.html](https://www.wangeditor.com/v5/guide/toolbar-config.html) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 比如怎么把工具栏中"**默认字号**" 这几个字修改成图标

**Comment by wangfupeng1988** [comment]
暂不支持。

**Comment by liuhai1024** [comment]
最后手动修改了下源码 把原来那讨厌的 **默认字号 默认字体  默认行高** 给改成正常图标了
https://cdn.jsdelivr.net/npm/@wangeditor/editor@0.15.14/dist/index.min.js
**第80367个字节(改为图标显示)**  setSelectedValue  =>    o.html(""),o.text(r)   改为 o.html(t.iconSvg)
**第79277个字节(把宽度调整去掉)**  i&&c.css("width",i+"px")  改为  i
害我找了老半天才找到
