### ISSUE TITLE
如何获取toolbar工具栏的回调方法

### ISSUE THREAD

**Issue by NormanChen-csh** [wangeditor-team/wangEditor-v5#456]
目前应该是用的editor-to-vue的组件，貌似看起来没有支持点击或者change操作的回调，给自定义菜单栏开发增加了一定难度

**Comment by wangfupeng1988** [comment]
是用的 `@wangeditor/editor-for-vue` 这个吗？
https://www.wangeditor.com/v5/guide/for-frame.html#vue2

**Comment by NormanChen-csh** [comment]
> 

用的是这个@wangeditor/editor-for-vue。
我自定义的menu好像没有办法拿到点击后的回调
`class MySelectMenu {
	constructor() {
		this.title = '添加表单组件',
		this.tag = 'select'
		this.mark = 'testMenu'
	}

	getOptions() {
		return [
			{
        value: 'header1',
        text: 'H1',
				selected: true
      },
			{
        value: 'header2',
        text: 'H2',
      },
		]
	}
	getValue(editor) {
    return ''
	}
	isActive() { return false }
	isDisabled() { return false }
	exec(editor) {
		console.log(editor)
	}
}
const menuConf = {
	key: 'testMenu',
	factory() {
		return new MySelectMenu()
	}
}
Boot.registerMenu(menuConf)`

**Comment by wangfupeng1988** [comment]
我需要复现这个问题。
你可以在 codesandbox 中做一个 demo 来复现；或者先抛开 vue 环境，用一个最简单的 html 页面来复现这个问题。

**Comment by NormanChen-csh** [comment]
exec这个方法会执行，但是我考虑的是如何在vue组件调用回调方法，或者说有什么具体配置？
目前只发现uploadImage有回调函数可以进行自定义配置

**Comment by wangfupeng1988** [comment]
> 如何在vue组件调用回调方法

没懂这句话。建议你新创建一个 issue ，按照 issue 模板，把问题描述清楚吧。否则这样一句一句回复，效率也比较低。
