### ISSUE TITLE
cra项目中，热更新报错"Cannot find textarea instance by editor"

### ISSUE THREAD

**Issue by boiboif** [wangeditor-team/wangEditor-v5#457]
## bug 描述

create-react-app项目中，按照官方demo增加useEffect return销毁时，热更新会报错"Cannot find textarea instance by editor"

```
useEffect(() => {
        return () => {
            if (editor == null) return
            // 好像是destroy导致的
            editor.destroy()
            setEditor(null)
        }
    }, [editor])
```

## wangEditor 版本

"@wangeditor/editor": "^0.15.15",
"@wangeditor/editor-for-react": "^0.6.23",

## demo 能否复现该 bug ？

能

- demo https://codesandbox.io/s/distracted-leavitt-dbrjer?file=/src/App.js

**Comment by hahaaha** [comment]
确实有这个问题 会尽快修复的
