### ISSUE TITLE
如何在粘贴word文本时自动删除样式

### ISSUE THREAD

**Issue by itshizhan** [wangeditor-team/wangEditor-v5#463]
## bug 描述

因为目前还不能完全支持word本文的复制。
如果用户复制一段文本（比如word中的很简单的一个列表）后，直接粘贴，或使用CTRL + V 后，导致编辑器无法编辑。
回车后光标消失，自动有很多缩进。

## 你预期的样子是？

因为无法控制用户使用快捷键，除非明确告知用户粘贴纯文本。

有没有可能粘贴的时候自动去除样式的。

这样至少编辑器可以正常使用。

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

最新版本

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 word里面编辑一个列表
- 步骤二 复制到官方demo
- 步骤三 回车，光标丢失

**Comment by itshizhan** [comment]
应该是自动在父级上添加了一些样式导致的。
```
<p id="w-e-element-506" data-slate-node="element" style="text-indent: -21pt; text-align: justify;"><span id="w-e-text-513" data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">l 第一节</span></span></span></p>
<p id="w-e-element-506" data-slate-node="element" style="text-indent: -21pt; text-align: justify;"><span id="w-e-text-513" data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">2 第二节</span></span></span></p>
```
而且，回车后，p标签会自动带上这个style

**Comment by wangfupeng1988** [comment]
无法完全支持 word 格式，以及无法粘贴 word 里的图片 —— 这符合预期。
粘贴之后不能再次编辑 —— 这不符合预期。你可以就此单独提交一个 issue ，详细描述复现步骤，以及看看有没有 js 报错

如果想仅粘贴纯文本，可以看这里 https://www.wangeditor.com/v5/guide/editor-config.html#custompaste
