### ISSUE TITLE
请教：headerSelect 能否配置去掉 h4 ，h5 ？或者 insertKeys 能否插入正文？

### ISSUE THREAD

**Issue by YiQingWang** [wangeditor-team/wangEditor-v5#466]
## 问题描述

toolbarConfig：headerSelect 能否配置，想要去掉 h4, h5 只保留 1，2，3 和正文
或者 insertKeys 能否插入正文？

## wangEditor 版本

"@wangeditor/editor": "^0.15.15",
 "@wangeditor/editor-for-react": "^0.6.23",

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*
https://www.wangeditor.com/v5/guide/toolbar-config.html#toolbarkeys

**Comment by wangfupeng1988** [comment]
不支持 headerSelect 列表的配置。

你可以通过菜单栏配置（你发的文档链接），移除 `headerSelect` 菜单，并插入 `header1` `header2` `header3` 三个菜单

**Comment by wangfupeng1988** [comment]
不用“正文”菜单。

当光标在标题，再次点击菜单，就能取消标题。如下图

<img width="579" alt="image" src="https://user-images.githubusercontent.com/9583120/160726382-5f6ec5f7-b4ba-45f4-a209-9e8ce9bd5f6d.png">
