### ISSUE TITLE
内容在到达最底部时： hoverbar 中的 selectlist （如 headerselect 和 codelang）会超出底部无法展示全部

### ISSUE THREAD

**Issue by YiQingWang** [wangeditor-team/wangEditor-v5#467]
## bug 描述

![image](https://user-images.githubusercontent.com/16113453/160613187-e424a5e1-7b30-431c-b093-290423a4c88b.png)

## 你预期的样子是？

**hoverbar 能否到达底部时展示在内容上方？**

## 系统和浏览器及版本号

- macos 12.0.1 (21A559)
- Google Chrome  99.0.4844.84（正式版本） (x86_64)

## wangEditor 版本

官网 demo 版本；
本地版本：

        "@wangeditor/editor": "^0.15.15",
        "@wangeditor/editor-for-react": "^0.6.23",
都有问题

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

- 插入空行到即将到内容区域最底部
- 插入一句话，在hoverbar 选择 headerselect
- 全屏模式同上

**Comment by wangfupeng1988** [comment]
已经修复，升级 `@wangeditor/editor`最新版本即可。
