### ISSUE TITLE
在使用vue2.x组件时,调用dangerouslyInsertHtml或者insertText会出现以下异常报错,但是不影响使用

### ISSUE THREAD

**Issue by AceyKubbo** [wangeditor-team/wangEditor-v5#468]
![image](https://user-images.githubusercontent.com/20533272/160737166-6984c24b-d689-41fc-a211-6ed44fc9409f.png)

**Comment by wangfupeng1988** [comment]
昨天刚升级了一个 `dangerouslyInsertHtml` 相关的 bug ，升级最新的 https://www.npmjs.com/package/@wangeditor/editor 试试
