### ISSUE TITLE
toolbar 菜单图标无法自定义

### ISSUE THREAD

**Issue by jisaz** [wangeditor-team/wangEditor-v5#469]
## bug 描述

*toolbar 菜单图标无法自定义*

## 你预期的样子是？
*展示自定义的 toolbar 菜单图标*

## 系统和浏览器及版本号

- 操作系统
- mac
- 浏览器和版本
- chrome 99

## wangEditor 版本
0.15.15

**Comment by wangfupeng1988** [comment]
暂不支持
