### ISSUE TITLE
禁用了编辑editor.disable()，插入的表格可以继续编辑，可以点击

### ISSUE THREAD

**Issue by yiwen9488** [wangeditor-team/wangEditor-v5#470]
## bug 描述

禁用了编辑editor.disable()，插入的表格可以继续编辑，可以点击
## 你预期的样子是？

禁用了编辑editor.disable()，表格不可编辑

## 系统和浏览器及版本号
mac，谷歌浏览器，版本100.0.4896.60
- 操作系统
- 浏览器和版本

## wangEditor 版本
    "@wangeditor/editor": "^0.15.17",
## demo 能否复现该 bug ？
能

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

禁用编辑editor.disable()，编辑表格

**Comment by wangfupeng1988** [comment]
已修复。请更新 `@wangeditor/editor` 最新版本。
