### ISSUE TITLE
引入@wangeditor/editor/dist/css/style.css后报错：module build failed (from ../node_modules/sass-loader/dist/cjs.js): SassError: Only 3 elements allowed, but 4 were passed.

### ISSUE THREAD

**Issue by Natsumeo** [wangeditor-team/wangEditor-v5#471]
## 问题描述
引入@wangeditor/editor/dist/css/style.css后报错：odule build failed (from ../node_modules/sass-loader/dist/cjs.js): SassError: Only 3 elements allowed, but 4 were passed.具体如下：

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/39702370/161050975-934171dd-6a16-4bb4-b637-9ce7268a997c.png">

## wangEditor 版本
@wangeditor/editor-for-vue": "^0.6.12-5"

## sass-loader版本
sass-loader "^12.1.0"

## 是否查阅了文档 ？

（文档链接：https://stackoverflow.com/questions/16581791/wrong-number-of-arguments-4-for-3-for-rgb-issue-in-css-scss-file-in-rails-3）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
之前有曾报过类似的问题，我再继续排查一下吧。

你能否提供一个简单的 demo （能复现 bug 即可，不要掺杂其他无关代码）？以帮助我快速复现 bug 。

**Comment by Natsumeo** [comment]
使用的时候没有做特殊操作，是按照您的这篇文档https://juejin.cn/post/7030722267264843783/进行配置的，查了报错问题：[https://stackoverflow.com/questions/16581791/wrong-number-of-arguments-4-for-3-for-rgb-issue-in-css-scss-file-in-rails-3](https://stackoverflow.com/questions/16581791/wrong-number-of-arguments-4-for-3-for-rgb-issue-in-css-scss-file-in-rails-3%EF%BC%89)，怀疑是sass版本的问题，项目里的一些相关配置：sass：1.39.0、sass-loader "^12.1.0"，之前项目上线急需，是把**@wangeditor/editor/dist/css/style.css**文件中的**rgba(0,0,0,.12)**改为**rgba(0, 0, 0, 0.2)**解决的

**Comment by wangfupeng1988** [comment]
@Natsumeo  你把 css 中的 `rgba(0,0,0,.12)` 改为 `#0000001f` ，看是否可以？

**Comment by wangfupeng1988** [comment]
> @Natsumeo 你把 css 中的 `rgba(0,0,0,.12)` 改为 `#0000001f` ，看是否可以？

`@wangeditor/editor` 最新版本已经改成了这种形式。

**Comment by Natsumeo** [comment]
改为 #0000001f是可以的，大佬@wangeditor/editor-for-vue可以辛苦同步更新一下吗，我们现在用的是Vue2的版本，目前我是把样式代码拷贝了一份在自己的代码中引进的

**Comment by wangfupeng1988** [comment]
`@wangeditor/editor-for-vue` 这个不用改。直接升级 `@wangeditor/editor` 即可。

**Comment by Natsumeo** [comment]
之前比较疑惑，为什么在安装@wangeditor/editor-for-vue的时候也要引入@wangeditor/editor，是前者复用了后者样式吗，想请问一下大佬这两个包主要的关联是？

**Comment by wangfupeng1988** [comment]
@wangeditor/editor-for-vue 仅仅是封装了一个 Vue 组件，核心代码都在 @wangeditor/editor 里。

**Comment by Natsumeo** [comment]
哦哦，明白了，谢谢啦～
