### ISSUE TITLE
表格生成的html没有style

### ISSUE THREAD

**Issue by chencheng666** [wangeditor-team/wangEditor-v5#476]
## bug 描述
![image](https://user-images.githubusercontent.com/32317552/162109297-e8b36b80-faa7-43df-80ed-8f6e8f6f400c.png)

*表格在编辑态有样式 是在样式表里 parse html后无样式*
![image](https://user-images.githubusercontent.com/32317552/162109491-6b76de0e-f880-4531-a448-42684af3c326.png)
![image](https://user-images.githubusercontent.com/32317552/162109547-1488ee1f-2869-4da3-a360-3a47b0ebaec6.png)

**Comment by wangfupeng1988** [comment]
编辑器只生成纯 HTML ，需要你自定义样式。

可参考 demo https://www.wangeditor.com/demo/get-html.html  ，以及网页源码中的 `https://www.wangeditor.com/demo/css/view.css`

**Comment by chencheng666** [comment]
好的 谢谢~


| |
陈成
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年04月7日 ***@***.***> 写道：

Closed #476.
