### ISSUE TITLE
安卓 移动端暗黑模式下 选择图片 （拍照、图片）弹出的窗口是白色的文字也是白色

### ISSUE THREAD

**Issue by chencheng666** [wangeditor-team/wangEditor-v5#478]
## bug 描述
安卓 移动端暗黑模式下 选择图片 （拍照、图片）弹出的窗口是白色的文字也是白色
*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统 安卓 小米手机
- 浏览器和版本

## wangEditor 版本
当前最新版本

- 中文 demo https://www.wangeditor.com/demo/zh-CN
- English demo https://www.wangeditor.com/demo/en

## 感觉可能是不是 富文本的问题 可能是系统的弹出层导致的 我暂时无法确认 ，还是麻烦大神看下
![image](https://user-images.githubusercontent.com/32317552/162376179-1478444f-2070-4a98-8be7-0875c437fe76.png)

**Comment by wangfupeng1988** [comment]
你看下这个白色区域的 DOM 节点，它的 CSS `class` 是什么？

**Comment by chencheng666** [comment]
谢谢回复~~~  我看了下 这个应该是原生的 ，我暂时没法调试这个小米手机， 我查了下 代码没有找到拍照相关的文本，应该是input type为file时候默认的原生样式，可能和我的手机 原生适配有关，非暗黑时候如下图
| |
陈成
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年04月8日 ***@***.***> 写道：

你看下这个白色区域的 DOM 节点，它的 CSS class 是什么？
