### ISSUE TITLE
edge 浏览器 输入法输入文字与placeholder重叠

### ISSUE THREAD

**Issue by q378532364** [wangeditor-team/wangEditor-v5#88]
## bug 描述

输入法输入文字与placeholder重叠

## 你预期的样子是？

输入法输入文字输入后 placeholder不显示

## 浏览器及版本号
all
## wangEditor 版本

v5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1. 清空编辑器
2. 输入文字不按空格

**Comment by wangfupeng1988** [comment]
最新代码已解决这个问题 https://github.com/wangeditor-team/wangEditor-v5/commit/aec1a9f62af8944b7894beeca953076ec73545d5
